karafka/karafka

- lib/karafka.rb
- lib/karafka/params.rb
- lib/karafka/router.rb
- spec/lib/karafka/params_spec.rb
https://trello.com/c/MGuhPdt7/10-karafka-params-for-kafka-framework
> Add params

- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/karafka.rb
- lib/karafka/app.rb
- lib/karafka/base_controller.rb
- lib/karafka/connection/actor_cluster.rb
- lib/karafka/connection/consumer.rb
- lib/karafka/connection/listener.rb
- lib/karafka/connection/queue_consumer.rb
- lib/karafka/monitor.rb
- lib/karafka/process.rb
- lib/karafka/runner.rb
- lib/karafka/version.rb
- lib/karafka/workers/base_worker.rb
- spec/lib/karafka/connection/actor_cluster_spec.rb
- spec/lib/karafka/connection/consumer_spec.rb
- spec/lib/karafka/connection/listener_spec.rb
- spec/lib/karafka/monitor_spec.rb
- spec/lib/karafka/process_spec.rb
- spec/lib/karafka/runner_spec.rb
- spec/lib/karafka_spec.rb
> Monitoring

- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/karafka/cli/info.rb
- lib/karafka/connection/broker_manager.rb
- lib/karafka/setup/config.rb
- lib/karafka/version.rb
- spec/lib/karafka/cli/info_spec.rb
- spec/lib/karafka/connection/broker_manager_spec.rb
@agwozdowski @pavlo-vavruk  please review. This is based on work of @jwkoelewijn from #86 - thank you very much!
> Jwkoelewijn zookeeper namespace support

- CHANGELOG.md
- lib/karafka/base_responder.rb
- spec/lib/karafka/base_responder_spec.rb
#97 
@agwozdowski  @pavlo-vavruk
> prevalidation

- README.md
> add Heroku deployment info to README

- README.md
This PR changes the build badges to SVG for sharper readability ✨
> README: Use SVG build badge, point to master

- CHANGELOG.md
- lib/karafka/attributes_map.rb
- lib/karafka/connection/api_adapter.rb
- lib/karafka/connection/client.rb
- lib/karafka/errors.rb
- lib/karafka/schemas/consumer_group.rb
- lib/karafka/setup/config.rb
- spec/lib/karafka/attributes_map_spec.rb
- spec/lib/karafka/connection/api_adapter_spec.rb
- spec/lib/karafka/connection/client_spec.rb
- spec/lib/karafka/schemas/consumer_group_spec.rb
> #320 and #318

- lib/karafka/process.rb
- lib/karafka/server.rb
- spec/lib/karafka/backends/inline_spec.rb
- spec/lib/karafka/process_spec.rb
- spec/lib/karafka/server_spec.rb
> yield removed

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- lib/karafka/attributes_map.rb
- lib/karafka/connection/api_adapter.rb
- lib/karafka/connection/client.rb
- spec/lib/karafka/attributes_map_spec.rb
- spec/lib/karafka/connection/api_adapter_spec.rb
> Manual offset for custom mappers

- lib/karafka/connection/builder.rb
- lib/karafka/connection/client.rb
- spec/lib/karafka/connection/builder_spec.rb
- spec/lib/karafka/connection/client_spec.rb
- spec/lib/karafka/connection/listener_spec.rb
Kafka client will be used in other places, so extracted to DRY.
> kafka client contruction extraction

- bin/karafka
- lib/karafka/app.rb
- lib/karafka/base_responder.rb
- lib/karafka/cli/server.rb
- lib/karafka/errors.rb
- lib/karafka/instrumentation/monitor.rb
- lib/karafka/persistence/client.rb
- lib/karafka/routing/builder.rb
- lib/karafka/server.rb
- lib/karafka/setup/config.rb
- spec/lib/karafka/base_responder_spec.rb
- spec/lib/karafka/cli/server_spec.rb
- spec/lib/karafka/errors_spec.rb
- spec/lib/karafka/instrumentation/monitor_spec.rb
- spec/lib/karafka/persistence/client_spec.rb
- spec/lib/karafka/routing/builder_spec.rb
- spec/lib/karafka/setup/config_spec.rb
> add postfix Error to all exception classes

- lib/karafka/setup/config.rb
> add default value to config seed_brokers

- CHANGELOG.md
- lib/karafka/params/params.rb
- lib/karafka/params/params_batch.rb
- spec/lib/karafka/params/params_batch_spec.rb
- spec/lib/karafka/params/params_spec.rb
> Params and params batch naming cleanup

- CHANGELOG.md
- lib/karafka/consumers/single_params.rb
- spec/lib/karafka/consumers/single_params_spec.rb
> Single params consuming mode automatically parses data spec

- lib/karafka/base_consumer.rb
- lib/karafka/connection/client.rb
- spec/lib/karafka/base_consumer_spec.rb
- spec/lib/karafka/connection/client_spec.rb
> #354 for 1.3 - expose consumer heartbeat

- CHANGELOG.md
- lib/karafka/base_responder.rb
- spec/lib/karafka/base_responder_spec.rb
> Async producer not working properly with responders

- CHANGELOG.md
- lib/karafka.rb
- lib/karafka/base_consumer.rb
- lib/karafka/params/params.rb
- spec/lib/karafka/params/params_spec.rb
close: https://github.com/karafka/karafka/issues/375
> Fix for parser mismatch

- CHANGELOG.md
- Gemfile.lock
- karafka.gemspec
- lib/karafka.rb
- lib/karafka/base_responder.rb
- spec/lib/karafka/cli/flow_spec.rb
- spec/lib/karafka/params/params_spec.rb
- spec/spec_helper.rb
> Removes AS direct dependency

- CHANGELOG.md
- lib/karafka.rb
- lib/karafka/templates/karafka.rb.example
> Better Rails logging

- CHANGELOG.md
- Gemfile.lock
- config/errors.yml
- karafka.gemspec
- lib/karafka/schemas/consumer_group.rb
- lib/karafka/setup/config.rb
- spec/lib/karafka/schemas/consumer_group_spec.rb
https://github.com/karafka/karafka/issues/388
> ssl_client_cert_chain sync

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/connection/listener.rb
- lib/karafka/version.rb
- spec/lib/karafka/connection/listener_spec.rb
close https://github.com/karafka/karafka/issues/414
> Backport to 1.2 the delayed retry upon failure

- CHANGELOG.md
- lib/karafka/base_responder.rb
- lib/karafka/cli/flow.rb
- lib/karafka/responders/topic.rb
- lib/karafka/schemas/responder_usage.rb
- spec/lib/karafka/responders/topic_spec.rb
- spec/lib/karafka/schemas/responder_usage_spec.rb
close https://github.com/karafka/karafka/issues/393
> Reorganize responders - remove constrains on multiple_usage

- CHANGELOG.md
- lib/karafka.rb
Closes https://github.com/karafka/karafka/issues/452
> require forwardable

- Gemfile.lock
- lib/karafka/params/builders/params.rb
- lib/karafka/params/params.rb
- lib/karafka/params/params_batch.rb
- spec/lib/karafka/params/builders/params_spec.rb
- spec/lib/karafka/params/params_batch_spec.rb
- spec/lib/karafka/params/params_spec.rb
> rename value to payload

- CHANGELOG.md
- Gemfile.lock
- config/errors.yml
- lib/karafka/schemas/consumer_group.rb
- lib/karafka/setup/config.rb
- spec/lib/karafka/schemas/consumer_group_spec.rb
close https://github.com/karafka/karafka/issues/473
> Support SASL OAuthBearer Authentication

- CHANGELOG.md
- lib/karafka/server.rb
- spec/lib/karafka/server_spec.rb
close https://github.com/karafka/karafka/issues/502
> forced kill

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/schemas/consumer_group.rb
- lib/karafka/setup/config.rb
- spec/lib/karafka/connection/api_adapter_spec.rb
- spec/lib/karafka/connection/builder_spec.rb
- spec/lib/karafka/schemas/consumer_group_spec.rb
close https://github.com/karafka/karafka/issues/506
> ssl_verify_hostname sync

- CHANGELOG.md
- lib/karafka/connection/listener.rb
- spec/lib/karafka/connection/listener_spec.rb
close https://github.com/karafka/karafka/issues/508
> Reset the consumers instances upon reconnecting to a cluster #508

- CHANGELOG.md
- lib/karafka/cli/install.rb
Fixes https://github.com/karafka/karafka/issues/549
> create lib and app/workers directories

- Gemfile.lock
- karafka.gemspec
@mensfeld Tried to follow the same commit message format you guys do for gem bumping 👌 
closes #559
> bump-gems-2019-12-18

- Gemfile.lock
https://diff.coditsu.io/gems/activesupport/6.0.2.1/6.0.2.2
> bump-gems-2020-03-23

- Gemfile.lock
https://my.diffend.io/gems/activesupport/6.0.3.1/6.0.3.2
https://my.diffend.io/gems/dry-validation/1.5.0/1.5.1
> bump-gems-2020-06-18

- lib/karafka/params/params.rb
- spec/lib/karafka/params/builders/params_spec.rb
Related to: https://github.com/karafka/karafka/pull/604
> Add backward compatibility for params metadata attributes

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/version.rb
> 1.4.2 release

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/version.rb
ref https://github.com/karafka/karafka/issues/665
> 1.4.3 release

- lib/karafka/connection/api_adapter.rb
- lib/karafka/connection/client.rb
- spec/lib/karafka/connection/api_adapter_spec.rb
- spec/lib/karafka/connection/client_spec.rb
Aims to tackle https://github.com/karafka/karafka/issues/699
> Fix Ruby 3 compatibility issues in Connection::Client#pause

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/setup/config.rb
- lib/karafka/version.rb
- spec/lib/karafka/assignment_strategies/round_robin_spec.rb
- spec/lib/karafka/connection/api_adapter_spec.rb
- spec/lib/karafka/connection/builder_spec.rb
This PR syncs with ruby-kafk 1.4
> ruby-kafka api sync

- lib/karafka/base_consumer.rb
- lib/karafka/connection/client.rb
- lib/karafka/connection/listener.rb
- lib/karafka/messages/seek.rb
- lib/karafka/processing/worker.rb
- spec/integrations/seek_to_a_given_offset_from_consumer.rb
- spec/lib/karafka/base_consumer_spec.rb
- spec/lib/karafka/messages/seek_spec.rb
While working with seeking, I noticed it is rather cumbersome. This PR improves the in-consumer seeking by allowing to use per context data within.
> Improved in-consumer seek

- spec/integrations/consumption/removing_a_topic_should_still_consume_rest.rb
- spec/integrations/consumption/simple_from_earliest.rb
covers this case: https://github.com/karafka/karafka/issues/727
> cover 1.4 error report with integration for 2.0

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- lib/active_job/consumer.rb
- lib/active_job/karafka.rb
- lib/active_job/queue_adapters/karafka_adapter.rb
- lib/active_job/routing_extensions.rb
- lib/karafka.rb
- lib/karafka/cli/install.rb
- lib/karafka/railtie.rb
- lib/karafka/templates/karafka.rb.erb
- spec/integrations/consumption/two_consumer_groups_one_active.rb
- spec/lib/active_job/consumer_spec.rb
- spec/lib/active_job/karafka_spec.rb
- spec/lib/active_job/queue_adapters/karafka_adapter_spec.rb
- spec/lib/active_job/routing_extensions_spec.rb
- spec/lib/karafka/process_spec.rb
- spec/lib/karafka_spec.rb
- spec/spec_helper.rb
- spec/support/factories/messages/metadata.rb
This PR includes:
- activejob adapter
- more specs
- install template updates
> ActiveJob, more specs and install

- CHANGELOG.md
- bin/benchmarks
- bin/integrations
- bin/stress
- docker-compose.yml
- spec/benchmarks/io/multiple_workers_multiple_partitions.rb
- spec/benchmarks/pass_through/multiple_workers_multiple_partitions.rb
- spec/benchmarks/pass_through/single_worker_multiple_partitions.rb
- spec/benchmarks/pass_through/single_worker_single_partition.rb
- spec/benchmarks_helper.rb
This PR adds benchmarks in specs. Those can be used to check karafka performance
> Benchmarks setup

- CHANGELOG.md
- Gemfile.lock
- karafka.gemspec
- lib/karafka/base_consumer.rb
- lib/karafka/connection/listener.rb
- lib/karafka/errors.rb
- lib/karafka/instrumentation/callbacks/error.rb
- lib/karafka/instrumentation/monitor.rb
- lib/karafka/instrumentation/stdout_listener.rb
- lib/karafka/processing/worker.rb
- lib/karafka/runner.rb
- lib/karafka/server.rb
- spec/integrations/consumption/non_constant_error_and_other_topics.rb
- spec/integrations/consumption/non_critical_error_recovery.rb
- spec/integrations/consumption/worker_critical_error_behaviour.rb
- spec/integrations/instrumentation/error_callback_multiple_subscription_groups.rb
- spec/integrations/instrumentation/error_callback_subscription.rb
- spec/lib/karafka/base_consumer_spec.rb
- spec/lib/karafka/connection/listener_spec.rb
- spec/lib/karafka/instrumentation/callbacks/error_spec.rb
- spec/lib/karafka/instrumentation/monitor_spec.rb
- spec/lib/karafka/instrumentation/stdout_listener_spec.rb
- spec/lib/karafka/runner_spec.rb
justification here: https://github.com/karafka/waterdrop/pull/225
close https://github.com/karafka/karafka/issues/750
> #750 - Unify error publisher keys to a single key

- karafka.gemspec
ref https://github.com/karafka/karafka/issues/764
> mfa flag for karafka 2.0

- config/errors.yml
- lib/karafka/contracts/config.rb
- spec/integrations/config_validation.rb
- spec/lib/karafka/contracts/config_spec.rb
superseeds https://github.com/karafka/karafka/pull/782
close https://github.com/karafka/karafka/pull/782
> ensure, that all kafka keys are strings

- Gemfile.lock
- bin/integrations
- lib/karafka/cli/install.rb
- lib/karafka/templates/karafka.rb.erb
- spec/integrations/installation/standalone/Gemfile
- spec/integrations/installation/standalone/install.rb
- spec/integrations/installation/with_rails/Gemfile
- spec/integrations/installation/with_rails/install.rb
- spec/integrations/pro/rails/rails5/Gemfile
- spec/integrations/pro/rails/rails6/Gemfile
- spec/integrations/pro/rails/rails7/Gemfile
- spec/integrations/rails/rails5/Gemfile
- spec/integrations/rails/rails7/Gemfile
This PR fixes a bug where installation would not work. It also adds some specs for regression.
> Installation flow fix + integration specs for standalone and Rails

- spec/integrations/consumption/with_lazy_payload_deserialization.rb
close https://github.com/karafka/karafka/issues/802
> Lazy messages deserialization integration spec

- CHANGELOG.md
- Gemfile.lock
- bin/integrations
- lib/karafka/railtie.rb
- lib/karafka/version.rb
- spec/integrations/rails/rails6/without-a-boot-file/Gemfile
- spec/integrations/rails/rails6/without-a-boot-file/railtie_setup.rb
close https://github.com/karafka/karafka/issues/818
close https://github.com/karafka/karafka/issues/820
> fix invalid error upon missing boot file + ensure stability of pristine specs

- lib/karafka/connection/client.rb
- lib/karafka/connection/rebalance_manager.rb
- lib/karafka/setup/config.rb
- spec/lib/karafka/connection/rebalance_manager_spec.rb
This PR makes the rebalance manager a bit cleaner. No external changes.
> improve rebalance manager

- CHANGELOG.md
- docker-compose.yml
- lib/karafka/connection/client.rb
- lib/karafka/connection/messages_buffer.rb
- lib/karafka/connection/rebalance_manager.rb
- spec/integrations/rebalancing/on_partition_data_revoked.rb
- spec/integrations/rebalancing/without_using_revoked_partition_data.rb
- spec/lib/karafka/connection/messages_buffer_spec.rb
- spec/lib/karafka/connection/rebalance_manager_spec.rb
- spec/spec_helper.rb
- spec/support/factories/messages/metadata.rb
close https://github.com/karafka/karafka/issues/825
> Optimize rebalancing behaviours

- CHANGELOG.md
- lib/karafka/connection/client.rb
- lib/karafka/connection/rebalance_manager.rb
- spec/integrations/rebalancing/on_partition_data_revoked.rb
- spec/integrations/rebalancing/without_using_revoked_partition_data.rb
- spec/lib/karafka/app_spec.rb
- spec/lib/karafka/connection/rebalance_manager_spec.rb
close https://github.com/karafka/karafka/issues/828
> optimize additional consumer shutdown in integration specs

- docker-compose.yml
- spec/integrations/rebalancing/with_static_membership_reconnect.rb
- spec/integrations/rebalancing/without_using_revoked_partition_data.rb
ref https://github.com/karafka/karafka/issues/774
> Add static membership integration spec

- spec/integrations/consumption/non_critical_error_constant_backoff.rb
- spec/integrations/consumption/non_critical_error_exponential_backoff.rb
This PR adds missing specs for a cases of backoff handling
> backoffspecs

- lib/karafka/connection/listener.rb
- lib/karafka/connection/messages_buffer.rb
- lib/karafka/contracts/config.rb
- lib/karafka/scheduler.rb
- lib/karafka/setup/config.rb
- spec/integrations/consumption/non_critical_error_exponential_backoff.rb
- spec/integrations_helper.rb
- spec/lib/karafka/connection/messages_buffer_spec.rb
- spec/lib/karafka/contracts/config_spec.rb
- spec/lib/karafka/scheduler_spec.rb
close https://github.com/karafka/karafka/issues/757
> extract scheduler out of listener

- Gemfile.lock
- spec/integrations/rebalancing/on_partition_data_revoked.rb
just a maintenance update + extended sleep for one of the specs to improve stability.
> gem bump + spec stability fix

- CHANGELOG.md
> 2.0.0.beta1 release

- spec/integrations/pausing/prolonging_manual_pause.rb
This PR adds an integration spec that checks if we can pause an already paused partition.
> prolonged pause spec

- CHANGELOG.md
- lib/karafka/base_consumer.rb
- lib/karafka/pro/active_job/consumer.rb
- lib/karafka/processing/executor.rb
- spec/integrations/consumption/with_prepare_method.rb
- spec/lib/karafka/base_consumer_spec.rb
- spec/lib/karafka/pro/active_job/consumer_spec.rb
- spec/lib/karafka/processing/executor_spec.rb
close https://github.com/karafka/karafka/issues/872
> Rename #prepared to #prepare in consumer to reflect its usecase

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/connection/listener.rb
- lib/karafka/contracts/config.rb
- lib/karafka/pro/loader.rb
- lib/karafka/pro/processing/partitioner.rb
- lib/karafka/processing/partitioner.rb
- lib/karafka/setup/config.rb
- lib/karafka/version.rb
- spec/integrations/pro/licensing/configure_with_expired_token_non_dev.rb
- spec/integrations/pro/licensing/configure_with_invalid_token.rb
- spec/integrations/pro/licensing/configure_with_valid_token.rb
- spec/lib/karafka/contracts/config_spec.rb
- spec/lib/karafka/pro/processing/partitioner_spec.rb
- spec/lib/karafka/processing/partitioner_spec.rb
This PR extracts the processing partitioner logic out of the listener code.
> Extract partitioner out of listener

- CHANGELOG.md
- lib/karafka/templates/example_consumer.rb.erb
> Fix example template

- CHANGELOG.md
> v2.0.0.rc2 release

- CHANGELOG.md
- lib/karafka/setup/config.rb
This PR alters defaults to make the system respond faster.
close https://github.com/karafka/karafka/issues/915
> Change max_wait_time and max_messages defaults

- CHANGELOG.md
- lib/karafka/connection/client.rb
- spec/integrations/pro/consumption/virtual_partitions/many_batches.rb
- spec/integrations/pro/consumption/virtual_partitions/many_distributed_batches_end_order.rb
- spec/integrations/pro/consumption/virtual_partitions/with_error.rb
- spec/integrations/pro/consumption/virtual_partitions/with_error_on_another_batch.rb
- spec/integrations/rebalancing/constant_rebalance_continuity.rb
part of https://github.com/karafka/karafka/issues/897
> More integration specs

- spec/integrations/pro/consumption/long_running_jobs/with_continuous_error.rb
part of https://github.com/karafka/karafka/issues/897
> lrj continuous error spec

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/version.rb
- Remove `dry-monitor`
- Use `karafka-core`
> v2.0.0.rc4

- CHANGELOG.md
- lib/karafka/pro/base_consumer.rb
- lib/karafka/pro/routing/topic_extensions.rb
- spec/integrations/consumption/time_bound_consumption.rb
- spec/integrations/pro/consumption/vp_with_lrj_from_earliest.rb
- spec/integrations/pro/routing/pro_with_long_running_job.rb
This PR just fixes some naming.
> align naming of virtual partitions

- CHANGELOG.md
- bin/integrations
- lib/karafka/connection/client.rb
- lib/karafka/connection/listener.rb
- lib/karafka/patches/rdkafka/consumer.rb
- lib/karafka/server.rb
- spec/integrations/shutdown/on_hanging_listener_and_shutdown.rb
- spec/lib/karafka/server_spec.rb
This PR improves the forceful shutdown scenario. It finalizes the librdkafka consumer to prevent memory leaks.
> Improve forceful shutdown

- CHANGELOG.md
- Gemfile.lock
- karafka.gemspec
- spec/integrations/pro/consumption/virtual_partitions/distributing_work_randomly.rb
This PR improves the integration spec that checks threads usage.
> Improve integration spec

- CHANGELOG.md
- Gemfile.lock
- karafka.gemspec
- lib/karafka/instrumentation/callbacks/statistics.rb
- lib/karafka/version.rb
This PR replaces the waterdrop stats decorator with one from the core.
> Replace stats decorator from waterdrop with the core one

- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/karafka/version.rb
> v2.0.0 changelog

- spec/integrations/consumption/non_critical_error_pause_no_marking.rb
- spec/integrations/consumption/non_critical_error_pause_position_marking.rb
This PR adds two extra specs to cover retries with marking
> Add two extra specs

- CHANGELOG.md
> v2.0.1 release

- lib/karafka/admin.rb
Since we do not create instances of admin, should not be a class.
> replace class with a module

- CHANGELOG.md
> v2.0.2 release

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/cli/info.rb
- lib/karafka/cli/server.rb
- lib/karafka/instrumentation/logger_listener.rb
- lib/karafka/version.rb
- spec/lib/karafka/cli/info_spec.rb
- spec/lib/karafka/instrumentation/logger_listener_spec.rb
This PR aligns the startup info to provide more details on Karafka and Ruby. No API changes.
> More descriptive startup info

- lib/karafka/base_consumer.rb
- lib/karafka/processing/result.rb
- spec/lib/karafka/processing/coordinator_spec.rb
- spec/lib/karafka/processing/result_spec.rb
This PR introduces processing failure cause tracking for things like DLQ.
close https://github.com/karafka/karafka/issues/979
> track failure cause in processing

- spec/lib/karafka/active_job/dispatcher_spec.rb
This PR adds "time freeze" to time sensitive specs.
> Optimize time sensitive spec

- spec/integrations/pro/rebalancing/long_running_jobs/continuity_after_error_and_rebalance.rb
close https://github.com/karafka/karafka/issues/986
> add one more integration spec case

- spec/integrations/pro/rails/active_job/virtual_partitions/from_earliest.rb
- spec/integrations/pro/rebalancing/long_running_jobs/revoke_mark_as_consumed_sync_not_enough_threads.rb
- spec/lib/karafka/time_trackers/poll_spec.rb
close https://github.com/karafka/karafka/issues/990
> Make poll real time specs independent

- spec/integrations/consumption/multi_topic_ping_pong.rb
close https://github.com/karafka/karafka/issues/1008
> Multi topic ping pong spec #1008

- spec/integrations/pro/consumption/long_running_jobs/parallel_non_lrj_with_lrj.rb
close https://github.com/karafka/karafka/issues/1009
> lrj non-blocking spec

- CHANGELOG.md
> v2.0.6 release

- CHANGELOG.md
- config/errors.yml
- lib/karafka/pro/contracts/consumer_group_topic.rb
- lib/karafka/pro/processing/partitioner.rb
- lib/karafka/pro/routing/topic_extensions.rb
- spec/integrations/pro/consumption/virtual_partitions/with_limited_concurrency.rb
- spec/integrations/pro/consumption/virtual_partitions/with_more_vps_than_workers.rb
- spec/lib/karafka/pro/contracts/consumer_group_spec.rb
- spec/lib/karafka/pro/contracts/consumer_group_topic_spec.rb
close https://github.com/karafka/karafka/issues/1023
> rename VP concurrency to max_partitions

- spec/integrations/pro/rebalancing/long_running_jobs/revoke_mark_as_consumed_enough_threads.rb
Finishes polling in rdkafka in the consumer to prevent shutdown issues
> improve spec stability

- CHANGELOG.md
- lib/karafka/routing/builder.rb
- lib/karafka/routing/consumer_group.rb
- spec/integrations/consumption/with_mixed_subscription_groups.rb
- spec/integrations/consumption/with_separate_subscription_groups.rb
- spec/integrations/instrumentation/statistics_on_lag_with_many_sub_group.rb
- spec/integrations/instrumentation/statistics_on_lag_with_one_sub_group.rb
- spec/integrations/routing/routing_with_subscription_groups_arg_based.rb
- spec/integrations/routing/routing_with_subscription_groups_block_based.rb
- spec/lib/karafka/routing/builder_spec.rb
close https://github.com/karafka/karafka/issues/1030
> allow for block based subscription groups definitions

- lib/karafka/base_consumer.rb
- lib/karafka/pro/base_consumer.rb
- lib/karafka/processing/jobs/base.rb
- lib/karafka/processing/jobs_queue.rb
Just some minor typos I found while reading the code
> Fix typo in comment

- Gemfile.lock
- lib/karafka/serialization/json/deserializer.rb
- spec/integrations/consumption/of_a_tombstone_record.rb
- spec/integrations/consumption/of_an_post_tombstone_message.rb
- spec/integrations_helper.rb
close https://github.com/karafka/karafka/issues/1047
> Spec out log compaction via tombstone

- spec/integrations/rebalancing/cooperative_sticky_full.rb
- spec/integrations_helper.rb
cooperative sticky part of https://github.com/karafka/karafka/issues/1053
> #1053 cooperative-sticky-full-spec

- CHANGELOG.md
- lib/karafka/base_consumer.rb
- spec/integrations/offset_management/with_marking_older_message.rb
- spec/lib/karafka/active_job/consumer_spec.rb
- spec/lib/karafka/base_consumer_spec.rb
- spec/lib/karafka/pro/base_consumer_spec.rb
- spec/support/factories/processing/coordinator.rb
close https://github.com/karafka/karafka/issues/1053
> #1053 - ignore marking as consumed for older offsets

- Gemfile.lock
- karafka.gemspec
- lib/karafka.rb
Solves https://github.com/karafka/karafka/issues/1064
Updated dependencies to make sure it's gonna work properly and indeed, without explicitly requiring concurrent-ruby I couldn't even rspec.
> require concurrent-ruby

- CHANGELOG.md
- lib/karafka/routing/subscription_group.rb
- lib/karafka/setup/attributes_map.rb
- lib/karafka/setup/config.rb
- spec/integrations/consumption/with_separate_subscription_groups.rb
- spec/integrations/pausing/pause_early_and_skip_via_marking.rb
- spec/integrations/setup/attributes_distribution.rb
- spec/integrations_helper.rb
- spec/lib/karafka/setup/attributes_map_spec.rb
close https://github.com/karafka/karafka/issues/776
This PR makes sure, we do not add settings that do not match target and adds spec that keeps an eye on potential new options in librdkafka.
it also improves spec suite stability
> Provide attributes map for stripping non applicable settings on librdkafka

- CHANGELOG.md
- lib/karafka/time_trackers/pause.rb
- lib/karafka/time_trackers/poll.rb
close https://github.com/karafka/karafka/issues/1073
> Fix a pause-resume-expire race condition for LRJ

- CHANGELOG.md
- lib/karafka/pro/processing/partitioner.rb
- spec/integrations/pro/consumption/virtual_partitions/consistent_distribution_spec.rb
- spec/integrations/pro/consumption/virtual_partitions/with_more_vps_than_workers_spec.rb
close https://github.com/karafka/karafka/issues/1083
> consistent VP partioning consumer instance assignment

- spec/integrations/consumption/non_critical_error_post_error_action.rb
- spec/integrations/offset_management/rebalance_commit_spec.rb
close https://github.com/karafka/karafka/issues/1089
> Spec for post error cleaning operations

- CHANGELOG.md
- lib/karafka/base_consumer.rb
- spec/integrations/consumption/strategies/dlq/without_intermediate_marking_spec.rb
- spec/integrations/consumption/with_error_for_seek_offset_tracking_spec.rb
- spec/integrations/shutdown/on_hanging_listener_and_shutdown_spec.rb
close https://github.com/karafka/karafka/issues/1113
> include seek_offset in the event payload

- CHANGELOG.md
- lib/karafka/errors.rb
- lib/karafka/server.rb
- lib/karafka/setup/attributes_map.rb
- spec/lib/karafka/instrumentation/logger_listener_spec.rb
- spec/lib/karafka/server_spec.rb
close https://github.com/karafka/karafka/issues/1119
> Fix invalid shutdown state

- CHANGELOG.md
- lib/karafka/connection/listener.rb
- spec/integrations/pro/shutdown/long_running_jobs/revocation_awareness_on_shutdown_spec.rb
close https://github.com/karafka/karafka/issues/1150
> Trigger revocation during running shutdown on LRJ

- CHANGELOG.md
- lib/karafka/connection/client.rb
- lib/karafka/connection/listener.rb
- lib/karafka/embedded.rb
- lib/karafka/instrumentation/logger_listener.rb
- lib/karafka/instrumentation/notifications.rb
- lib/karafka/instrumentation/vendors/datadog/logger_listener.rb
- lib/karafka/process.rb
- lib/karafka/server.rb
- lib/karafka/status.rb
- spec/integrations/embedding/quiet_spec.rb
- spec/integrations/signals/on_sigtstp_spec.rb
- spec/lib/karafka/instrumentation/logger_listener_spec.rb
- spec/lib/karafka/process_spec.rb
close https://github.com/karafka/karafka/issues/1151
This PR adds the `TSTP` signal support, so we silence karafka when it needs to keep running without accepting new jobs.
> #1151 Quiet

- karafka.gemspec
part of https://github.com/karafka/karafka/issues/1101
> meta links

- spec/integrations/pro/rebalancing/long_running_jobs/revoke_mark_as_consumed_not_enough_threads_spec.rb
Break the loop so when closing consumer, it does not hang.
> improve unstable spec

- karafka.gemspec
A nicer description aligned with the website and docs
> update gem description

- spec/integrations/pro/rebalancing/long_running_jobs/rebalance_continuity_spec.rb
close https://github.com/karafka/karafka/issues/1181
> optimize spec

- CHANGELOG.md
- config/errors.yml
- lib/karafka/app.rb
- lib/karafka/cli/server.rb
- lib/karafka/contracts/server_cli_options.rb
- lib/karafka/processing/jobs_queue.rb
- lib/karafka/routing/consumer_group.rb
- lib/karafka/routing/subscription_group.rb
- lib/karafka/routing/topic.rb
- lib/karafka/routing/topics.rb
- lib/karafka/server.rb
- lib/karafka/setup/config.rb
- spec/integrations/consumption/two_consumer_groups_one_active_spec.rb
- spec/integrations/routing/limited_scope/with_non_existing_consumer_groups_spec.rb
- spec/integrations/routing/limited_scope/with_non_existing_subscription_groups_spec.rb
- spec/integrations/routing/limited_scope/with_non_existing_topics_spec.rb
- spec/integrations/routing/limited_scope/with_nothing_to_run_spec.rb
- spec/integrations/routing/routing_and_cli_validation_spec.rb
- spec/integrations/routing/stable_with_limited_consumer_groups_spec.rb
- spec/integrations/setup/attributes_distribution_spec.rb
- spec/lib/karafka/app_spec.rb
- spec/lib/karafka/cli/server_spec.rb
- spec/lib/karafka/contracts/server_cli_options_spec.rb
- spec/lib/karafka/routing/consumer_group_spec.rb
- spec/lib/karafka/routing/subscription_group_spec.rb
- spec/lib/karafka/routing/topic_spec.rb
- spec/lib/karafka/routing/topics_spec.rb
- spec/lib/karafka/server_spec.rb
- spec/lib/karafka/setup/dsl_spec.rb
- spec/spec_helper.rb
close https://github.com/karafka/karafka/issues/1192
> Allow running particular named subscription groups and topics similar to consumer groups

- spec/integrations/consumption/strategies/default/processing_with_delay_spec.rb
- spec/integrations/pro/consumption/strategies/lrj/with_long_manual_pause_spec.rb
Just a scenario illustrating and testing the delayed processing
> delayed processing scenario

- CHANGELOG.md
- lib/karafka/admin.rb
- spec/lib/karafka/admin_spec.rb
- spec/lib/karafka/server_spec.rb
- spec/spec_helper.rb
Provides admin read topic api for future usage with web/
> Admin read_topic API

- CHANGELOG.md
- lib/karafka/app.rb
- lib/karafka/status.rb
- spec/lib/karafka/status_spec.rb
This PR includes small status improvements and explicit `#to_s` for easier reporting.
> status improvements

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/setup/config.rb
- spec/lib/karafka/setup/config_spec.rb
* emit stats every 5 seconds by default @Azdaroth 
* add specs
Co-authored-by: Maciej Mensfeld <maciej@mensfeld.pl>
I retargeted to fix specs. Did not yet figure out how to run pro from forks.
> emit stats every 5 seconds by default (#1218)

- CHANGELOG.md
- lib/karafka/messages/message.rb
- lib/karafka/messages/parser.rb
- lib/karafka/setup/config.rb
- spec/lib/karafka/messages/parser_spec.rb
This PR introduces a messages parser. It wraps the deserialization in a higher configurable abstraction.
> Introduce configurable messages parser

- CHANGELOG.md
- lib/karafka/instrumentation/proctitle_listener.rb
- spec/lib/karafka/instrumentation/proctitle_listener_spec.rb
This PR fixes a case where proctitle would not switch the title on new states.
> fix proctitle reporting

- spec/integrations/embedding/puma_poro/Gemfile
Fixes https://github.com/karafka/karafka/security/dependabot/7
> puma_poro integrations spec dependency bump

- .github/workflows/ci.yml
- bin/verify_karafka
- bin/verify_license_integrity
- spec/integrations/pro/licensing/post_checksum_verification_poro/Gemfile
- spec/integrations/pro/licensing/post_checksum_verification_poro/verify_spec.rb
ref https://karafka.io/docs/Pro-Getting-Started/#license-gem-integrity-verification
> Verify license checksum via recommended script

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/pro/processing/strategies/dlq.rb
- lib/karafka/version.rb
- spec/integrations/pro/consumption/strategies/dlq/details_dispatch_transfer_with_enhancement_spec.rb
- spec/integrations/pro/consumption/strategies/dlq/manual_dispatch_to_dlq_spec.rb
close https://github.com/karafka/karafka/issues/1266
close https://github.com/karafka/karafka/issues/1264
> Allow for DLQ message content enhancements

- CHANGELOG.md
- lib/karafka/setup/config.rb
- spec/integrations/instrumentation/statistics_callback_on_client_change_spec.rb
- spec/integrations/instrumentation/statistics_callback_subscription_spec.rb
- spec/integrations/setup/config_with_inherited_client_id_spec.rb
- spec/integrations/setup/config_with_overwritten_client_id_spec.rb
- spec/lib/karafka/setup/config_spec.rb
close https://github.com/karafka/karafka/issues/1269
> Use client_id for kafka.client.id

- spec/integrations/pro/consumption/strategies/vp/with_pause_on_collapsed_spec.rb
Improvement to the spec stability
> Spec stability

- CHANGELOG.md
- spec/integrations/pro/consumption/strategies/dlq/multi_topic_one_target_multi_partitions_flow_spec.rb
- spec/integrations/pro/consumption/strategies/dlq_vp/collapse_and_continuity_spec.rb
- spec/integrations/pro/consumption/strategies/dlq_vp/skip_after_collapse_many_spec.rb
few small remarks that slipped through coditsu at some point
> Coditsu remarks

- README.md
Reference from readme the become-pro directly instead of the root of the page.
> reference pro

- CHANGELOG.md
- Gemfile.lock
- karafka.gemspec
- lib/karafka/version.rb
- spec/support/rspec_locator.rb
Small update to reference the core locator as a base for the custom one in Karafka.
> Use common rspec locator base

- CHANGELOG.md
- Gemfile.lock
- karafka.gemspec
- lib/karafka/admin.rb
- spec/integrations_helper.rb
- spec/lib/karafka/admin_spec.rb
close https://github.com/karafka/karafka/issues/1254
> Ability to resize topics + wait fix

- CHANGELOG.md
- lib/karafka.rb
- lib/karafka/connection/client.rb
- lib/karafka/instrumentation/callbacks/error.rb
- lib/karafka/instrumentation/callbacks/statistics.rb
- lib/karafka/instrumentation/notifications.rb
- lib/karafka/setup/config.rb
- spec/integrations/setup/re_initialization_of_cached_resources_spec.rb
- spec/lib/karafka/instrumentation/callbacks/error_spec.rb
- spec/lib/karafka/instrumentation/callbacks/statistics_spec.rb
close https://github.com/karafka/karafka/issues/1314
> Fix Karafka monitor is prematurely cached (#1314)

- CHANGELOG.md
- lib/karafka/admin.rb
close https://github.com/karafka/karafka/issues/1317
> Increase fetch.message.max.bytes for admin

- spec/integrations/pausing/pause_super_short_spec.rb
close https://github.com/karafka/karafka/issues/1308
> #1308 extra spec for short pause

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/cli/topics.rb
- lib/karafka/version.rb
- spec/integrations/cli/topics/ignore_non_primary_cluster_spec.rb
close https://github.com/karafka/karafka/issues/1365
> Do not mix primary and secondary cluster in declarative management

- CHANGELOG.md
- lib/karafka/admin.rb
close https://github.com/karafka/karafka/issues/1369
> disable auto-commit on admin actions

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/active_job/consumer.rb
- lib/karafka/instrumentation/notifications.rb
- lib/karafka/pro/active_job/consumer.rb
- lib/karafka/version.rb
- spec/integrations/instrumentation/aj_per_job_consumption_events_spec.rb
- spec/integrations/pro/instrumentation/aj_per_job_consumption_events_spec.rb
close https://github.com/karafka/karafka/issues/1372
> Better AJ instrumentation (#1372)

- CHANGELOG.md
- lib/karafka/admin.rb
- spec/lib/karafka/admin_spec.rb
This PR
- improves the `read_topic` operations by optimizing how we compute ranges to fetch
- introduces a new method for reading watermark offsets
- allows for `read_topic` consumer settings customization. Needed for the web-ui improvements
> Improve admin operations and introduce watermark offset readings

- lib/karafka/admin.rb
This PR adds a small refactor to simplify the topic reading code and save one potential poll when all data is already there.
> optimize read topic flow

- spec/integrations/pro/consumption/strategies/aj/dlq_ftr_lrj_mom_vp/with_non_recoverable_job_error_spec.rb
- spec/integrations/pro/consumption/strategies/vp/collective_state_awareness_break_spec.rb
This spec ensures, that the collective state awareness for VPs work as expected.
> Collective state break

- lib/karafka/pro/processing/coordinator.rb
- lib/karafka/pro/processing/filters_applier.rb
- lib/karafka/pro/routing/features/delaying/topic.rb
- lib/karafka/pro/routing/features/expiring/topic.rb
- lib/karafka/pro/routing/features/throttling/topic.rb
- spec/integrations/pro/consumption/strategies/ftr/chained_filters_with_post_throttle_spec.rb
- spec/integrations/pro/consumption/strategies/ftr/chained_filters_with_pre_throttle_spec.rb
- spec/integrations/pro/consumption/strategies/ftr/custom_per_topic_spec.rb
- spec/integrations/pro/consumption/strategies/ftr/custom_to_delay_spec.rb
- spec/integrations/pro/consumption/strategies/ftr/endless_skip_no_seek_spec.rb
- spec/integrations/pro/consumption/strategies/ftr/static_throttler_spec.rb
- spec/integrations/pro/consumption/strategies/vp/collective_state_awareness_break_spec.rb
- spec/lib/karafka/pro/processing/filters_applier_spec.rb
This PR expands the filtering API to inject topic and partition for location-aware factories support.
> More specs + filtering API extension

- Gemfile
- Gemfile.lock
- spec/integrations/pro/web/from_earliest_spec.rb
- spec/integrations/pro/web/with_errors_spec.rb
- spec/integrations/pro/web/with_idle_and_fast_shutdown_spec.rb
- spec/integrations/web/from_earliest_spec.rb
- spec/integrations/web/with_errors_spec.rb
- spec/integrations_helper.rb
This PR adds basic integration specs for ensuring karafka-web recent release compatibility
> karafka-web integrations

- CHANGELOG.md
- lib/karafka/pro/iterator.rb
- spec/integrations/pro/iterator/negative_multiple_topics_lookups_spec.rb
- spec/integrations/pro/iterator/negative_topic_multiple_partitions_spec.rb
- spec/integrations/pro/iterator/with_negative_lookup_for_last_messages_spec.rb
- spec/integrations/pro/iterator/with_pause_current_partition_usage_spec.rb
This PR adds the ability to use iterator in the reverse mode, that is "give me at most X last messages" by using negative offsets definitions.
close https://github.com/karafka/karafka/issues/1427
> Reverse lookup in the iterator

- spec/integrations/consumption/with_producer_disconnect_error_spec.rb
add a spec illustrating reconnect for producer
> integration spec for reconnects

- CHANGELOG.md
- config/locales/errors.yml
- spec/integrations/setup/max_messages_format_as_string_spec.rb
- spec/lib/karafka/contracts/topic_spec.rb
close https://github.com/karafka/karafka/issues/1443
> Make sure max_messages and max_wait_time have references in errors.yml

- config/locales/errors.yml
- spec/lib/karafka/contracts/config_spec.rb
- spec/lib/karafka/contracts/consumer_group_spec.rb
- spec/lib/karafka/contracts/topic_spec.rb
Missing validation errors
close https://github.com/karafka/karafka/issues/1445
> Add missing error messages references

- CHANGELOG.md
- lib/karafka/connection/client.rb
- spec/integrations/consumption/with_sync_mark_sa_consumed_after_revoke_spec.rb
- spec/support/data_collector.rb
close https://github.com/karafka/karafka/issues/1461
> Make sure to handle unknown_member_id when dealing with revoked partition on marking

- spec/integrations/pro/consumption/strategies/dlq/lrj_mom/non_recoverable_moving_forward_marking_spec.rb
- spec/integrations/rebalancing/message_order_with_sync_commit_spec.rb
- spec/integrations/rebalancing/message_order_without_sync_commit_spec.rb
ref https://github.com/karafka/karafka/pull/1460
> A test cases for message ordering during rebalances

- spec/integrations/pro/consumption/strategies/dlq/lrj_mom/non_recoverable_moving_forward_marking_spec.rb
close https://github.com/karafka/karafka/issues/1459
> Stabilize spec

- spec/integrations/pro/consumption/strategies/ftr/persistent_post_rebalance_pausing_spec.rb
- spec/integrations/pro/consumption/strategies/ftr/persistent_transactional_offset_spec.rb
A simple spec illustrating transactional offset management.
> Transactional offsets management integration spec

- spec/support/data_collector.rb
close https://github.com/karafka/karafka/issues/1490
> Increase stability of specs by increasing random topics names

- CHANGELOG.md
- Gemfile.lock
- karafka.gemspec
- spec/integrations/pro/rebalancing/on_partition_data_revoked_spec.rb
close https://github.com/karafka/karafka/issues/1496
> Fix unstable spec

- spec/integrations/lags/processing_slow_spec.rb
Improves spec glitching on the CI
> Slow ci spec fix

- spec/integrations/pro/rails/rails6_pristine/Gemfile
- spec/integrations/pro/rails/rails6_pristine/railtie_setup_spec.rb
- spec/integrations/pro/rails/rails7_pristine/just_a_dependency/Gemfile
- spec/integrations/pro/rails/rails7_pristine/just_a_dependency/railtie_setup_spec.rb
- spec/integrations/pro/rails/rails7_pristine/with-active_job_and_current_attributes/Gemfile
- spec/integrations/rails/rails6_pristine/just-a-dependency/Gemfile
- spec/integrations/rails/rails6_pristine/with-active_job/Gemfile
- spec/integrations/rails/rails6_pristine/with-active_job/railtie_setup_spec.rb
- spec/integrations/rails/rails6_pristine/without-a-boot-file/Gemfile
- spec/integrations/rails/rails6_pristine/without-active_job/Gemfile
- spec/integrations/rails/rails6_pristine/without-active_job/railtie_setup_spec.rb
- spec/integrations/rails/rails6_pristine/without-active_job_rspec/Gemfile
- spec/integrations/rails/rails7_pristine/just-a-dependency/Gemfile
- spec/integrations/rails/rails7_pristine/with-active_job/Gemfile
- spec/integrations/rails/rails7_pristine/with-active_job/railtie_setup_spec.rb
- spec/integrations/rails/rails7_pristine/with-active_job_and_current_attributes/Gemfile
- spec/integrations/rails/rails7_pristine/without-active_job/Gemfile
- spec/integrations/rails/rails7_pristine/without-active_job/railtie_setup_spec.rb
- spec/integrations/rails/rails7_pristine/without-active_job_rspec/Gemfile
This just bumps rails bypassing renovates problems.
> bump rails

- CHANGELOG.md
- lib/karafka/instrumentation/logger_listener.rb
- lib/karafka/pro/iterator.rb
- spec/integrations/pro/iterator/custom_max_wait_time_spec.rb
- spec/lib/karafka/instrumentation/logger_listener_spec.rb
Adds missing instrumentation event hook for LoggerListener and adds ability to customize max_wait_time on the iterator.
> Fix missing logger event and add ma_wait_time for Iterator

- CHANGELOG.md
- lib/karafka/base_consumer.rb
- lib/karafka/messages/messages.rb
- spec/integrations/consumption/strategies/default/from_earliest_spec.rb
- spec/integrations/instrumentation/post_mutation_messages_count_reporting_spec.rb
- spec/integrations/pro/consumption/strategies/ftr/used_status_for_fully_delayed_consumer_spec.rb
- spec/lib/karafka/base_consumer_spec.rb
- spec/lib/karafka/messages/messages_spec.rb
close https://github.com/karafka/karafka/issues/1526
> #used? and small fixes

- spec/integrations/pro/consumption/strategies/lrj/ftr/constant_reporting_lag_spec.rb
- spec/integrations/rebalancing/cooperative_sticky_unassigned_shutdown_spec.rb
ref https://github.com/karafka/karafka/issues/1529
> unassigned coop close

- CHANGELOG.md
- Gemfile.lock
- karafka.gemspec
- lib/karafka/templates/karafka.rb.erb
- lib/karafka/version.rb
close https://github.com/karafka/karafka/issues/1535
> lower noisy default waterdrop setup

- CHANGELOG.md
- config/locales/pro_errors.yml
- lib/karafka/connection/listener.rb
- lib/karafka/connection/pauses_manager.rb
- lib/karafka/pro/routing/features/pausing.rb
- lib/karafka/pro/routing/features/pausing/contract.rb
- lib/karafka/pro/routing/features/pausing/topic.rb
- lib/karafka/processing/coordinators_buffer.rb
- lib/karafka/routing/topic.rb
- spec/integrations/pro/pausing/with_per_topic_pause_setup_spec.rb
- spec/integrations/pro/routing/pausing/with_custom_invalid_pausing_spec.rb
- spec/integrations/pro/routing/pausing/with_custom_valid_spec.rb
- spec/lib/karafka/connection/pauses_manager_spec.rb
- spec/lib/karafka/pro/routing/features/pausing/contract_spec.rb
- spec/lib/karafka/pro/routing/features/pausing/topic_spec.rb
- spec/lib/karafka/pro/routing/features/pausing_spec.rb
- spec/lib/karafka/processing/coordinators_buffer_spec.rb
- spec/lib/karafka/routing/topic_spec.rb
close https://github.com/karafka/karafka/issues/1538
> Per topic backoff policies

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/instrumentation/notifications.rb
- lib/karafka/patches/rdkafka/bindings.rb
- lib/karafka/version.rb
- spec/integrations/rebalancing/cooperative_sticky_without_assignment_spec.rb
this PR adds basic instrumentation of rebalances. Can be useful to track them in some metrics, etc
> instrument rebalance callback

- CHANGELOG.md
- lib/karafka/admin.rb
- lib/karafka/base_consumer.rb
- lib/karafka/connection/client.rb
- lib/karafka/connection/proxy.rb
- lib/karafka/patches/rdkafka/bindings.rb
- lib/karafka/pro/iterator/tpl_builder.rb
- spec/lib/karafka/connection/proxy_spec.rb
close https://github.com/karafka/karafka/issues/1553
close https://github.com/karafka/karafka/issues/1555
> increase watermark requests timeouts and do not unsubscribe long-lived

- spec/lib/karafka/connection/proxy_spec.rb
classical @thijsc mistake :rofl:
> always close consumer instance in specs

- Gemfile.lock
- spec/integrations/pro/rails/rails7_pristine/just_a_dependency/Gemfile
- spec/integrations/pro/rails/rails7_pristine/just_a_dependency/railtie_setup_spec.rb
- spec/integrations/pro/rails/rails7_pristine/with-active_job_and_current_attributes/Gemfile
- spec/integrations/rails/rails7_pristine/just-a-dependency/Gemfile
- spec/integrations/rails/rails7_pristine/with-active_job/Gemfile
- spec/integrations/rails/rails7_pristine/with-active_job/railtie_setup_spec.rb
- spec/integrations/rails/rails7_pristine/with-active_job_and_current_attributes/Gemfile
- spec/integrations/rails/rails7_pristine/without-active_job/Gemfile
- spec/integrations/rails/rails7_pristine/without-active_job/railtie_setup_spec.rb
- spec/integrations/rails/rails7_pristine/without-active_job_rspec/Gemfile
Superseeds: https://github.com/karafka/karafka/pull/1543/files
> Bump Rails + friends

- CHANGELOG.md
- lib/karafka/app.rb
- lib/karafka/connection/listener.rb
- lib/karafka/status.rb
- spec/integrations/shutdown/extremely_fast_stop_spec.rb
- spec/lib/karafka/app_spec.rb
- spec/lib/karafka/connection/listener_spec.rb
- spec/lib/karafka/status_spec.rb
close https://github.com/karafka/karafka/issues/1562
> introduce meta status #done? and make sure all done states work with it

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/connection/proxy.rb
- lib/karafka/version.rb
This PR ensures, that timeouts are also retried.
> expand offset queries retries

- Gemfile.lock
Just a bump to see if karafka will operate as expected with new karafka-rdkafka. I do not want to lock it because there are no breaking changes but want to be sure it operates as expected, hence the bump.
> karafka-rdkafka bump

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/pro/processing/strategies/dlq/default.rb
- lib/karafka/pro/processing/strategies/dlq/ftr.rb
- lib/karafka/version.rb
- spec/integrations/consumption/strategies/default/from_earliest_spec.rb
- spec/integrations/consumption/strategies/dlq/without_any_errors_spec.rb
- spec/integrations/pro/consumption/from_earliest_spec.rb
- spec/integrations/pro/consumption/strategies/dlq/ftr_lrj_vp/without_intermediate_marking_spec.rb
- spec/integrations/pro/consumption/strategies/dlq/ftr_vp/marking_without_intermediate_marking_spec.rb
- spec/integrations/pro/consumption/strategies/dlq/lrj_vp/without_intermediate_marking_spec.rb
- spec/integrations/pro/consumption/strategies/dlq/vp/marking_without_intermediate_marking_spec.rb
- spec/integrations/pro/consumption/strategies/ftr/custom_per_topic_spec.rb
- spec/integrations/pro/consumption/strategies/vp/without_intermediate_marking_spec.rb
- spec/integrations_helper.rb
close https://github.com/karafka/karafka/issues/1579
> Fix DLQ + VP without intermediate marking may mark earlier message

- CHANGELOG.md
- config/locales/errors.yml
- lib/karafka/admin.rb
- lib/karafka/contracts/config.rb
- lib/karafka/setup/config.rb
- spec/integrations/setup/admin_invalid_configuration_spec.rb
- spec/lib/karafka/contracts/config_spec.rb
close https://github.com/karafka/karafka/issues/1589
close https://github.com/karafka/karafka/issues/1592
> Admin config

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/admin.rb
- lib/karafka/version.rb
- spec/lib/karafka/admin_spec.rb
close https://github.com/karafka/karafka/issues/1608
> Fix read_topic admin time based lookups

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/messages/builders/batch_metadata.rb
- lib/karafka/version.rb
- spec/integrations/consumption/with_future_messages_due_to_drift_spec.rb
- spec/integrations/pro/instrumentation/first_idle_messages_metadata_spec.rb
- spec/integrations/web/from_earliest_drifted_spec.rb
- spec/lib/karafka/messages/builders/batch_metadata_spec.rb
close https://github.com/karafka/karafka/issues/1611
> Compensate for cluster time drift in reporting

- bin/integrations
- spec/integrations/consumption/with_future_messages_due_to_drift_spec.rb
- spec/integrations/web/from_earliest_drifted_spec.rb
- spec/lib/karafka/processing/jobs_queue_spec.rb
- spec/lib/karafka/processing/worker_spec.rb
This PR extends the length of time lag to compensate for a slow CI
> Stabilize few specs

- Gemfile.lock
- spec/integrations_helper.rb
> Update deps for specs

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/railtie.rb
- lib/karafka/version.rb
close https://github.com/karafka/karafka/issues/1620
> Migrate to Rails 7.1+ connection cleaning API

- bin/integrations
- docker-compose.yml
- spec/integrations/consumption/strategies/default/of_many_partitions_with_many_workers_spec.rb
- spec/integrations/lags/processing_not_enough_threads_spec.rb
- spec/integrations/pro/consumption/strategies/aj/dlq_ftr_mom_vp/regular_processing_without_errors_spec.rb
- spec/integrations/pro/consumption/strategies/ftr/static_throttler_spec.rb
- spec/integrations/pro/consumption/strategies/vp/cancelled_vps_due_to_bad_partitioning_spec.rb
- spec/integrations/pro/consumption/strategies/vp/with_error_in_the_middle_marking_spec.rb
- spec/integrations_helper.rb
close https://github.com/karafka/karafka/issues/1603
on top improves some specs
> Add an integration spec illustrating how virtual partitioner that distributes all to one partition cancels VPs

- CHANGELOG.md
- spec/integrations/instrumentation/vendors/datadog/with_original_client_pristine/Gemfile
- spec/integrations/instrumentation/vendors/datadog/with_original_client_pristine/with_proper_ddtrace_spec.rb
- spec/integrations/pro/consumption/strategies/aj/dlq_ftr_mom_vp/regular_processing_without_errors_spec.rb
This PR adds integrations against native DD client to ensure things like https://github.com/karafka/karafka/pull/1624 won't happen again.
> Add integrations for dd client

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/routing/subscription_group.rb
- lib/karafka/version.rb
- spec/lib/karafka/routing/subscription_group_spec.rb
close https://github.com/karafka/karafka/issues/1645
> Make subscription groups ids globally unique

- CHANGELOG.md
- lib/karafka/railtie.rb
- spec/integrations/installation/with_rails71_pristine/Gemfile
- spec/integrations/installation/with_rails71_pristine/install_spec.rb
- spec/integrations/installation/with_rails7_pristine/Gemfile
- spec/integrations/installation/with_rails7_pristine/install_spec.rb
- spec/integrations/pro/rails/rails71_pristine/just_a_dependency/Gemfile
- spec/integrations/pro/rails/rails71_pristine/just_a_dependency/railtie_setup_spec.rb
- spec/integrations/pro/rails/rails71_pristine/with-active_job_and_current_attributes/Gemfile
- spec/integrations/pro/rails/rails71_pristine/with-active_job_and_current_attributes/active_job_run_spec.rb
This PR adds specs to ensure Karafka operates with Rails 7.1.
close https://github.com/karafka/karafka/issues/1655
ref https://github.com/rails/rails/issues/49494
> Support Rails 7.1

- spec/integrations/rails/rails71_pristine/just-a-dependency/Gemfile
- spec/integrations/rails/rails71_pristine/just-a-dependency/rails_setup_spec.rb
- spec/integrations/rails/rails71_pristine/just-a-dependency/with_potential_name_collision_spec.rb
- spec/integrations/rails/rails71_pristine/with-active_job/Gemfile
- spec/integrations/rails/rails71_pristine/with-active_job/extended_routing_absence_spec.rb
- spec/integrations/rails/rails71_pristine/with-active_job/railtie_setup_spec.rb
- spec/integrations/rails/rails71_pristine/with-active_job/without_double_logging_spec.rb
- spec/integrations/rails/rails71_pristine/with-active_job_and_current_attributes/Gemfile
- spec/integrations/rails/rails71_pristine/with-active_job_and_current_attributes/active_job_run_spec.rb
- spec/integrations/rails/rails71_pristine/with-active_job_and_current_attributes/resource_accesibility_and_isolation_spec.rb
- spec/integrations/rails/rails71_pristine/with-active_job_and_perform_all_later/Gemfile
- spec/integrations/rails/rails71_pristine/with-active_job_and_perform_all_later/perform_all_later_run_spec.rb
- spec/integrations/rails/rails71_pristine/without-active_job/Gemfile
- spec/integrations/rails/rails71_pristine/without-active_job/extended_routing_absence_spec.rb
- spec/integrations/rails/rails71_pristine/without-active_job/railtie_setup_spec.rb
- spec/integrations/rails/rails71_pristine/without-active_job_rspec/Gemfile
- spec/integrations/rails/rails71_pristine/without-active_job_rspec/console_with_rails_spec.rb
- spec/integrations/rails/rails71_pristine/without-active_job_rspec/rspec_rails_setup_spec.rb
close https://github.com/karafka/karafka/issues/1334
> introduce aj perform_all_later specs and other rails7.1 specs

- karafka.gemspec
Link to the correct changelog location
> Update changelog location

- lib/karafka/cli/base.rb
- lib/karafka/cli/console.rb
- lib/karafka/cli/server.rb
close https://github.com/karafka/karafka/issues/1677
It's interesting as the aliases used to work for sure. Nonetheless not worth deeper investigation.
ref https://github.com/rails/thor/issues/808
> Support thor 1.3.0

- CHANGELOG.md
- lib/karafka/admin.rb
- spec/lib/karafka/admin_spec.rb
This PR adds ability to request N messages and to go with a negative offset in reference to requested number of messages.
> support negative offsets

- lib/karafka/pro/processing/strategies/lrj/default.rb
- renovate.json
- spec/integrations/pro/shutdown/long_running_jobs/revocation_awareness_on_shutdown_spec.rb
close https://github.com/karafka/karafka/issues/1707
> Fix unstable spec and remove outdated comment

- spec/integrations/pro/consumption/strategies/vp/with_cycling_distribution_spec.rb
close https://github.com/karafka/karafka/issues/1730
> cycle vps example

- CHANGELOG.md
- lib/karafka/connection/listener.rb
- lib/karafka/pro/processing/schedulers/base.rb
- lib/karafka/pro/processing/schedulers/default.rb
- lib/karafka/processing/schedulers/default.rb
- spec/integrations/pro/consumption/scheduling/full_ftr_with_idle_in_scheduler_spec.rb
- spec/lib/karafka/pro/processing/schedulers/base_spec.rb
- spec/lib/karafka/pro/processing/schedulers/default_spec.rb
- spec/lib/karafka/processing/schedulers/default_spec.rb
close https://github.com/karafka/karafka/issues/1780
> Fix for Scheduler consumption may receive idle jobs when full FTR kicks

- spec/integrations/pro/consumption/periodics/on_a_non_existing_topic_spec.rb
- spec/integrations/pro/consumption/periodics/pause_from_tick_spec.rb
- spec/integrations/pro/consumption/periodics/pause_resume_flow_from_tick_spec.rb
- spec/integrations/pro/consumption/periodics/resume_from_tick_spec.rb
One more spec to cover this case.
> spec for periodics on a non-existing topic

- spec/integrations/pro/consumption/periodics/marking_from_ticking_spec.rb
Another one of those that behave differently under load.
> Marking on ticking spec stability

- CHANGELOG.md
- config/locales/errors.yml
- lib/karafka/pro/processing/strategies/dlq/default.rb
- lib/karafka/processing/strategies/dlq.rb
- lib/karafka/routing/features/dead_letter_queue/config.rb
- lib/karafka/routing/features/dead_letter_queue/contracts/topic.rb
- lib/karafka/routing/features/dead_letter_queue/topic.rb
- spec/integrations/consumption/strategies/dlq/independent_constant_recovering_spec.rb
- spec/integrations/consumption/strategies/dlq/with_rolling_error_spec.rb
- spec/integrations/pro/consumption/strategies/dlq/default/independent_constant_recovering_spec.rb
- spec/integrations/pro/consumption/strategies/dlq/default/with_rolling_error_spec.rb
- spec/lib/karafka/routing/features/dead_letter_queue/config_spec.rb
- spec/lib/karafka/routing/features/dead_letter_queue/contracts/topic_spec.rb
close https://github.com/karafka/karafka/issues/1789
> independent messages flow on dlq

- spec/integrations/consumption/strategies/mom/with_manual_offset_and_error_spec.rb
under heavy CPU load this spec would start shutdown too early, this fixes it
> improve mom spec stability

- lib/karafka/admin.rb
Just update to use official API I released.
> use direct cluster info rdkafka reference

- .github/workflows/ci.yml
Not everything there was needed and we used less then optimal bundler version for 2.7
> Bundler 2.7 script improvements

- Gemfile.lock
- lib/karafka/admin/acl.rb
This PR enables most recent karafka-rdkafka and unblocks the missing setting in the ACL.
> Use most recent karafka-rdkafka

- lib/karafka/pro/routing/features/patterns/contracts/consumer_group.rb
- spec/integrations/pro/consumption/multiplexing/with_patterns_spec.rb
- spec/integrations/pro/routing/patterns/named_with_same_in_one_consumer_group_spec.rb
This PR adds extra specs to ensure multiplexing works with pattern matching and fixes a case where multiplexing would not work with pattern matching.
> more specs and fix for patterns

- lib/karafka/templates/karafka.rb.erb
close https://github.com/karafka/karafka/issues/1814
> Enhance template with web ui info

- lib/karafka/connection/listener.rb
- spec/integrations/pro/consumption/periodic_jobs/partially_periodic_spec.rb
I forgot a check :facepalm: 
close https://github.com/karafka/karafka/issues/1835
> Fix all SG running periodic instead of per topic

- CHANGELOG.md
- spec/integrations/routing/routing_and_cli_validations_for_many_inclusions_spec.rb
ref https://github.com/karafka/karafka/issues/1843
> Add specs for multi-element CLI server startup

- CHANGELOG.md
- lib/karafka/instrumentation/vendors/appsignal/metrics_listener.rb
- lib/karafka/instrumentation/vendors/datadog/logger_listener.rb
- lib/karafka/instrumentation/vendors/datadog/metrics_listener.rb
- lib/karafka/instrumentation/vendors/kubernetes/liveness_listener.rb
- spec/integrations/pro/instrumentation/vendors/appsignal/ticking_tracking_spec.rb
- spec/integrations/pro/instrumentation/vendors/datadog/tick_error_logger_spec.rb
- spec/integrations/pro/instrumentation/vendors/kubernetes/liveness_from_ticking_spec.rb
close https://github.com/karafka/karafka/issues/1841
> Support ticking in the instrumentation

- CHANGELOG.md
- config/locales/errors.yml
- lib/karafka/base_consumer.rb
- lib/karafka/instrumentation/logger_listener.rb
- lib/karafka/pro/processing/strategies/dlq/default.rb
- lib/karafka/pro/processing/strategies/dlq/ftr.rb
- lib/karafka/pro/processing/strategies/dlq/ftr_lrj.rb
- lib/karafka/pro/processing/strategies/dlq/lrj.rb
- lib/karafka/routing/features/dead_letter_queue/config.rb
- lib/karafka/routing/features/dead_letter_queue/contracts/topic.rb
- lib/karafka/routing/features/dead_letter_queue/topic.rb
- spec/integrations/pro/consumption/transactions/dlq/with_crash_during_transational_dispatch_spec.rb
- spec/integrations/pro/consumption/transactions/dlq/with_transactional_dispatch_spec.rb
- spec/lib/karafka/instrumentation/logger_listener_spec.rb
- spec/lib/karafka/routing/features/dead_letter_queue/config_spec.rb
- spec/lib/karafka/routing/features/dead_letter_queue/contracts/topic_spec.rb
close https://github.com/karafka/karafka/issues/1858
> Use transactions for DLQ dispatches if applicable

- spec/lib/karafka/connection/client_spec.rb
close https://github.com/karafka/karafka/issues/1862
> fix consumer leak

- lib/karafka/admin.rb
close https://github.com/karafka/karafka/issues/1863
> retry on not coordinator

- lib/karafka/templates/karafka.rb.erb
- spec/integrations/web/end_to_end_install_flow_pristine/Gemfile
- spec/integrations/web/end_to_end_install_flow_pristine/install_with_rails_spec.rb
This PR adds (failing for now, before web-ui release) specs that ensure, that 0.8.1 can be installed starting from scratch and that new env gets things activated correctly.
ref https://github.com/karafka/karafka-web/issues/259
> specs for upcoming web fix

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/pro/connection/manager.rb
- lib/karafka/version.rb
- spec/integrations/pro/shutdown/on_reached_quiet_spec.rb
- spec/integrations/shutdown/on_reached_quiet_spec.rb
It is not a big production issue but still worth fixing. Won't craft immediate release because of low impact.
close https://github.com/karafka/karafka/issues/1886
> Ensure correct silence procedure

- Gemfile.lock
- spec/integrations/instrumentation/producer_logger_on_forks_spec.rb
This PR makes sure that this https://github.com/karafka/rdkafka-ruby/issues/407 does not happen again.
> test forking of logger in rdkafka

- CHANGELOG.md
- lib/karafka/pro/processing/strategies/vp/default.rb
- spec/integrations/pro/consumption/strategies/vp/errors_tracking/collapsed_consecutive_errors_accumulation_spec.rb
- spec/integrations/pro/consumption/strategies/vp/groups_aggregation_halt_on_recovery_spec.rb
close https://github.com/karafka/karafka/issues/1900
> Fix endless groups accumulation

- CHANGELOG.md
- config/locales/pro_errors.yml
- lib/karafka/pro/active_job/job_options_contract.rb
- lib/karafka/pro/processing/strategies/aj/dlq_ftr_lrj_mom.rb
- lib/karafka/pro/processing/strategies/aj/dlq_ftr_lrj_mom_vp.rb
- lib/karafka/pro/processing/strategies/aj/dlq_ftr_mom.rb
- lib/karafka/pro/processing/strategies/aj/dlq_ftr_mom_vp.rb
- lib/karafka/pro/processing/strategies/aj/dlq_lrj_mom.rb
- lib/karafka/pro/processing/strategies/aj/dlq_lrj_mom_vp.rb
- lib/karafka/pro/processing/strategies/aj/dlq_mom.rb
- lib/karafka/pro/processing/strategies/aj/dlq_mom_vp.rb
- lib/karafka/pro/processing/strategies/dlq/default.rb
- lib/karafka/pro/processing/strategies/dlq/ftr.rb
- lib/karafka/pro/processing/strategies/dlq/ftr_lrj.rb
- lib/karafka/pro/processing/strategies/dlq/ftr_lrj_mom.rb
- lib/karafka/pro/processing/strategies/dlq/ftr_mom.rb
- lib/karafka/pro/processing/strategies/dlq/lrj.rb
- lib/karafka/pro/processing/strategies/dlq/lrj_mom.rb
- lib/karafka/pro/processing/strategies/dlq/mom.rb
- lib/karafka/pro/routing/features/dead_letter_queue/contracts/topic.rb
- lib/karafka/pro/routing/features/dead_letter_queue/topic.rb
- lib/karafka/routing/features/dead_letter_queue/config.rb
- spec/integrations/pro/consumption/strategies/aj/dlq_mom/with_error_type_based_dispatcher_spec.rb
- spec/integrations/pro/consumption/strategies/dlq/default/with_error_type_based_dispatcher_spec.rb
- spec/lib/karafka/pro/active_job/job_options_contract_spec.rb
- spec/lib/karafka/pro/routing/features/dead_letter_queue/contracts/topic_spec.rb
- spec/lib/karafka/pro/routing/features/dead_letter_queue/topic_spec.rb
close https://github.com/karafka/karafka/issues/1898
close https://github.com/karafka/karafka/issues/1905
> Provide ability to use strategies with errors tracker for DLQ application

- Gemfile.lock
- lib/karafka/constraints.rb
- spec/integrations/web/incompatible_version_pristine/console_with_rails_spec.rb
This PR ensures that we use web-ui version that supports swarm.
> ensure correct web-ui usage

- CHANGELOG.md
- lib/karafka/connection/client.rb
- lib/karafka/routing/subscription_group.rb
- spec/integrations/swarm/static_memberships_without_a_conflict_spec.rb
- spec/lib/karafka/routing/subscription_group_spec.rb
close https://github.com/karafka/karafka/issues/1922
> fix invalid sub-id propagation for static memberships

- CHANGELOG.md
- config/locales/pro_errors.yml
- lib/karafka/pro/routing/features/swarm.rb
- lib/karafka/pro/routing/features/swarm/config.rb
- lib/karafka/pro/routing/features/swarm/contracts/topic.rb
- lib/karafka/pro/routing/features/swarm/topic.rb
- spec/integrations/pro/swarm/limited_per_node_spec.rb
- spec/integrations/pro/swarm/with_unreachable_nodes_spec.rb
- spec/integrations/swarm/static_memberships_without_a_conflict_spec.rb
- spec/lib/karafka/pro/routing/features/swarm/config_spec.rb
- spec/lib/karafka/pro/routing/features/swarm/contracts/topic_spec.rb
- spec/lib/karafka/pro/routing/features/swarm/topic_spec.rb
- spec/lib/karafka/pro/routing/features/swarm_spec.rb
close https://github.com/karafka/karafka/issues/1892
> provide granular nodes control in swarm

- CHANGELOG.md
- lib/karafka/instrumentation/vendors/datadog/metrics_listener.rb
- spec/integrations/instrumentation/vendors/datadog/metrics_flow_with_distributions_spec.rb
- spec/support/vendors/datadog/statsd_dummy_client.rb
Small updates to the metrics updated from https://github.com/karafka/karafka/pull/1924
> Add `distribution` setting to Datadog::MetricsListener (#1924)

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/swarm/supervisor.rb
- lib/karafka/version.rb
close https://github.com/karafka/karafka/issues/1934
> Add a buffer to the supervisor supervision on shutdown to prevent a potential race condition when signal pass lags

- CHANGELOG.md
- config/locales/pro_errors.yml
- lib/karafka/pro/routing/features/direct_assignments/contracts/topic.rb
- lib/karafka/pro/routing/features/direct_assignments/subscription_group.rb
- lib/karafka/pro/routing/features/direct_assignments/topic.rb
- lib/karafka/pro/routing/features/swarm/contracts/topic.rb
- lib/karafka/pro/routing/features/swarm/topic.rb
- spec/integrations/pro/routing/direct_assignments/not_fulfilled_swarm_distribution_spec.rb
- spec/integrations/pro/swarm/direct_granular_assignments_spec.rb
- spec/integrations/pro/swarm/direct_granular_ranges_spec.rb
- spec/lib/karafka/pro/processing/coordinators/errors_tracker_spec.rb
- spec/lib/karafka/pro/routing/features/direct_assignments/contracts/topic_spec.rb
- spec/lib/karafka/pro/routing/features/direct_assignments/topic_spec.rb
- spec/lib/karafka/pro/routing/features/swarm/contracts/routing_spec.rb
- spec/lib/karafka/pro/routing/features/swarm/contracts/topic_spec.rb
close https://github.com/karafka/karafka/issues/1943
> Explicit partitions swarm assignments for direct assignments

- CHANGELOG.md
- lib/karafka/templates/karafka.rb.erb
close https://github.com/karafka/karafka/issues/1915
> Small template update to emphasis error tracking

- lib/karafka/cli/info.rb
- lib/karafka/cli/server.rb
- lib/karafka/cli/topics.rb
- lib/karafka/pro/encryption/cipher.rb
- lib/karafka/processing/coordinators_buffer.rb
- lib/karafka/processing/executor.rb
- lib/karafka/processing/executors_buffer.rb
- lib/karafka/processing/jobs_queue.rb
- lib/karafka/processing/workers_batch.rb
part 1 of https://github.com/karafka/karafka/issues/1888
> Use config injector

- bin/integrations
- lib/karafka/connection/proxy.rb
alongside this PR also cleans the error handling
> log more in integration specs

- spec/integrations/consumption/producer_ping_pong_spec.rb
- spec/integrations/consumption/strategies/default/from_latest_with_non_persistent_error_spec.rb
- spec/integrations/consumption/strategies/default/of_many_topics_on_many_workers_spec.rb
- spec/integrations/consumption/strategies/default/of_many_topics_with_different_settings_spec.rb
- spec/integrations/consumption/with_max_messages_spec.rb
- spec/integrations/instrumentation/statistics_on_lag_with_many_sub_group_spec.rb
- spec/integrations/instrumentation/statistics_on_lag_with_one_sub_group_spec.rb
- spec/integrations/offset_management/from_latest_via_initial_offset_spec.rb
- spec/integrations/offset_management/from_latest_via_kafka_setting_spec.rb
- spec/integrations/pausing/with_manual_pause_and_other_partitions_working_spec.rb
- spec/integrations/pro/consumption/with_pro_scheduler_from_earliest_spec.rb
- spec/integrations/pro/performance_tracking_spec.rb
- spec/integrations/pro/shutdown/on_reached_quiet_spec.rb
- spec/integrations/rebalancing/lost_partition_revoked_execution_time_spec.rb
- spec/integrations/seek/seek_backward_from_consumer_spec.rb
- spec/integrations/seek/seek_in_a_loop_spec.rb
- spec/integrations/seek/seek_to_a_given_offset_from_consumer_spec.rb
- spec/integrations/shutdown/fast_shutdown_on_long_polling_spec.rb
- spec/integrations/shutdown/on_hanging_jobs_and_a_shutdown_spec.rb
- spec/integrations/shutdown/on_hanging_listener_and_shutdown_spec.rb
- spec/integrations/shutdown/on_hanging_on_shutdown_job_and_a_shutdown_spec.rb
- spec/integrations/shutdown/on_reached_quiet_spec.rb
- spec/integrations_helper.rb
Improves integration specs execution time by around 13%.
> Improve CI

- Gemfile
- Gemfile.lock
- spec/integrations/pro/testing/rspec/multiplexing_spec.rb
- spec/integrations/testing/rspec/simple_integration_spec.rb
- spec/integrations_helper.rb
close https://github.com/karafka/karafka/issues/1692
This PR adds karafka-testing integration into the test suite to make sure things work as expected.
For now it adds rspec but we can add minitest in the future as well
> test testing

- CHANGELOG.md
- config/locales/errors.yml
- lib/karafka/admin.rb
- lib/karafka/connection/proxy.rb
- lib/karafka/contracts/config.rb
- lib/karafka/setup/config.rb
- spec/lib/karafka/contracts/config_spec.rb
this PR adds proxy for retries for admin.
I noticed that it fails on integration suite when cluster becomes unstable.
> proxy pass commit

- CHANGELOG.md
- lib/karafka/connection/status.rb
- lib/karafka/instrumentation/notifications.rb
- lib/karafka/status.rb
- spec/integrations/instrumentation/listener_lifecycle_flow_spec.rb
needed to fix https://github.com/karafka/karafka/issues/1956
> Instrument listeners lifecycle events

- CHANGELOG.md
- lib/karafka/connection/status.rb
- lib/karafka/instrumentation/vendors/kubernetes/liveness_listener.rb
- lib/karafka/pro/swarm/liveness_listener.rb
- spec/integrations/pro/instrumentation/vendors/kubernetes/downscaled_multiplexing_support_spec.rb
- spec/integrations/pro/swarm/with_liveness_downscaling_multiplex_spec.rb
close https://github.com/karafka/karafka/issues/1956
close https://github.com/karafka/karafka/issues/1970
> ensure k8s and swarm liveness works with multiplexing

- CHANGELOG.md
- lib/karafka/pro/processing/expansions_selector.rb
- lib/karafka/pro/processing/piping/consumer.rb
- spec/integrations/pro/consumption/piping/with_alteration_to_headers_spec.rb
- spec/integrations/pro/consumption/piping/without_any_changes_spec.rb
- spec/integrations/pro/consumption/piping/without_any_changes_transactional_spec.rb
- spec/lib/karafka/pro/processing/piping/consumer_spec.rb
- spec/support/factories/messages/message.rb
close https://github.com/karafka/karafka/issues/1868
> Provide direct piping API

- Gemfile
- Gemfile.lock
- karafka.gemspec
- lib/karafka/admin/configs.rb
- lib/karafka/admin/configs/config.rb
- lib/karafka/admin/configs/resource.rb
- spec/integrations/admin/configs_flow_spec.rb
- spec/integrations/pro/rebalancing/with_static_membership_reconnect_spec.rb
- spec/integrations/rebalancing/with_static_membership_reconnect_spec.rb
- spec/integrations_helper.rb
- spec/lib/karafka/admin/configs/config_spec.rb
- spec/lib/karafka/admin/configs/resource_spec.rb
- spec/lib/karafka/admin/configs_spec.rb
This does not yet cover declaratives. Just introduces basic low level admin API for configs management similar to ACLs.
> Introduce Admins low-level configs API

- CHANGELOG.md
- lib/karafka/instrumentation/vendors/appsignal/client.rb
close https://github.com/karafka/karafka/issues/1977
> support custom appsignal namespace

- spec/integrations/pro/consumption/direct_assignments/multi_topic_stream_merging_spec.rb
close https://github.com/karafka/karafka/issues/1983
> stream merging low-level example

- lib/karafka/cli/topics/plan.rb
- spec/integrations/cli/declaratives/plan/when_missing_topics_partitions_and_configs_spec.rb
- spec/integrations/pro/rebalancing/virtual_partitions/coordinator_replacement_after_rebalance_spec.rb
close https://github.com/karafka/karafka/issues/1986
> Declarative unknown config name introduction fix

- config/locales/pro_errors.yml
- lib/karafka/pro/routing/features/direct_assignments/contracts/topic.rb
- spec/integrations/pro/consumption/patterns/complex_regexp_match_spec.rb
- spec/integrations/pro/routing/direct_assignments/with_pattern_attempt_spec.rb
- spec/lib/karafka/pro/routing/features/direct_assignments/contracts/topic_spec.rb
close https://github.com/karafka/karafka/issues/1988
adds one extra spec for patterns as well
> make sure direct assingments are not used with patterns

- CHANGELOG.md
- lib/active_job/queue_adapters/karafka_adapter.rb
Small PR to align doc and readme with https://github.com/karafka/karafka/pull/1990
> update readme and doc after PR with AJ fix

- spec/benchmarks/piping/multiple_workers_piping_with_delivery_time.rb
close https://github.com/karafka/karafka/issues/1920
> pipe benchmark

- spec/integrations/pro/consumption/direct_assignments/multi_topic_transactional_spec.rb
works OOB lol
close https://github.com/karafka/karafka/issues/2002
> multi-topic transactions spec

- .github/workflows/ci.yml
GH deprecates the docker-compose in favor of `docker-compose`.
> fix docker compose

- CHANGELOG.md
- lib/karafka/connection/listener.rb
- lib/karafka/embedded.rb
- lib/karafka/helpers/async.rb
- lib/karafka/instrumentation/logger_listener.rb
- lib/karafka/runner.rb
- spec/lib/karafka/helpers/async_spec.rb
- spec/lib/karafka/processing/worker_spec.rb
This PR adds names to threads to ease debugging and ttin.
> Name used threads

- CHANGELOG.md
- lib/karafka/admin.rb
- spec/integrations/admin/consumer_groups/seek_consumer_group_topic_time_total_past_multi_partition_all_spec.rb
- spec/integrations/admin/consumer_groups/seek_consumer_group_topic_time_total_past_multi_partition_spec.rb
- spec/integrations_helper.rb
close https://github.com/karafka/karafka/issues/2032
> fix admin group seek

- CHANGELOG.md
- lib/karafka/admin.rb
- spec/integrations/admin/consumer_groups/seek_consumer_group_topic_time_total_past_multi_partition_all_spec.rb
- spec/integrations/admin/consumer_groups/seek_consumer_group_topic_time_total_past_multi_partition_spec.rb
- spec/integrations_helper.rb
Backport https://github.com/karafka/karafka/pull/2033 to `2.3-stable`
> fix admin group seek, backport to 2.3

- spec/integrations/pro/consumption/strategies/dlq/vp/patterned_custom_strategy_based_flow_spec.rb
> pattern dlq vp err str spec

- CHANGELOG.md
- Gemfile.lock
- karafka.gemspec
close https://github.com/karafka/karafka/issues/2067
> use base64 from gem

- spec/integrations/pro/consumption/piping/with_key/transactional_with_marking_spec.rb
one more case tha was not covered: EOS with manual marking
> one more spec for marking in transaction and piping

- Gemfile.lock
- spec/integrations/testing/minitest_pristine/assertions.rb
covers https://github.com/karafka/karafka-testing/pull/200
> Ensure key and headers deserialization works with karafka-testing helpers

- CHANGELOG.md
- lib/karafka/active_job/job_extensions.rb
- spec/integrations/consumption/strategies/aj_mom/options_override_and_inheritance_spec.rb
- spec/integrations/pro/consumption/strategies/aj/mom/with_multiple_custom_partitioners_spec.rb
close https://github.com/karafka/karafka/issues/2092
> Fix activejob karafka_options inheritance

- spec/integrations/production/reject_no_key_message_when_compacted_spec.rb
close https://github.com/karafka/karafka/issues/2099
> Spec to check that keyless are rejected on compacted topics

- CHANGELOG.md
- Gemfile.lock
- config/locales/errors.yml
- lib/karafka/pro/active_job/job_options_contract.rb
- lib/karafka/version.rb
- spec/lib/karafka/pro/active_job/job_options_contract_spec.rb
close https://github.com/karafka/karafka/issues/2102
> validate activejob alternative producer option

- CHANGELOG.md
- lib/karafka/connection/client.rb
- spec/integrations/seek/to_a_given_offset_from_consumer_on_higher_partition_spec.rb
- spec/integrations/seek/to_time_before_start_on_higher_partition_spec.rb
close https://github.com/karafka/karafka/issues/2105
> Fix invalid time seek in higher offsets

- lib/karafka/runner.rb
part of https://github.com/karafka/karafka/issues/1888
> use config injector in the runner

- CHANGELOG.md
- lib/karafka/helpers/async.rb
close https://github.com/karafka/karafka/issues/2023
> remove empty default async thread name

- spec/integrations/installation/with_rails71_pristine/Gemfile
- spec/integrations/installation/with_rails7_pristine/Gemfile
Missin bigdecimal etc defs for Ruby 3.4
> rails7 ruby 3.4 fixes

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/connection/client.rb
- lib/karafka/version.rb
close https://github.com/karafka/karafka/issues/1921
> Propagate fatal errors faster

- CHANGELOG.md
- lib/karafka/pro/processing/strategies/dlq/default.rb
- spec/integrations/pro/consumption/strategies/dlq/default/raw_headers_dispatch_spec.rb
close https://github.com/karafka/karafka/issues/2151
> use raw_headers and raw_key in the DLQ dispatch

- spec/integrations/pro/consumption/transactions/lost_assignment_with_offset_storage_spec.rb
This PR adds few more assertions to the spec to cover more interesting things.
> enhance spec checks

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/routing/subscription_group.rb
- lib/karafka/setup/config.rb
- lib/karafka/version.rb
- spec/integrations/setup/config_with_inherited_client_id_spec.rb
- spec/lib/karafka/routing/subscription_group_spec.rb
- spec/lib/karafka/setup/config_spec.rb
close https://github.com/karafka/karafka/issues/2174
> mitigate hanging librdkafka on coop-sticky

- Gemfile.lock
- lib/karafka/setup/attributes_map.rb
- spec/lib/karafka/setup/attributes_map_spec.rb
superseeds https://github.com/karafka/karafka/pull/2181
> core, waterdrop, testing and karafka-rdkafka bump

- spec/integrations/consumption/time_bound_consumption_spec.rb
new librdkafka seems to close slower than previous
> give more time to stop librdkafka in shutdown specs

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/connection/client.rb
- lib/karafka/version.rb
- spec/lib/karafka/connection/listener_spec.rb
mitigates https://github.com/confluentinc/librdkafka/issues/4792
> mitigate librdkafka shutdown issues

- CHANGELOG.md
- Gemfile.lock
- karafka.gemspec
- lib/karafka/version.rb
close https://github.com/karafka/karafka/issues/2177
> fix spdx deprecated lgpl version

- CHANGELOG.md
- lib/karafka/routing/subscription_group.rb
- lib/karafka/setup/config.rb
- lib/karafka/setup/defaults_injector.rb
- spec/integrations/instrumentation/oauth_listener_producer_inheritance_spec.rb
- spec/integrations/pro/licensing/external_poro/loaded_via_custom_chain_spec.rb
- spec/integrations/pro/licensing/load_poro/configure_spec.rb
- spec/integrations/routing/alternative_kafka_scope_defaults_population_spec.rb
- spec/integrations/setup/load_poro/configure_spec.rb
- spec/integrations/setup/max_messages_format_as_string_spec.rb
- spec/integrations/setup/re_initialization_of_cached_resources_spec.rb
- spec/lib/karafka/setup/config_spec.rb
- spec/lib/karafka/setup/defaults_injector_spec.rb
- spec/lib/karafka/swarm/node_spec.rb
close https://github.com/karafka/karafka/issues/2193
> ensure defaults are always injected when missing

- spec/integrations/consumption/inflight_topic_removal_spec.rb
- spec/integrations/production/inflight_topic_removal_spec.rb
close https://github.com/karafka/karafka/issues/2114
> add topic removal specs

- lib/karafka/routing/consumer_group.rb
part of https://github.com/karafka/karafka/issues/1888
> move part of config fetching

- CHANGELOG.md
- lib/karafka/pro/processing/partitioner.rb
- spec/integrations/embedding/puma_with_worker_poro/config/puma.rb
- spec/integrations/pro/consumption/strategies/vp/with_error_in_partitioner_reduced_spec.rb
- spec/integrations/pro/consumption/strategies/vp/with_error_in_partitioner_spec.rb
- spec/lib/karafka/pro/processing/partitioner_spec.rb
close https://github.com/karafka/karafka/issues/2045
> handle vp partitioner errors gracefully

- CHANGELOG.md
- Gemfile.lock
- config/locales/errors.yml
- lib/karafka/connection/listener.rb
- lib/karafka/contracts/config.rb
- lib/karafka/setup/config.rb
- spec/integrations/admin/post_fork_behaviour_spec.rb
- spec/integrations_helper.rb
- spec/lib/karafka/connection/listener_spec.rb
- spec/lib/karafka/contracts/config_spec.rb
close https://github.com/karafka/karafka/issues/2209
superseeds https://github.com/karafka/karafka/pull/2207
> Bump rdkafka and spec admin

- CHANGELOG.md
- Gemfile.lock
- config/locales/errors.yml
- lib/karafka/routing/features/eofed/contracts/topic.rb
- lib/karafka/version.rb
- spec/integrations/routing/eofed/with_eof_disabled_and_kafka_eof_spec.rb
- spec/integrations/routing/eofed/with_eof_in_different_scope_spec.rb
- spec/integrations/routing/eofed/with_eof_in_same_scope_spec.rb
- spec/integrations/routing/eofed/with_eof_spec.rb
- spec/integrations/routing/eofed/without_eof_spec.rb
- spec/integrations_helper.rb
- spec/lib/karafka/routing/features/eofed/contracts/topic_spec.rb
close https://github.com/karafka/karafka/issues/2213
> validate eof consistency

- CHANGELOG.md
- lib/karafka/admin.rb
- spec/integrations/admin/rename_consumer_group/when_previous_and_new_cgs_exist_spec.rb
- spec/integrations/admin/rename_consumer_group/when_previous_cg_does_not_exist_spec.rb
- spec/integrations/admin/rename_consumer_group/with_non_existing_topics_spec.rb
- spec/integrations/admin/rename_consumer_group/without_old_removal_spec.rb
- spec/lib/karafka/admin_spec.rb
close https://github.com/karafka/karafka/issues/2217
> Provide API for CGs renaming

- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
just web bump because we cannot lock ffi because we test on 3.4
superseeds https://github.com/karafka/karafka/pull/2207
> update karafka web

- lib/karafka/pro/routing/features/recurring_tasks/builder.rb
- spec/integrations/pro/recurring_tasks/defining_schedule_spec.rb
- spec/integrations/pro/recurring_tasks/disable_enable_all_spec.rb
- spec/integrations/pro/recurring_tasks/disabled_state_replaying_spec.rb
- spec/integrations/pro/recurring_tasks/logging_data_published_spec.rb
- spec/integrations/pro/recurring_tasks/routes_creation_spec.rb
- spec/integrations/pro/recurring_tasks/state_publishing_frequency_spec.rb
- spec/integrations/pro/recurring_tasks/state_structure_spec.rb
- spec/integrations/pro/recurring_tasks/trigger_all_spec.rb
- spec/integrations/pro/recurring_tasks/version_downgrade_block_spec.rb
- spec/integrations/pro/recurring_tasks/version_upgrade_allowed_spec.rb
- spec/integrations/pro/recurring_tasks/with_changed_cron_between_versions_spec.rb
- spec/integrations/pro/recurring_tasks/with_completely_removed_schedule_spec.rb
- spec/integrations/pro/recurring_tasks/with_simple_disabled_job_spec.rb
- spec/integrations/pro/recurring_tasks/with_simple_enabled_job_spec.rb
- spec/integrations/pro/recurring_tasks/without_any_schedules_spec.rb
- spec/integrations/pro/recurring_tasks/without_fugit_pristine/fail_without_fugit_spec.rb
- spec/lib/karafka/pro/routing/features/recurring_tasks/builder_spec.rb
most of them require `true` as enabling argument so I added it here as well.
> Align API for recurring tasks in routing so it matches other methods in this API

- lib/karafka/pro/recurring_tasks/serializer.rb
- spec/integrations/pro/recurring_tasks/logging_data_published_on_errors_spec.rb
- spec/integrations/pro/recurring_tasks/logging_data_published_spec.rb
- spec/lib/karafka/pro/recurring_tasks/serializer_spec.rb
removes arguments that are redundant
> Remove unused args

- CHANGELOG.md
- config/locales/errors.yml
- lib/karafka/contracts/config.rb
- lib/karafka/processing/worker.rb
- lib/karafka/railtie.rb
- lib/karafka/setup/config.rb
- spec/lib/karafka/contracts/config_spec.rb
continuation of https://github.com/karafka/karafka/pull/2232
> Wrap worker/job execution with rails reloader or executor

- lib/karafka/pro/recurring_tasks/matcher.rb
- spec/lib/karafka/pro/recurring_tasks/matcher_spec.rb
this allows cross-version disabling on ui etc
> skip versioning check

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/messages/message.rb
- lib/karafka/version.rb
- spec/integrations/consumption/of_a_tombstone_record_spec.rb
- spec/integrations/embedding/puma_single_poro/config/puma.rb
- spec/lib/karafka/messages/message_spec.rb
This PR adds a message API to check if a message is a tombstone event.
> tombstone event check

- CHANGELOG.md
- lib/karafka/pro/routing/features/recurring_tasks/builder.rb
- spec/integrations/pro/recurring_tasks/smarter_reconfiguration_spec.rb
This PR allows for multi-topic reconfiguration of recurring tasks. Useful for setting of things like replication factor.
> support multi-topic reconfiguration

- config/locales/pro_errors.yml
- lib/karafka/pro/routing/features/scheduled_messages/builder.rb
- lib/karafka/pro/scheduled_messages/contracts/config.rb
- lib/karafka/pro/scheduled_messages/dispatcher.rb
- lib/karafka/pro/scheduled_messages/setup/config.rb
- spec/integrations/pro/scheduled_messages/day_rotation_spec.rb
- spec/integrations/pro/scheduled_messages/dispatch_crash_recovery_spec.rb
- spec/integrations/pro/scheduled_messages/future_scheduled_cancelling_spec.rb
- spec/integrations/pro/scheduled_messages/ordered_dispatches_spec.rb
- spec/integrations/pro/scheduled_messages/with_dispatched_except_one_for_dispatch_spec.rb
- spec/integrations/pro/scheduled_messages/with_mostly_future_dispatches_spec.rb
- spec/integrations/pro/scheduled_messages/without_any_messages_spec.rb
- spec/lib/karafka/pro/routing/features/scheduled_messages/builder_spec.rb
- spec/lib/karafka/pro/scheduled_messages/contracts/config_spec.rb
- spec/lib/karafka/pro/scheduled_messages/dispatcher_spec.rb
this slightly changes the naming, etc so its better
> normalize scheduled messages api

- spec/lib/karafka/pro/scheduled_messages/serializer_spec.rb
- spec/lib/karafka/time_trackers/poll_spec.rb
This spec stub would leak to different threads. This fixes it.
> stabilize time spec

- spec/integrations/pro/scheduled_messages/with_mostly_future_dispatches_spec.rb
- spec/integrations/specs_naming_spec.rb
- spec/integrations/web/with_request_without_rails_pristine/Gemfile
- spec/integrations/web/with_request_without_rails_pristine/config.ru
- spec/integrations/web/with_request_without_rails_pristine/install_and_run_spec.rb
close https://github.com/karafka/karafka/issues/2266
> ensure poro web-ui works with karafka

- CHANGELOG.md
- Gemfile.lock
- lib/active_job/queue_adapters/karafka_adapter.rb
- lib/karafka/version.rb
- spec/integrations/rails/rails72_pristine/with-active-job-transactional/Gemfile
- spec/integrations/rails/rails72_pristine/with-active-job-transactional/schedule_with_sqlite_spec.rb
- spec/lib/active_job/queue_adapters/karafka_adapter_spec.rb
close https://github.com/karafka/karafka/issues/2269
ref https://github.com/rails/rails/pull/52301
> support post-transactional job enqueue in aj

- spec/integrations/pro/web/with_tick_and_eofed_errors_spec.rb
close https://github.com/karafka/karafka/issues/2248
> Add spec for eofed and tick error handling on a message-less consumer

- CHANGELOG.md
- config/locales/pro_errors.yml
- lib/karafka/pro/scheduled_messages/contracts/message.rb
- spec/lib/karafka/pro/scheduled_messages/contracts/message_spec.rb
- spec/lib/karafka/pro/scheduled_messages/proxy_spec.rb
close https://github.com/karafka/karafka/issues/2271
> validate target topic

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/contracts/topic.rb
- lib/karafka/version.rb
- spec/integrations/routing/with_incomplete_kafka_reconfiguration_spec.rb
- spec/integrations/routing/with_topic_inherited_settings_spec.rb
- spec/lib/karafka/contracts/topic_spec.rb
- spec/lib/karafka/routing/builder_spec.rb
close https://github.com/karafka/karafka/issues/2276
> Validate existence of bootstrap.servers on redefines

- .github/workflows/ci.yml
- CHANGELOG.md
- config/locales/errors.yml
- lib/active_job/queue_adapters/karafka_adapter.rb
- lib/karafka/active_job/dispatcher.rb
- lib/karafka/pro/active_job/dispatcher.rb
- lib/karafka/pro/active_job/job_options_contract.rb
- spec/integrations/consumption/strategies/aj_mom/failing_perform_later_spec.rb
- spec/integrations/pro/scheduled_messages/active_job_future_job_spec.rb
- spec/lib/karafka/active_job/dispatcher_spec.rb
- spec/lib/karafka/pro/active_job/dispatcher_spec.rb
- spec/lib/karafka/pro/active_job/job_options_contract_spec.rb
close https://github.com/karafka/karafka/issues/2252
> support AJ future dispatches

- CHANGELOG.md
- lib/karafka/app.rb
- spec/integrations/setup/debug_mode_spec.rb
close https://github.com/karafka/karafka/issues/2282
> Introduce a `debug!` flag

- CHANGELOG.md
- lib/karafka/pro/scheduled_messages/contracts/message.rb
- lib/karafka/pro/scheduled_messages/proxy.rb
- spec/lib/karafka/pro/scheduled_messages/contracts/message_spec.rb
- spec/lib/karafka/pro/scheduled_messages/proxy_spec.rb
close https://github.com/karafka/karafka/issues/2278
> verify cancel topic

- lib/karafka/helpers/config_importer.rb
- lib/karafka/messages/message.rb
part of the refactor
ref https://github.com/karafka/karafka/issues/1888
> migrate message to config importer

- lib/active_job/queue_adapters/karafka_adapter.rb
another of https://github.com/karafka/karafka/issues/1888
> migrate dispatcher aj reference to config importer

- CHANGELOG.md
- lib/karafka/processing/executor.rb
- spec/integrations/consumption/strategies/dlq/with_custom_producer_spec.rb
- spec/integrations/production/via_overwritten_producer_spec.rb
close https://github.com/karafka/karafka/issues/2288
> allow for direct producer overwrite

- Gemfile.lock
- spec/integrations/consumption/strategies/default/with_failed_transactions_spec.rb
- spec/integrations/pro/consumption/transactions/early_exit_spec.rb
- spec/lib/karafka/admin_spec.rb
- spec/lib/karafka/pro/iterator_spec.rb
close https://github.com/karafka/karafka/issues/2165
> bump waterdrop and add specs

- Gemfile.lock
- spec/integrations/pro/web/commanding/trace_spec.rb
close https://github.com/karafka/karafka/pull/2296
> bump web to 0.10.3

- CHANGELOG.md
- Gemfile.lock
- lib/karafka.rb
- lib/karafka/version.rb
- spec/integrations/rails/rails70_pristine/without-active_job_rspec/console_with_rails_spec.rb
- spec/integrations/rails/rails71_pristine/with_kubernetes_listener_in_the_console/console_with_rails_spec.rb
- spec/integrations/rails/rails71_pristine/without-active_job_rspec/console_with_rails_spec.rb
- spec/integrations/rails/rails72_pristine/with_kubernetes_listener_in_the_console/console_with_rails_spec.rb
- spec/integrations/rails/rails72_pristine/without-active_job_rspec/console_with_rails_spec.rb
- spec/lib/karafka_spec.rb
close https://github.com/karafka/karafka/issues/2300
> fix ruby-lsp dir lookup

- CHANGELOG.md
- lib/karafka/cli/topics/plan.rb
- spec/integrations/cli/declaratives/plan/when_downscaling_partitions_spec.rb
- spec/integrations/cli/declaratives/plan/when_with_partitions_spec.rb
continuation of https://github.com/karafka/karafka/pull/2303
> Report partition downscale as ignored in declarative topics

- CHANGELOG.md
- lib/karafka/cli/base.rb
- lib/karafka/swarm/supervisor.rb
- spec/integrations/swarm/cli_validations_for_inclusions_spec.rb
continuation of https://github.com/karafka/karafka/pull/2306
close https://github.com/karafka/karafka/issues/2305
> Validate cli options in swarm

- CHANGELOG.md
- config/locales/errors.yml
- lib/karafka/contracts/config.rb
- lib/karafka/contracts/routing.rb
- lib/karafka/routing/builder.rb
- lib/karafka/setup/config.rb
- spec/integrations/cli/declaratives/strict_setup_requirement_spec.rb
- spec/integrations/pro/cli/declaratives/strict_setup_requirement_spec.rb
- spec/lib/karafka/contracts/config_spec.rb
- spec/lib/karafka/contracts/routing_spec.rb
close https://github.com/karafka/karafka/issues/2311
> Introduce strict mode for declarative topics

- CHANGELOG.md
- lib/karafka/instrumentation/vendors/kubernetes/base_listener.rb
- lib/karafka/instrumentation/vendors/kubernetes/liveness_listener.rb
- spec/lib/karafka/instrumentation/vendors/kubernetes/base_listener_spec.rb
close https://github.com/karafka/karafka/issues/2302
> promote healthy? to public

- spec/integrations/web/with_request_without_rails_pristine/Gemfile
- spec/integrations/web/with_request_without_rails_pristine/install_and_run_spec.rb
This PR fixes a spec that fails because it doesn't bind to a port
> Fix failing port binding spec

- lib/karafka/instrumentation/vendors/datadog/metrics_listener.rb
A pattern I've seen in our app while memory profiling is using `+` and `+=` to join together arrays.
I was making other changes around this code, and figured I'd do this part first. Also: not saying this is a "big" memory improvement, but these are the type of small things that add up in large apps.
Consider:
```ruby
tags = ["a:1"]
tags += ["b:2"]
````
This creates 3 arrays, but only the last 
- line 1 assigning to tags (`["a:1"]`)
- the right hand side (`["b:2"]`)
- the two added together (`["a:1", "b:2"]`)
In many cases, we can reduce this to one array:
```
tags = ["a:1"]
tags.append("b:2")
```
In the casees of having another array, `concat` can be used in a similar way to avoid creating an extra array.
Worth noting that sometimes this ends up in a slightly different order, but for tags …
> Update Datadog metrics listener to avoid creating extra arrays

- lib/karafka/instrumentation/vendors/datadog/metrics_listener.rb
continuation of https://github.com/karafka/karafka/pull/2338
> Update Datadog metrics listener to avoid creating extra arrays (#2338)

- CHANGELOG.md
- lib/karafka/instrumentation/vendors/appsignal/metrics_listener.rb
- lib/karafka/instrumentation/vendors/datadog/logger_listener.rb
- spec/integrations/instrumentation/vendors/datadog/metrics_with_eofed_spec.rb
close https://github.com/karafka/karafka/issues/2341
> improve dd and appsignal listeners

- spec/integrations/pro/consumption/direct_assignments/multi_topic_transactional_spec.rb
There was a race condition in between the topics so the spec failed once in a while as not all the data was being fetched on shutdown by the last topic.
Sleep mitigates this + the return on stop on consumers not to produce more.
> stabilize trans spec

- spec/integrations/pro/rebalancing/transactions/revoke_continuity_spec.rb
- spec/integrations/pro/rebalancing/transactions/revoke_reclaim_continuity_cooperative_spec.rb
- spec/integrations/pro/rebalancing/transactions/revoke_reclaim_continuity_spec.rb
This PR adds more integration specs.
> Add more specs

- .github/workflows/ci.yml
- Gemfile
- Gemfile.lock
- spec/integrations_helper.rb
ref https://github.com/karafka/karafka/issues/2371
> use ruby 3.4 as default

- spec/integrations/consumption/wrapping/wrapped_error_handling_spec.rb
ref https://github.com/karafka/karafka/issues/2392
> illustrate wrap yielding flow

- spec/integrations/pro/recurring_tasks/with_completely_removed_schedule_spec.rb
This spec would fail today because date was set fixed.
> Make spec run on nye

- spec/integrations/pro/recurring_tasks/with_changed_cron_between_versions_spec.rb
similar to this: https://github.com/karafka/karafka/pull/2396 just failing on jan 1st
> Make spec run on jan1

- spec/integrations/instrumentation/vendors/datadog/with_original_client_pristine/Gemfile
- spec/integrations/instrumentation/vendors/datadog/with_original_client_pristine/with_proper_ddtrace_spec.rb
close https://github.com/karafka/karafka/issues/2387
> make dd integrations work with 3.4

- CHANGELOG.md
- lib/karafka/base_consumer.rb
- lib/karafka/instrumentation/notifications.rb
- lib/karafka/pro/processing/strategies/aj/dlq_ftr_lrj_mom.rb
- lib/karafka/pro/processing/strategies/aj/dlq_ftr_lrj_mom_vp.rb
- lib/karafka/pro/processing/strategies/aj/dlq_lrj_mom.rb
- lib/karafka/pro/processing/strategies/aj/dlq_lrj_mom_vp.rb
- lib/karafka/pro/processing/strategies/aj/ftr_lrj_mom_vp.rb
- lib/karafka/pro/processing/strategies/aj/lrj_mom_vp.rb
- lib/karafka/pro/processing/strategies/default.rb
- lib/karafka/pro/processing/strategies/dlq/default.rb
- lib/karafka/pro/processing/strategies/dlq/ftr_lrj.rb
- lib/karafka/pro/processing/strategies/dlq/ftr_lrj_mom.rb
- lib/karafka/pro/processing/strategies/dlq/ftr_mom.rb
- lib/karafka/pro/processing/strategies/dlq/lrj.rb
- lib/karafka/pro/processing/strategies/dlq/lrj_mom.rb
- lib/karafka/pro/processing/strategies/dlq/mom.rb
- lib/karafka/pro/processing/strategies/lrj/default.rb
- lib/karafka/pro/processing/strategies/lrj/ftr.rb
- lib/karafka/processing/strategies/aj_dlq_mom.rb
- lib/karafka/processing/strategies/default.rb
- lib/karafka/processing/strategies/dlq.rb
- lib/karafka/processing/strategies/dlq_mom.rb
- spec/integrations/pro/consumption/transactions/with_marking_tracking_via_instrumentation_spec.rb
this PR exposes api to track successful transactions. Can be used for enhanced seek offset tracking, etc
> expose tracking of transactions in consumers

- spec/integrations/pro/consumption/transactions/with_abort_spec.rb
- spec/integrations/pro/consumption/transactions/with_lag_less_statistics_spec.rb
close https://github.com/karafka/karafka/issues/2410
> more transactional specs

- CHANGELOG.md
- lib/karafka/instrumentation/logger_listener.rb
- spec/integrations/instrumentation/assignment_and_revocation_logs_spec.rb
- spec/lib/karafka/instrumentation/logger_listener_spec.rb
This PR adds rebalance logging info. Useful for debugging
close https://github.com/karafka/karafka/issues/2419
> log rebalance info

- .github/workflows/ci.yml
- bin/verify_kafka_warnings
- spec/integrations/instrumentation/post_errors_instrumentation_error_spec.rb
- spec/integrations/pro/consumption/direct_assignments/multi_topic_stream_merging_spec.rb
- spec/integrations/pro/consumption/direct_assignments/multi_topic_transactional_spec.rb
part of https://github.com/karafka/karafka/issues/2358
> run post-execution kafka logs checks

- CHANGELOG.md
- config/locales/errors.yml
- lib/karafka/connection/listener.rb
- lib/karafka/contracts/config.rb
- lib/karafka/helpers/async.rb
- lib/karafka/runner.rb
- lib/karafka/setup/config.rb
- spec/integrations/setup/with_custom_worker_thread_priority_spec.rb
- spec/lib/karafka/contracts/config_spec.rb
Following great summary here: https://github.com/bensheldon/good_job/issues/1554
I'm introducing similar management capabilities for thread priority.
> allow for thread priority control

- CHANGELOG.md
- lib/karafka/swarm/node.rb
- spec/integrations/swarm/with_different_producer_payload_sizes_spec.rb
close https://github.com/karafka/karafka/issues/2442
> Fix for lack of inheritance of post-fork attributes in producer

- CHANGELOG.md
- config/locales/pro_errors.yml
- lib/karafka/pro/routing/features/multiplexing/contracts/topic.rb
- spec/integrations/pro/consumption/multiplexing/static_with_many_topics_and_partitions_spec.rb
- spec/integrations/pro/swarm/low_multiplexing_on_many_topics_spec.rb
- spec/lib/karafka/pro/routing/features/multiplexing/contracts/topic_spec.rb
close https://github.com/karafka/karafka/issues/2443
> do not allow 1:1 multiplexing

- .github/workflows/ci.yml
- CHANGELOG.md
- bin/verify_topics_naming
close https://github.com/karafka/karafka/issues/2454
> verify test topics naming convention in the CI

- .github/CODEOWNERS
- .github/workflows/ci.yml
- .github/workflows/verify-action-pins.yml
- renovate.json
I'm hardening the workflows to introduce self-hosted runners future usage
> workflow hardening

- CHANGELOG.md
- spec/integrations/routing/with_altered_routing_flow_spec.rb
close https://github.com/karafka/karafka/issues/2344
> Include the partial reconfiguration routing patches in the integration test suite

- CHANGELOG.md
- config/locales/pro_errors.yml
- lib/karafka/pro/processing/partitioner.rb
- lib/karafka/pro/processing/virtual_partitions/distributors/balanced.rb
- lib/karafka/pro/processing/virtual_partitions/distributors/base.rb
- lib/karafka/pro/processing/virtual_partitions/distributors/consistent.rb
- lib/karafka/pro/routing/features/virtual_partitions/config.rb
- lib/karafka/pro/routing/features/virtual_partitions/contracts/topic.rb
- lib/karafka/pro/routing/features/virtual_partitions/topic.rb
- spec/integrations/pro/consumption/strategies/vp/balanced_distribution_spec.rb
- spec/lib/karafka/connection/raw_messages_buffer_spec.rb
- spec/lib/karafka/pro/processing/virtual_partitions/distributors/balanced_spec.rb
- spec/lib/karafka/pro/processing/virtual_partitions/distributors/base_spec.rb
- spec/lib/karafka/pro/processing/virtual_partitions/distributors/consistent_spec.rb
- spec/lib/karafka/pro/routing/features/virtual_partitions/contracts/topic_spec.rb
- spec/lib/karafka/pro/routing/features/virtual_partitions/topic_spec.rb
- spec/support/factories/messages/message.rb
close https://github.com/karafka/karafka/issues/2515
> Introduce a new balanced distribution mode for VPs

- .github/workflows/ci.yml
- CHANGELOG.md
- bin/integrations
close https://github.com/karafka/karafka/issues/2449
> improve CI parallelization

- CHANGELOG.md
- lib/karafka/admin.rb
- spec/integrations/admin/copy_consumer_group/when_previous_and_new_cgs_exist_spec.rb
- spec/integrations/admin/copy_consumer_group/when_previous_cg_does_not_exist_spec.rb
- spec/integrations/admin/copy_consumer_group/with_non_existing_topics_spec.rb
- spec/integrations/admin/rename_consumer_group/when_previous_cg_does_not_exist_spec.rb
- spec/integrations/admin/rename_consumer_group/without_old_removal_spec.rb
- spec/lib/karafka/admin_spec.rb
close https://github.com/karafka/karafka/issues/2522
> improve cg management admin apis

- spec/support/duplications_detector.rb
close https://github.com/karafka/karafka/issues/2534
> second layer of dd specs

- spec/integrations_helper.rb
mitigates https://github.com/karafka/karafka/actions/runs/14482782437/job/40622832961
> stabilize wait_for_assignments

- lib/karafka/templates/karafka.rb.erb
I had encountered few cases recently where users would use the default CG for few apps causing conflicts in their processing.
This PR is the first step to improve the situation.
close https://github.com/karafka/karafka/issues/2553
> improve the default setup template

- lib/karafka/pro/cleaner.rb
- lib/karafka/pro/encryption.rb
- lib/karafka/pro/loader.rb
- lib/karafka/pro/recurring_tasks.rb
- lib/karafka/pro/scheduled_messages.rb
- lib/karafka/swarm/node.rb
- spec/integrations/pro/recurring_tasks/within_swarm_and_custom_producer_spec.rb
- spec/integrations/pro/recurring_tasks/within_swarm_spec.rb
- spec/integrations/pro/scheduled_messages/within_swarm_spec.rb
- spec/integrations_helper.rb
- spec/spec_helper.rb
close https://github.com/karafka/karafka/issues/2569
> fix recurring tasks not working with swarm

- spec/integrations/rails/rails71_pristine/with_kubernetes_listener_in_the_console/Gemfile
- spec/integrations/rails/rails71_pristine/without-active_job_rspec/Gemfile
rspec 8 is not compatible with rails 7.1 hence lock.
> fix rails71 specs

- CHANGELOG.md
- lib/karafka/pro/scheduled_messages/consumer.rb
- lib/karafka/pro/scheduled_messages/daily_buffer.rb
- lib/karafka/pro/scheduled_messages/deserializers/headers.rb
- lib/karafka/pro/scheduled_messages/max_epoch.rb
- spec/integrations/pro/scheduled_messages/fast_close_past_schedules_spec.rb
- spec/lib/karafka/pro/scheduled_messages/daily_buffer_spec.rb
- spec/lib/karafka/pro/scheduled_messages/deserializers/headers_spec.rb
- spec/lib/karafka/pro/scheduled_messages/max_epoch_spec.rb
close https://github.com/karafka/karafka/issues/2578
> fix state loading and scheduling with mild memory preservation

- CHANGELOG.md
- config/locales/pro_errors.yml
- lib/karafka/pro/connection/manager.rb
- lib/karafka/pro/routing/features/multiplexing/config.rb
- lib/karafka/pro/routing/features/multiplexing/contracts/topic.rb
- lib/karafka/pro/routing/features/multiplexing/proxy.rb
- lib/karafka/pro/routing/features/multiplexing/subscription_group.rb
- spec/integrations/pro/consumption/multiplexing/dynamic_downscale_spec.rb
- spec/integrations/pro/consumption/multiplexing/dynamic_with_max_start_spec.rb
- spec/integrations/pro/consumption/multiplexing/dynamic_with_mid_start_spec.rb
- spec/integrations/pro/consumption/multiplexing/dynamic_with_min_start_spec.rb
- spec/integrations/pro/instrumentation/vendors/kubernetes/downscaled_multiplexing_support_spec.rb
- spec/integrations/pro/routing/multiplexing/too_small_scale_delay_spec.rb
- spec/integrations/pro/swarm/with_liveness_downscaling_multiplex_spec.rb
- spec/lib/karafka/pro/connection/manager_spec.rb
- spec/lib/karafka/pro/routing/features/multiplexing/contracts/topic_spec.rb
close https://github.com/karafka/karafka/issues/2544
> customize multiplexing delay per CG

- CHANGELOG.md
- lib/karafka/admin.rb
- lib/karafka/setup/config.rb
- spec/lib/karafka/admin/configs_spec.rb
close https://github.com/karafka/karafka/issues/2463
> Lower the native kafka rd poll timeout for admin

- CHANGELOG.md
- lib/karafka/cli/base.rb
close https://github.com/karafka/karafka/issues/2592
> fix optparse losing argv data

- CHANGELOG.md
- lib/karafka.rb
close https://github.com/karafka/karafka/issues/2590
> fallback without bundler

- CHANGELOG.md
- lib/karafka/setup/config.rb
- lib/karafka/setup/defaults_injector.rb
- spec/lib/karafka/setup/defaults_injector_spec.rb
close https://github.com/karafka/karafka/issues/2593
> Set producer dev metadata refresh defaults to 5s similar to consumer

- spec/integrations/seek/back_to_expired_spec.rb
close https://github.com/karafka/karafka/issues/2608
> add spec on expired seek

- CHANGELOG.md
- lib/karafka/admin.rb
- lib/karafka/base_consumer.rb
- lib/karafka/connection/client.rb
- lib/karafka/pro/iterator/expander.rb
- lib/karafka/pro/iterator/tpl_builder.rb
- spec/integrations/pro/iterator/named_earliest_spec.rb
- spec/integrations/pro/iterator/named_latest_spec.rb
- spec/integrations/seek/to_earliest_spec.rb
- spec/integrations/seek/to_latest_spec.rb
close https://github.com/karafka/karafka/issues/2609
> allow for named seek usage

- spec/integrations/pro/consumption/patterns/negative_lookup_spec.rb
close https://github.com/karafka/karafka/issues/2619
> fix naming of topics in test

- lib/karafka/server.rb
ref https://github.com/karafka/karafka/issues/1888
> use config injector in the server

- lib/karafka/admin.rb
- lib/karafka/admin/configs.rb
- lib/karafka/pro/scheduled_messages/consumer.rb
ref https://github.com/karafka/karafka/issues/1888
> config injector refactor cd

- CHANGELOG.md
- lib/karafka/connection/client.rb
close https://github.com/karafka/karafka/issues/2634
> fix rare edge case of negative seek

- Gemfile.lock
- lib/karafka/version.rb
test release for trusted publishing
> v2.5.0.beta2

- CHANGELOG.md
- lib/karafka/pro/scheduled_messages/dispatcher.rb
- spec/integrations/pro/scheduled_messages/dispatch_crash_recovery_spec.rb
- spec/lib/karafka/pro/scheduled_messages/dispatcher_spec.rb
close https://github.com/karafka/karafka/issues/2642
> use independent last states

- CHANGELOG.md
- lib/karafka/pro/scheduled_messages/consumer.rb
- lib/karafka/pro/scheduled_messages/serializer.rb
- lib/karafka/pro/scheduled_messages/tracker.rb
- spec/lib/karafka/pro/scheduled_messages/serializer_spec.rb
- spec/lib/karafka/pro/scheduled_messages/tracker_spec.rb
close https://github.com/karafka/karafka/issues/2638
> enhance scheduled messages reporting

- CHANGELOG.md
- lib/karafka/helpers/interval_runner.rb
- lib/karafka/pro/scheduled_messages/consumer.rb
- lib/karafka/pro/scheduled_messages/state.rb
- lib/karafka/pro/scheduled_messages/tracker.rb
- spec/integrations/pro/scheduled_messages/with_constant_non_eof_flow_spec.rb
- spec/lib/karafka/helpers/interval_runner_spec.rb
- spec/lib/karafka/pro/scheduled_messages/state_spec.rb
close https://github.com/karafka/karafka/issues/2633
> improved scheduled messages

- Gemfile
- Gemfile.lock
- spec/integrations/pro/web/dlq_tracing_match_spec.rb
close https://github.com/karafka/karafka/issues/2672
> introduce trace spec

- CHANGELOG.md
- lib/karafka/instrumentation/logger_listener.rb
- spec/integrations/instrumentation/assignment_and_revocation_logs_spec.rb
- spec/lib/karafka/instrumentation/logger_listener_spec.rb
part of https://github.com/karafka/karafka/issues/2677
> normalize logs format

- CHANGELOG.md
- lib/karafka/instrumentation/vendors/kubernetes/base_listener.rb
- lib/karafka/instrumentation/vendors/kubernetes/liveness_listener.rb
- lib/karafka/instrumentation/vendors/kubernetes/swarm_liveness_listener.rb
- spec/integrations/instrumentation/vendors/kubernetes/consuming_liveness_parallel_regular_flow_spec.rb
- spec/integrations/instrumentation/vendors/kubernetes/consuming_liveness_parallel_timeout_flow_spec.rb
- spec/integrations/instrumentation/vendors/kubernetes/consuming_liveness_timeout_flow_spec.rb
- spec/integrations/instrumentation/vendors/kubernetes/fenced_out_criticality_spec.rb
- spec/integrations/instrumentation/vendors/kubernetes/liveness_all_good_spec.rb
- spec/integrations/instrumentation/vendors/kubernetes/polling_liveness_timeout_flow_spec.rb
- spec/integrations/instrumentation/vendors/kubernetes/swarm_liveness_all_good_spec.rb
- spec/integrations/instrumentation/vendors/kubernetes/swarm_liveness_not_controlling_often_spec.rb
- spec/integrations/pro/instrumentation/vendors/kubernetes/downscaled_multiplexing_support_spec.rb
- spec/integrations/pro/instrumentation/vendors/kubernetes/liveness_from_ticking_spec.rb
close https://github.com/karafka/karafka/issues/2679
> report in k8s body details

- CHANGELOG.md
- Gemfile.lock
- karafka.gemspec
- lib/karafka/active_job/job_extensions.rb
- lib/karafka/contracts/base.rb
- lib/karafka/pro/encryption.rb
- lib/karafka/pro/recurring_tasks.rb
- lib/karafka/pro/routing/features/swarm.rb
- lib/karafka/pro/routing/features/swarm/contracts/routing.rb
- lib/karafka/pro/scheduled_messages.rb
- lib/karafka/pro/scheduled_messages/proxy.rb
- lib/karafka/routing/builder.rb
- lib/karafka/routing/features/base/expander.rb
- lib/karafka/server.rb
- lib/karafka/setup/config.rb
- lib/karafka/swarm/supervisor.rb
- spec/integrations/pro/cli/swarm/with_nothing_matching_spec.rb
- spec/integrations/pro/encryption/setup/config_scope_validation_spec.rb
- spec/integrations/pro/routing/recurring_tasks/validations_flows_spec.rb
- spec/integrations/pro/routing/scheduled_messages/validations_flows_spec.rb
- spec/integrations/routing/and_cli_validations_for_inclusions_spec.rb
- spec/integrations/setup/config_validation_spec.rb
- spec/lib/karafka/active_job/job_extensions_spec.rb
- spec/lib/karafka/setup/config_spec.rb
close https://github.com/karafka/karafka/issues/2676
> improve contracts validations reporting

- CHANGELOG.md
- spec/integrations/instrumentation/vendors/datadog_native_pristine/Gemfile
- spec/integrations/instrumentation/vendors/datadog_native_pristine/consume_with_tracing_spec.rb
close https://github.com/karafka/karafka/issues/2586
ref https://github.com/DataDog/dd-trace-rb/issues/4626
> add basic sanity checks for native dd integration

- CHANGELOG.md
- lib/karafka/instrumentation/logger_listener.rb
Small improvement to how TTIN is printed.
> improve ttin reporting

- CHANGELOG.md
- lib/karafka/connection/client.rb
- spec/integrations/consumption/with_unwanted_offset_reset_spec.rb
close https://github.com/karafka/karafka/issues/2704
> add better support for error offset reset state

- CHANGELOG.md
- Gemfile.lock
- karafka.gemspec
- lib/karafka/admin/acl.rb
- spec/lib/karafka/admin/acl_spec.rb
close https://github.com/karafka/karafka/issues/2706
> transactional ids acl management

- CHANGELOG.md
- Gemfile.lock
- lib/active_job/queue_adapters/karafka_adapter.rb
- spec/integrations/rails/rails71_pristine/with-active_job_and_perform_all_later/perform_all_later_run_spec.rb
- spec/integrations/rails/rails72_pristine/with-active_job_and_perform_all_later/perform_all_later_run_spec.rb
- spec/integrations/rails/rails80_pristine/with-active_job_and_perform_all_later/perform_all_later_run_spec.rb
Someone from the Shoryuken community pointed out the inheritance flaw there and I noticed we could improve things here alongside.
> improve aj parent

- CHANGELOG.md
- lib/karafka.rb
same as https://github.com/karafka/karafka-core/pull/227
> normalize require

- spec/integrations/pro/consumption/strategies/ftr/partial_offset_storage_race_condition_spec.rb
close https://github.com/karafka/karafka/issues/2473
> extra spec

- CHANGELOG.md
- lib/karafka/admin.rb
- lib/karafka/admin/acl.rb
- lib/karafka/admin/configs.rb
- lib/karafka/admin/configs/config.rb
- lib/karafka/admin/configs/resource.rb
- lib/karafka/admin/consumer_groups.rb
- lib/karafka/admin/topics.rb
- spec/lib/karafka/admin/consumer_groups_spec.rb
- spec/lib/karafka/admin/topics_spec.rb
- spec/lib/karafka/admin_spec.rb
close https://github.com/karafka/karafka/issues/2786
> Refactor root admin operations

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/connection/client.rb
- lib/karafka/connection/proxy.rb
- lib/karafka/version.rb
- spec/integrations/pro/consumption/cleaner/external_prepend_compatibility_spec.rb
- spec/integrations/rebalancing/kip_848/newly_joined_fencing_spec.rb
close https://github.com/karafka/karafka/issues/2815
> kip 848 support and specs
