karafka/karafka

- lib/karafka/templates/app.rb.example
Original code resulted in:
karafka/lib/karafka/connection/broker_manager.rb:41:in `zk': undefined
method `hosts' for ["127.0.0.1:2181"]:Array (NoMethodError)
when starting using 'bundle exec karafka server'
> Changed template to work with how the zk gem expects it

- lib/karafka/logger.rb
- spec/lib/karafka/logger_spec.rb
When you follow the Readme to create a new Karafka application, it will
throw an error stating that the log dir does not exist. This directory
cannot be created by the CLI install command, because the logger needs
to be initialized before that.
This commit adds a check for the directory, and adds a spec for this as
well
> Make sure the log directory exists

- lib/karafka/templates/app.rb.example
doing a clean install then:
bundle exec karafka
gave:
NoMethodError: undefined method hosts' for {:hosts=>["127.0.0.1:9092"]}:Hash from waterdrop: lib/karafka/setup/configurators/water_drop.rb:12:inblock in setup'
> fix error on startup from waterdrop

- lib/karafka/routing/route.rb
- spec/lib/karafka/base_responder_spec.rb
- spec/lib/karafka/responders/topic_spec.rb
- spec/lib/karafka/routing/route_spec.rb
__What are you trying to accomplish with this PR?__
Dots are valid in Kafka topic syntax. After starting a project with Karafka, i found out i couldn't map any route to my topics since they are namespaced using dots. 
__How is this accomplished?__
Adding the `\.` option in the `NAME_FORMAT` regex fixed my issue without causing any further problem.
I also tweaked the tests a bit by removing the `rand(...).to_s` to a valid string containing alphanumeric character, an underscore, a dash and a dot.
@mensfeld
> Added dot in topic validation format

- README.md
I recently implemented a custom monitor following the example in the readme. Everything was super straight forward except it seems the base class was changed to a singleton after the docs were written. Running the code as is produces:
```
NoMethodError: private method `new' called for CustomMonitor:Class
```
I updated the readme to reflect how to construct the singleton object.
> update readme section about custom monitors which are now singletons

- lib/karafka/base_responder.rb
- spec/lib/karafka/base_responder_spec.rb
In our application we're quite dependant on partition support, so i added it :)
I chose to add support for waterdrop options per `respond_to`. That way the options can be based on the data. The proposed solution introduces a bit more complexity in the message buffer. A topic is no longer linked to just the message, but an array/pair of the data and the waterdrop options.
Let me know what you think
> Allow options into responder (fixes #95)

- CHANGELOG.md
- README.md
- lib/karafka/base_controller.rb
- lib/karafka/cli/info.rb
- lib/karafka/connection/topic_consumer.rb
- lib/karafka/routing/builder.rb
- lib/karafka/routing/route.rb
- lib/karafka/setup/config.rb
- lib/karafka/templates/app.rb.example
- spec/lib/karafka/base_controller_spec.rb
- spec/lib/karafka/cli/info_spec.rb
- spec/lib/karafka/cli/routes_spec.rb
- spec/lib/karafka/connection/topic_consumer_spec.rb
- spec/lib/karafka/routing/route_spec.rb
- spec/lib/karafka/routing/router_spec.rb
We started using karafka, but we've hit a wall with our throughput. By enabling the batch mode, I was able to increase 10 fold the throughput on a simple 2 partition topic.
I'm pretty sure that in production that throughput increase would significantly be more.
This PR adds the batch message consumption from ruby-kafka, as mentioned here: https://github.com/zendesk/ruby-kafka/blob/e9613b54516ca7d58894fe999ab930ab4b732d00/README.md#consuming-messages-in-batches
To enable the batch mode, you can either specify the system wide setting, or use it per topic, such as:
```
topic :binary_video_details do
controller Videos::DetailsController
batch_mode true
end
```
@mensfeld
> Add support to batch incoming messages

- lib/karafka/process.rb
- lib/karafka/server.rb
- spec/lib/karafka/server_spec.rb
We use Karafka with Heroku Kafka and noticed that Kafka Server does not properly shut down on Heroku because SIGTERM is used instead of SIGQUIT or SIGINT. This PR simply adds support for SIGTERM as well.
> Handle SIGTERM as a shutdown command for kafka server to support Heroku deployment

- README.md
- lib/karafka.rb
- spec/lib/karafka_spec.rb
Allow using `ENV['KARAFKA_ROOT_DIR']` to specify the root directory for Karafka. We use this so we can have all of our Karafka classes and logic in a subdirectory of a parent Rails app, but still share the same Gemfile. The Rails app can then be loaded without Karafka's classes and dependencies.
> Allow karafka root to be specified from ENV

- README.md
AS IS: The contributions section is using a relative path and is not properly linked to github's contributors page.
TO BE: The contributors section is using an absolute path and is properly linked to github's contributors page.
> Link to contributors directly

- lib/karafka/setup/config.rb
See #186 
The ability to load the ca cert from a file is required to support Heroku Kafka due to a change they are rolling out where multiple ca certs may be present on the brokers. Also see: https://devcenter.heroku.com/articles/ca-cert-rotation-kafka
> add support for ruby-kafka `ssl_ca_cert_file_path` config

- lib/karafka/connection/config_adapter.rb
- lib/karafka/connection/messages_processor.rb
- spec/lib/karafka/connection/config_adapter_spec.rb
- spec/lib/karafka/connection/messages_processor_spec.rb
fixes [#196]
In the below situation, karafka will now correctly subscribe to `staging_my_topic`. Also fixes an issue where when a topic mapper is in place the `@topic` instance variable on the message would get replaced, leading to the message to be processed over and over as it would never be committed as read.
```
module StagingTopicMapper
PREFIX = 'staging_'
def self.incoming(topic)
topic.to_s.gsub(PREFIX, '')
end
def self.outgoing(topic)
"#{PREFIX}#{topic}"
end
end
```
```
consumer_groups.draw do
topic :my_topic
end
```
> fix [#196] incorrect subscriptions are created when topic mapper is used

- spec/spec_helper.rb
`spec_helper.rb` checks for `RUBY_VERSION` environment variable.
Perhaps it could fall back to `RUBY_VERSION` constant for `jruby?` check?
> check RUBY_ENGINE constant if RUBY_VERSION is missing

- lib/karafka/setup/config.rb
- lib/karafka/setup/configurators/celluloid.rb
- spec/lib/karafka/setup/configurators/celluloid_spec.rb
At times our consumers take longer than default 30 seconds to process a batch of messages. We'd like to extend the default shutdown period (just like we have extended termination period for docker containers running these consumers).
Not sure if that should to be scoped by `celluloid`, but here goes.
> add configuration setting to control Celluloid's shutdown timeout

- lib/karafka/patches/ruby_kafka.rb
Assumedly `Patches` was the intended word here
> Typo in docstring for Karafka::Patches::RubyKafka

- CHANGELOG.md
- Gemfile.lock
- karafka.gemspec
> Too shallow ruby-kafka version lock

- CHANGELOG.md
- lib/karafka/base_consumer.rb
- lib/karafka/connection/client.rb
- spec/lib/karafka/base_consumer_spec.rb
- spec/lib/karafka/connection/client_spec.rb
closes #359 
Allows to mark as consumed faster without triggering the blocking call to kafka for offset commits.
> Divide mark_as_consumed into mark_as_consumed and mark_as_consumed!

- CHANGELOG.md
- lib/karafka/attributes_map.rb
- lib/karafka/persistence/consumer.rb
- lib/karafka/schemas/consumer_group_topic.rb
- lib/karafka/setup/config.rb
- spec/lib/karafka/connection/batch_delegator_spec.rb
- spec/lib/karafka/connection/message_delegator_spec.rb
- spec/lib/karafka/patches/ruby_kafka_spec.rb
- spec/lib/karafka/persistence/consumer_spec.rb
- spec/lib/karafka/routing/router_spec.rb
This will allow us to optimize how consumers are being built and pre heat everything.
It will also simplify a bit the codebase and allow further steps towards Ruby 3.0 support.
> Remove persistence in favor of persisting

- CHANGELOG.md
- lib/karafka/connection/client.rb
- spec/lib/karafka/connection/client_spec.rb
This PR removes catching of the system exceptions (that shouldn't be used) allowing them to propagate to the listener, so it can reinitialize the client upon a critical exception.
> Allow exceptions to propagate

- lib/karafka/base_responder.rb
- lib/karafka/responders/topic.rb
- spec/lib/karafka/base_responder_spec.rb
This addresses the two cases listed on https://github.com/karafka/karafka/issues/460
Case 1:
```
Class MyResponder < BaseResponder
def default_generator_class
MyCustomParser
end
end
```
Case 2:
```
Class MyResponder < BaseResponder
def respond(data)
if some_condition
respond_to :topic1, data, generator: MyCustomParser
else
respond_to :topic2, data, generator: MyOtherCustomerParser
end
respond_to :topic3, data, generator: YetAnotherCustomerParser
end
end
```
I struggled with naming, feedback welcome. "Parser" is Karafka's term
for what's known in Kafka as a deserializer. It seems confusing to
call the serializer a parser too. Since the method called on it is
`generate()` I chose "generator".
> Override generator (parser) for responder

- lib/karafka/instrumentation/monitor.rb
- lib/karafka/server.rb
This PR adds additional post stop events for hooking up cleanup or anything else that needs to run after everything is stopped.
> add additional post stop events

- CHANGELOG.md
- lib/karafka/helpers/class_matcher.rb
- lib/karafka/responders/builder.rb
- spec/lib/karafka/helpers/class_matcher_spec.rb
Fixes: https://github.com/karafka/sidekiq-backend/issues/29 by injecting the proper naming from which we remap in case it is missing, so the remapping remaps to a proper worker name.
> sidekiq backend issue 29

- lib/karafka/schemas/consumer_group.rb
- lib/karafka/setup/config.rb
- spec/lib/karafka/connection/api_adapter_spec.rb
- spec/lib/karafka/connection/builder_spec.rb
Since 0.7.7 version of ruby-kafka (https://github.com/zendesk/ruby-kafka/commit/21ba7a92f0754d48ada8b410649e7c48a476cb4f) parameter `sasl_over_ssl` is mandatory for connection without ssl.
This parameter would be needed for projects working on karafka 1.2
> Add support for parameter sasl_over_ssl in ruby-kafka

- .travis.yml
- CHANGELOG.md
- config/errors.yml
- lib/karafka.rb
- lib/karafka/app.rb
- lib/karafka/connection/batch_delegator.rb
- lib/karafka/connection/listener.rb
- lib/karafka/connection/message_delegator.rb
- lib/karafka/instrumentation/monitor.rb
- lib/karafka/patches/ruby_kafka.rb
- lib/karafka/persistence/consumers.rb
- lib/karafka/persistence/topic.rb
- lib/karafka/persistence/topics.rb
- lib/karafka/routing/builder.rb
- lib/karafka/schemas.rb
- lib/karafka/schemas/responder_usage.rb
- spec/lib/karafka/app_spec.rb
- spec/lib/karafka/connection/batch_delegator_spec.rb
- spec/lib/karafka/connection/message_delegator_spec.rb
- spec/lib/karafka/patches/ruby_kafka_spec.rb
- spec/lib/karafka/persistence/consumers_spec.rb
- spec/lib/karafka/persistence/topics_spec.rb
- spec/lib/karafka/routing/builder_spec.rb
close https://github.com/karafka/karafka/issues/492
This PR adds option to reload and redraw all the cached mappings and objects to support hot code reload in development.
It should work both with Zeitwerk and Rails as it does not reload framework code, just the invalidates caches so things are recreated.
Limitations:
-  During the redraw, if new topics are present, they won't be included.
- All the multi batch long running operations will be invalidated when the code is reloaded (to be expected but still worth mentioning).
> Hot code reload

- lib/karafka/params/params.rb
- lib/karafka/serialization/json/deserializer.rb
- spec/lib/karafka/params/params_spec.rb
- spec/lib/karafka/serialization/json/deserializer_spec.rb
I played with 1.3 version and found an interesting case for improvement. Now we can use headers. I played with avro and you told me that it's good to put event type and version (for schema-registry) to the headers of kafka message.
And with it I'll be happy to use deserializer like this:
```ruby
module Parsers
class AvroParser
REGESTRY_URL = 'http://localhost:8081/'
attr_reader :avro
def initialize
@avro = AvroTurf::Messaging.new(registry_url: REGESTRY_URL)
end
def call(content, subject: '', version: 1)
avro.decode(content, subject: subject, version: version)
end
end
end
```
In this case, I can decode the message by subject and version and get decoded payload for in consumer block. Also, it will provide me to use dry-struct for mapping payload to struct object, like this:
```ruby
def …
```
> Allow to use headers in the deserializer object

- lib/karafka/attributes_map.rb
- lib/karafka/contracts/server_cli_options.rb
A couple of small tweaks that make it work with dry-configurable `0.11.0` as well as previous versions.
> dry-configurable upgrade

- CHANGELOG.md
- lib/karafka/server.rb
close https://github.com/karafka/karafka/issues/578
bypass for: https://github.com/dry-rb/dry-configurable/issues/93
I didn't update specs as I don't have an idea of how to stub a trap context. I consider that worthless as I expect `dry-configurable` to be fixed instead. I've checked with our dummy app.
> #578 - patch for dry-configurable trap context error

- lib/karafka/cli.rb
- lib/karafka/cli/flow.rb
- lib/karafka/cli/info.rb
- spec/lib/karafka/cli/flow_spec.rb
- spec/lib/karafka/cli/info_spec.rb
Swap `puts` with `Karafka.logger`. Fixes https://github.com/karafka/karafka/issues/583
Plain logging still look nice:
```log
2020-04-17 12:05:31.985611 I [14392:70280042062320] KarafkaApp -- Initializing Karafka server 14392
2020-04-17 12:05:32.010163 I [14392:70280341057040] KarafkaApp -- Karafka version: 1.3.5
Ruby version: 2.5.5
Ruby-kafka version: 0.7.10
Application client id: giorgio
Backend: inline
Batch fetching: false
Batch consuming: false
Boot file: /Users/serj/Projects/toptal/giorgio/karafka.rb
Environment: development
Kafka seed brokers: ["kafka://localhost:9092"]
```
And with JSON logging:
```
bundle exec karafka server | jq
```
```json
{
"host": "cube.local",
"application": "App",
"environment": "development",
"timestamp": "2020-04-17T09:08:56.131481Z",
"level": "info", …
```
> Direct CLI output to the logger

- CHANGELOG.md
- lib/karafka/connection/api_adapter.rb
- lib/karafka/connection/builder.rb
- lib/karafka/connection/client.rb
- spec/lib/karafka/connection/api_adapter_spec.rb
- spec/lib/karafka/connection/builder_spec.rb
Fixes https://github.com/karafka/karafka/issues/582
Longer description:
The Kafka client settings were not populated down to the client but taken from the "global" settings. This was an unnoticed bug as it affected only the subset of client settings. Since each consumer group is anyhow built based on per consumer group settings OR (if not defined) based on the defaults, this fetches the proper settings directly from the consumer group object, ensuring, that the settings are always the one "closest" to the consumer group.
> #582 - Fix for not being able to define seed_brokers on a per consumer_group basis

- CHANGELOG.md
Support for exponential backoff in pause was not added until 1.3.0
> Fix CHANGELOG.md inaccuracy WRT exp backoff

- lib/karafka/consumers/single_params.rb
- lib/karafka/params/params.rb
- spec/lib/karafka/consumers/single_params_spec.rb
- spec/lib/karafka/params/builders/params_spec.rb
- spec/lib/karafka/params/params_batch_spec.rb
Fixes https://github.com/karafka/karafka/issues/598
~~However, it introduces another inconsistency: now `params['payload']` would return the payload without a deserialization attempt. @mensfeld please take a look, I'm not sure if this approach is valid or there is a better way.
If this **is** the way, probably we should override `Karafka::Params::Params#[]` to remove the inconsistency described above?~~
We decided to override `Hash#[]` method to remove any inconsistencies in payload access.
The small benchmark made shows there is no significant performance penalty in such an approach.
> Allow metadata access without deserialization attempt

- lib/karafka/instrumentation/logger.rb
In case of passed read-only path as log_pass, `FileUtils.mkdir_p` raises `Errno::EROFS`.
That's a not target of the rescue clause, so cause unexpected behavior.
In my environment (macOS Big Sur 11.2.1), `bundle exec rspec` failed below error.
[![Image from Gyazo](https://i.gyazo.com/77ad7b9d80f35c34f3e5d025d8dea4dd.png)](https://gyazo.com/77ad7b9d80f35c34f3e5d025d8dea4dd)
https://developer.apple.com/forums/thread/650016
> The system volume is now read-only so you should seek to avoid modifying system files.
> Rescue Errno::EROFS in ensure_dir_exists

- README.md
- replace Travis CI links with GitHub Actions ones
> Update CI links in README.md

- lib/karafka/cli/install.rb
- spec/lib/karafka/cli/install_spec.rb
`rails` is just a meta-gem with a bunch of dependencies, all the Rails stuff can be installed without it and depends on `railties`.
> Change `rails?` check to  `railties` gem

- CHANGELOG.md
- Gemfile.lock
- karafka.gemspec
We are trying to use Karafka with an application that uses an old version of rake. After analyzing the commits, I realized that rake is no longer used by this project but the dependency is still present in the gemspec. 
This pull request removes the dependency.
> Remove rake dependency

- lib/karafka/instrumentation/logger.rb
- spec/lib/karafka/instrumentation/logger_spec.rb
This was partially fixed in #651, but we're still raising if log directory is writable/exists, but logfile is not.
Consolidate file-creation stuff and handle errors in the single place.
> Fixup logger checks for non-writeable logfile

- CHANGELOG.md
- lib/karafka/instrumentation/stdout_listener.rb
- spec/lib/karafka/instrumentation/stdout_listener_spec.rb
This PR updates the message that is printed with stdout logger when booting the framework.
The previous message was misleading for Ruby on Rails users. Users would think that when booting the framework a karafka process starts, while it was not true. Booting just bootstraps the framework components when executed outside of the server process.
close: https://github.com/karafka/karafka/issues/689
> #689 - update initialization message

- lib/karafka/cli/install.rb
The current generator does not recognize having just 'rails' in Gemfile, and generates the non-rails app class.
With this change, it supports either 'railties' (for piecemeal dependency) or 'rails' (for all-in).
> Allow 'rails' in Gemfile to enable rails-aware generator

- lib/karafka/messages/messages.rb
- spec/integrations/consumption_with_long_living_buffer.rb
- spec/lib/karafka/messages/messages_spec.rb
This PR provides a `#raw_payloads` method on the messages batch and adds additional integrations spec.
> #raw_payloads on batches

- lib/karafka/connection/client.rb
- lib/karafka/patches/rdkafka/consumer.rb
- spec/lib/karafka/connection/client_spec.rb
This PR matches the waterdrop `producer#name` with `consumer#name` patch as well as aliases that to the consumer client instance.
> introduce consumer and client name

- Gemfile.lock
- karafka.gemspec
- lib/karafka/instrumentation.rb
- spec/lib/karafka/instrumentation_spec.rb
This PR introduces hooks to callbacks managers from WaterDrop for further usage.
> Instrumentation callback hooks

- docker-compose.yml
- lib/karafka/server.rb
- spec/integrations/consumption/constant_error_should_not_clog_others.rb
- spec/integrations/consumption/of_many_partitions_with_error.rb
- spec/integrations/consumption/of_many_partitions_with_many_workers.rb
This pr removes unused docker compose kafka topics and renames topics to inform that they are of integrations suite nature.
> Remove unused compose topics

- docker-compose.yml
- lib/karafka/connection/listener.rb
- lib/karafka/instrumentation/stdout_listener.rb
- lib/karafka/runner.rb
- lib/karafka/server.rb
- lib/karafka/setup/config.rb
- lib/karafka/status.rb
- spec/integrations/consumption/constant_error_should_not_clog_others.rb
- spec/integrations/consumption/of_many_partitions_with_error.rb
- spec/integrations/consumption/of_many_partitions_with_many_workers.rb
- spec/integrations/consumption/simple_from_earliest.rb
- spec/integrations/consumption/time_bound_consumption.rb
- spec/lib/karafka/instrumentation/stdout_listener_spec.rb
- spec/lib/karafka/runner_spec.rb
- spec/lib/karafka/server_spec.rb
- spec/lib/karafka/status_spec.rb
- spec/spec_helper.rb
This PR improves the stopping process by introducing `stopped` status that indicates to the server that all the components were closed and that we can safely stop.
> more reliable server stopping

- bin/stress
- lib/karafka/processing/jobs_queue.rb
- lib/karafka/processing/worker.rb
- spec/integrations/consumption/two_consumer_groups_same_topic.rb
- spec/lib/karafka/processing/jobs_queue_spec.rb
This PR changes how we skip listener thread execution and pass it to workers. Previous approach would `Thread.pass` effectively running upon each scheduler switch just to pass it. The new approach blocks with a queues (one per group) until it is unblocked when needed. This effectively reduces context switching from 200k switches to listener to just over 200. (99% reduction).
Since we always wait on all the workers work to be done both on polling and shutdown, we can do it that way.
inspired by @ioquatix <3
> optimize context switching in the jobs queue

- docker-compose.yml
- lib/karafka/connection/listener.rb
- spec/integrations/consumption/on_partition_data_revoked.rb
This PR:
- adds a spec for a case when we lose a partition due to rebalance
- fixes a case where after a rebalance we would receive data for the partition in which we at the moment process data and/or run revoking operations
close https://github.com/karafka/karafka/issues/753
> Partition revoked consumer action spec + fix

- bin/integrations
- config/errors.yml
- lib/karafka/connection/pauses_manager.rb
- lib/karafka/contracts/config.rb
- spec/integrations/consumption/rate_limited.rb
A PR to demonstrate and check, that rate-limiting using pause time could be implemented.
This PR includes also:
- a fix for config validator. We will always validate pause_max_timeout to make sure, we don't end up with invalid smaller max than the pause timeout (did this and didn't know what is happening)
- improvement in the integration suite runner: when spec fails, part of stdout is printed alongside stderr
You probably don't want to use this in production ;) but worth having as a POC on how to achieve it.
> rate limited integration spec + validator fix

- lib/karafka/cli/server.rb
- lib/karafka/contracts/base.rb
- lib/karafka/contracts/config.rb
- lib/karafka/contracts/consumer_group.rb
- lib/karafka/contracts/consumer_group_topic.rb
- lib/karafka/contracts/server_cli_options.rb
- lib/karafka/routing/builder.rb
- lib/karafka/setup/config.rb
- spec/lib/karafka/cli/server_spec.rb
- spec/lib/karafka/contracts/base_spec.rb
- spec/spec_helper.rb
This PR similar to WaterDrop introduces a common contract base
Since we don't run contracts often (only on start) no need to cache them.
Note: had to lower code coverage requirement as with this refactor there is less code and we were right on the threshold.
> common contracts base

- CHANGELOG.md
- karafka.gemspec
We are officially dropping support for ruby 2.6 because maintenance ends beginning of April 2022. More information in this post https://www.ruby-lang.org/en/news/2021/11/24/ruby-2-6-9-released/. We also can't support JRuby because it is currently based on ruby 2.6.
> drop support for ruby 2.6

- CHANGELOG.md
- Require `kafka` keys to be symbols
> v2.0.0-alpha2 release

- spec/integrations/consumption/single_message_consumer.rb
This spec illustrates (and tests) how can we provide support for 1.4 style of "per message" consumption.
close https://github.com/karafka/karafka/issues/791
> Single message consumption mode integration spec for 2.0

- lib/karafka/instrumentation/monitor.rb
- lib/karafka/setup/config.rb
- lib/karafka/status.rb
- spec/integrations/instrumentation/app_status_lifecycle_flow.rb
- spec/lib/karafka/status_spec.rb
This PR restores the app.initialized state change and adds integration tests to ensure states changes flow order
> support initialized state and add integration for states flow

- CHANGELOG.md
- lib/karafka/base_consumer.rb
- lib/karafka/instrumentation/monitor.rb
- spec/integrations/instrumentation/consumption_event_vs_processing.rb
- spec/lib/karafka/base_consumer_spec.rb
This PR:
- renames `consumer.consume` event to `consumer.consumed`
- ensures that offset management is part of instrumentation during consumption
- adds a spec to count events and messages produced
> renamed event and consumption event integration spec

- CHANGELOG.md
- lib/karafka/railtie.rb
- spec/integrations/rails/rails6/just-a-dependency/Gemfile
- spec/integrations/rails/rails6/just-a-dependency/rails_setup.rb
- spec/integrations/rails/rails7/just-a-dependency/Gemfile
- spec/integrations/rails/rails7/just-a-dependency/rails_setup.rb
- spec/integrations/rails/rails7/without-active_job/railtie_setup.rb
- spec/integrations/rails/rails7/without-active_job_rspec/rspec_rails_setup.rb
Karafka should not fail, when it is just a dependency. In case like this `KARAFKA_BOOT_FILE` should be set to `"false"` string
close: https://github.com/karafka/karafka/issues/817
> do not fail when not first class citizen

- lib/karafka/processing/jobs_queue.rb
- spec/lib/karafka/processing/jobs_queue_spec.rb
This PR:
- changes how we track jobs in the jobs queue by collecting the actual jobs not their ids
- adds a `#tick` internal API that will cause a wait lock recheck
close https://github.com/karafka/karafka/issues/841
> Track jobs not their ids in jobs queue

- lib/karafka/processing/jobs/base.rb
- lib/karafka/processing/jobs_queue.rb
- lib/karafka/processing/worker.rb
- spec/lib/karafka/processing/jobs/base_spec.rb
- spec/lib/karafka/processing/jobs_queue_spec.rb
- spec/lib/karafka/processing/worker_spec.rb
This PR introduces notion of non blocking jobs as well as per-job lifecycle methods that can be used to prepare things needed for the async jobs to run safely.
> Introduce notion of non-blocking jobs

- lib/karafka/processing/executor.rb
- lib/karafka/processing/jobs/consume.rb
- spec/lib/karafka/processing/executor_spec.rb
- spec/lib/karafka/processing/jobs/consume_spec.rb
This PR moves the preparation of the consumer in the executor to the `#prepare` step to align with the lifecycle methods flow.
> move consumer preparation to prepare

- CHANGELOG.md
- lib/karafka/base_consumer.rb
- lib/karafka/instrumentation/monitor.rb
- lib/karafka/processing/executor.rb
- spec/integrations/consumption/with_prepared_method.rb
- spec/lib/karafka/base_consumer_spec.rb
- spec/lib/karafka/processing/executor_spec.rb
This PR adds proper lifecycle method to the consumer and runs it via the executor + specs and integrations to make sure it is executed.
> Add prepare hook to consumer and run it via executor

- lib/karafka/processing/jobs/base.rb
- spec/lib/karafka/processing/jobs/base_spec.rb
- spec/lib/karafka/processing/jobs/consume_spec.rb
- spec/lib/karafka/processing/jobs/revoked_spec.rb
- spec/lib/karafka/processing/jobs/shutdown_spec.rb
Job should not be able to change its own state. Each job should "decide" on whether it is blocking or now. For now all the jobs are blocking.
> Disallow job state change

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/processing/executors_buffer.rb
- lib/karafka/routing/consumer_group.rb
- lib/karafka/routing/subscription_group.rb
- lib/karafka/routing/subscription_groups_builder.rb
- lib/karafka/routing/topics.rb
- lib/karafka/version.rb
- spec/lib/karafka/routing/topics_spec.rb
This PR abstracts away the notion of topic groups. So far it was a simple array, but now for the simplicity and future development of virtual partitions, it makes sense to abstract this away.
It was the last non-abstract karafka routing component.
> Abstract away notion of topics groups

- lib/karafka/connection/listener.rb
- lib/karafka/connection/messages_buffer.rb
- lib/karafka/scheduler.rb
- spec/lib/karafka/connection/messages_buffer_spec.rb
- spec/lib/karafka/scheduler_spec.rb
- spec/support/factories/messages/message.rb
This PR updates the scheduler API to work with the jobs array instead of directly with messages. That way we can actually reorder jobs even if they come from same partition to make sure that in case of parallel processing we enqueue in good order (for other schedulers).
> Make scheduler work with jobs instead of messages

- CHANGELOG.md
- lib/karafka/connection/listener.rb
- lib/karafka/pro/scheduler.rb
- lib/karafka/scheduler.rb
- spec/lib/karafka/pro/scheduler_spec.rb
- spec/lib/karafka/scheduler_spec.rb
This PR:
- moves away all the jobs scheduling to schedulers removing this semi-layer in between listeners and schedulers, where listeners would actually schedule the jobs
- provides support for shutdown and revocation jobs to be scheduled as well
> Move all jobs scheduling to schedulers

- CHANGELOG.md
- lib/karafka/connection/listener.rb
- lib/karafka/connection/listeners_batch.rb
- lib/karafka/helpers/async.rb
- lib/karafka/pro/scheduler.rb
- lib/karafka/processing/executors_buffer.rb
- lib/karafka/processing/jobs_queue.rb
- lib/karafka/processing/worker.rb
- lib/karafka/processing/workers_batch.rb
- lib/karafka/runner.rb
- lib/karafka/scheduler.rb
- lib/karafka/server.rb
- lib/karafka/setup/config.rb
- spec/integrations/shutdown/shutdown_jobs_threads_processing.rb
- spec/lib/karafka/connection/listener_spec.rb
- spec/lib/karafka/connection/listeners_batch_spec.rb
- spec/lib/karafka/helpers/async_spec.rb
- spec/lib/karafka/pro/scheduler_spec.rb
- spec/lib/karafka/processing/executors_buffer_spec.rb
- spec/lib/karafka/processing/jobs_queue_spec.rb
- spec/lib/karafka/processing/worker_spec.rb
- spec/lib/karafka/processing/workers_batch_spec.rb
- spec/lib/karafka/runner_spec.rb
- spec/lib/karafka/scheduler_spec.rb
- spec/lib/karafka/server_spec.rb
This PR moves the queue closing process to the runner. That way:
- we do not attempt to close jobs queue from multiple listeners (in the multi-consumer group scenario)
- we ensure that all the work in listeners is done so no new jobs will be enqueued
- we ensure that we will not reach `max.poll.timeout` for non-blocking jobs that are running during shutdown
It also:
- Moves shutdown supervision to a separate thread not to run it in a trap context
- Makes listeners self-sufficient like workers
- Makes the runner only run the code not do stuff with threads
- Introduces the notion of ListenersBatch similar WorkersBatch to abstract the design better
- aligns some internal naming conventions
**No** external apis are changed.
> Optimize jobs queue shutdown and make listeners self-sufficient

- CHANGELOG.md
- lib/karafka/connection/listener.rb
- lib/karafka/processing/jobs_queue.rb
- spec/integrations/rebalancing/without_using_revoked_partition_data.rb
- spec/integrations/shutdown/shutdown_jobs_exceeding_max_poll_interval.rb
This PR slightly changes how we run shutdown process.
We do an active polling shutdown not to be kicked out from the consumer group. This allows us to have active connection to kafka to finalize anything we would need.
This PR adds also a spec for it.
> introduce polling wait for shutdown + specs

- lib/karafka/pro/active_job/consumer.rb
- lib/karafka/pro/active_job/dispatcher.rb
- lib/karafka/pro/loader.rb
- lib/karafka/pro/processing/jobs/consume_non_blocking.rb
- lib/karafka/processing/jobs/base.rb
- spec/integrations/pausing/with_manual_pause_and_other_partitions_working.rb
- spec/integrations/pro/licensing/configure_with_expired_token.rb
- spec/integrations/pro/licensing/configure_with_invalid_token.rb
- spec/integrations/pro/licensing/configure_with_valid_token.rb
- spec/integrations/pro/rails/active_job/async_job_processing.rb
- spec/integrations/pro/rails/active_job/sync_job_processing.rb
- spec/lib/karafka/pro/active_job/consumer_spec.rb
- spec/lib/karafka/pro/processing/jobs/consume_non_blocking_spec.rb
This PR adds pro activejob consumer. For now it does not provide any extra functionalities but it is needed for further development.
it also adds a non-blocking consumption job type for future usage.
> Use PRO ActiveJob consumer in PRO mode

- spec/integrations/pausing/pausing_with_message_skip.rb
- spec/integrations/pausing/seeking_offset_after_pausing.rb
This PR adds two additional cases for integration specs that ensure we can run certain operations during pause.
> pausing with message skip and seeking during pause

- CHANGELOG.md
- lib/karafka/connection/listener.rb
- lib/karafka/instrumentation/logger_listener.rb
- lib/karafka/instrumentation/monitor.rb
- lib/karafka/processing/worker.rb
- spec/lib/karafka/instrumentation/logger_listener_spec.rb
This PR improves the logger listener and introduces basic worker job processing related notifications.
They look much better now:
```
I, [timestamp]  INFO -- : [fa5110b8ce54] Consume job for Consumer on 423902f0ab78 started
I, [timestamp]  INFO -- : [019a1adb4686] Consume job for Consumer on 4f63a8fa8689 started
I, [timestamp]  INFO -- : [4f589b9420ee] Consume job for Consumer on 45bc0010a12f started
I, [timestamp]  INFO -- : [f943b327d13b] Consume job for Consumer on 45bc0010a12f finished in 100ms
I, [timestamp]  INFO -- : [4e80018b600f] Consume job for Consumer on 423902f0ab78 finished in 101ms
I, [timestamp]  INFO -- : [0c8bd915f7f4] Consume job for Consumer on 4f63a8fa8689 finished in 100ms
```
> Improve logger listener and introduce workers related notifications

- .github/workflows/ci.yml
- CHANGELOG.md
- Gemfile.lock
- lib/karafka/base_consumer.rb
- lib/karafka/connection/client.rb
- lib/karafka/pro/base_consumer.rb
- lib/karafka/version.rb
- spec/integrations/pro/consumption/lrj_with_auto_offset_management.rb
- spec/integrations/pro/rebalancing/lrj_rebalance_consumer_recreation.rb
This PR:
- improves specs stability by restoring bundle install outside of the GH action (no idea why but sometimes bundler claims it cannot find packages without it)
- improves another spec stability by ensuring we do not consume too much too fast so another consumer does not hang waiting on nothing
- resume paused partitions even if we lost them. That way when reclaiming, we will continue to process.
> Improve specs stability + always resume paused partitions on revocation

- .github/workflows/ci.yml
This bundler cache in the action causes weird errors. I reported that to bundler team but for now need to reverse this cache.
> Remove bundler cache from the CI

- bin/integrations
Fix invalid read of the error buffer that would cause it to hang if empty
> read nonblock data from error buffer

- lib/karafka/base_consumer.rb
- lib/karafka/pro/base_consumer.rb
- spec/integrations/offset_management/with_sync_marking.rb
This PR adds additional spec and aligns the coordinator referencing style. No changes to the logic whatsoever.
> use method reference to coordinator

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- karafka.gemspec
- lib/karafka.rb
- lib/karafka/setup/config.rb
- spec/lib/karafka/licenser_spec.rb
- spec/lib/karafka/pro/loader_spec.rb
As part of removing gems that are fairly easy to replace (to lower the complexity of the supply chain), this PR removes dependency on dry-configurable.
No changes to the end user API needed.
> Remove dry configurable in favour of homebrew

- CHANGELOG.md
- lib/karafka/active_job/consumer.rb
- spec/integrations/rails/active_job/big_batch_shutdown_early_break.rb
This PR improves shutdown, not processing jobs that we would pick up after restart.
> Improve ActiveJob shutdown

- CHANGELOG.md
- lib/karafka/instrumentation/logger_listener.rb
- spec/lib/karafka/instrumentation/logger_listener_spec.rb
This will make logger more informative and without the extensive noise.
close https://github.com/karafka/karafka/issues/916
> Remove extensive messaging from default dev info logging level

- spec/lib/karafka/connection/listener_spec.rb
rdkafka client should always be closed after usage to prevent spec crashes
> close client after use in specs

- spec/integrations/consumption/of_messages_with_headers.rb
- spec/integrations/pro/consumption/virtual_partitions/with_parallel_errors.rb
This change adds one more check to make sure headers keys are strings.
ref https://github.com/appsignal/rdkafka-ruby/issues/204
> Check headers key format + add more specs

- docker-compose.yml
- spec/integrations/pro/consumption/virtual_partitions/distributing_work_randomly.rb
- spec/integrations/pro/consumption/virtual_partitions/distributing_work_using_message_keys.rb
This spec shows that we can partition messages using VP and message keys that were used to partition data via Kafka.
> Spec to show partitioning for VP based on message key and random

- CHANGELOG.md
- config/errors.yml
- docker-compose.yml
- lib/karafka/pro/active_job/dispatcher.rb
- lib/karafka/pro/active_job/job_options_contract.rb
- spec/integrations/pro/consumption/long_running_jobs/multiple_batches_processing.rb
- spec/integrations/pro/rails/active_job/ordered_jobs_with_key.rb
- spec/integrations/pro/rails/active_job/ordered_jobs_with_partition_key.rb
- spec/integrations/pro/rails/active_job/virtual_partitions/with_partitioning_using_key.rb
- spec/lib/karafka/pro/active_job/dispatcher_spec.rb
- spec/lib/karafka/pro/active_job/job_options_contract_spec.rb
This PR adds more integration specs and adds option to choose between `:key` and `:partition_key` for AJ partitioning.
> More specs and key option usage for Active Job

- README.md
- spec/integrations/pro/shutdown/long_running_jobs/stopping_awareness.rb
One more scenario to illustrate that when using LRJ we can use the app status detection to early exit the LRJ job.
> add lrj shutdown detection scenario

- lib/karafka/connection/listener.rb
- spec/integrations/consumption/reaching_max_messages_count.rb
- spec/integrations/consumption/reaching_max_wait_time.rb
- spec/integrations/consumption/with_lazy_payload_deserialization.rb
- spec/integrations/offset_management/messages_and_metadata_details.rb
- spec/integrations/offset_management/with_sync_marking.rb
- spec/integrations/pausing/pause_early_and_skip_via_marking.rb
- spec/integrations/pro/consumption/long_running_jobs/multiple_batches_processing.rb
- spec/integrations/pro/consumption/long_running_jobs/with_continuous_error.rb
- spec/integrations/pro/consumption/virtual_partitions/different_coordinator_different_partitions.rb
- spec/integrations/pro/consumption/virtual_partitions/distributing_work_randomly.rb
- spec/integrations/pro/consumption/virtual_partitions/distributing_work_using_message_keys.rb
- spec/integrations/pro/consumption/virtual_partitions/from_earliest.rb
- spec/integrations/pro/consumption/virtual_partitions/many_batches_same_key.rb
- spec/integrations/pro/consumption/virtual_partitions/many_distributed_batches_end_order.rb
- spec/integrations/pro/consumption/virtual_partitions/shared_coordinator.rb
- spec/integrations/pro/consumption/virtual_partitions/with_manual_offset_management.rb
- spec/integrations/pro/consumption/virtual_partitions/with_manual_offset_management_error.rb
- spec/integrations/pro/consumption/virtual_partitions/with_parallel_errors.rb
- spec/integrations/pro/rebalancing/long_running_jobs/constant_rebalance_continuity.rb
- spec/integrations/pro/rebalancing/long_running_jobs/coordinator_replacement_after_rebalance.rb
- spec/integrations/pro/rebalancing/long_running_jobs/revoke_continuity.rb
- spec/integrations/pro/rebalancing/long_running_jobs/revoked_detection.rb
- spec/integrations/pro/rebalancing/virtual_partitions/coordinator_replacement_after_rebalance.rb
- spec/integrations/pro/shutdown/virtual_partitions/shutdown_on_all_consumers.rb
- spec/integrations/rebalancing/constant_rebalance_continuity.rb
- spec/integrations/rebalancing/without_using_revoked_partition_data.rb
- spec/support/data_collector.rb
This PR optimizes specs message aggregation, removes resources from listeners upon shutdown and makes sure we close consumer in specs so GC won't go crazy.
> optimize specs and shutdown referenec removal

- CHANGELOG.md
- lib/karafka/pro/active_job/consumer.rb
- spec/integrations/pro/rails/active_job/virtual_partitions/with_error_on_next_job.rb
- spec/lib/karafka/pro/active_job/consumer_spec.rb
This PR skips marking as consumed when Active Job is used with VP due to VP limitations.
> Make Enhaned Active Job work with Virtual Partitions

- lib/karafka/connection/client.rb
This fixes theoretical case where subscription would kick in faster than callbacks assignment (never encountered).
> add callbacks prior to subscription

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/instrumentation/notifications.rb
- lib/karafka/processing/worker.rb
- lib/karafka/railtie.rb
- lib/karafka/version.rb
- spec/lib/karafka/processing/worker_spec.rb
This PR bypasses: https://github.com/rails/rails/issues/44183
It releases the thread ActiveRecord lock, so the reloader does not have to wait for it.
> Bypass reload! Rails lag

- CHANGELOG.md
- lib/karafka.rb
- lib/karafka/pro/loader.rb
- lib/karafka/railtie.rb
- spec/lib/karafka/time_trackers/poll_spec.rb
This PR fixes two issues:
- Too verbose Rails logger when used with logger broadcaster
- Not visible Pro components when discovered via Zeitwerk
> Pro loader and Rails logger dev verbose fixes

- CHANGELOG.md
Fixes the link to the "Build vs Buy" page in the wiki.
> Fix link to Pro Subscription wiki page

- CHANGELOG.md
- README.md
- bin/integrations
- lib/karafka/admin.rb
When CI is heavily utilized, Kafka reacts slowly, thus timeout extension.
This PR makes us re-query Kafka to make sure topic exists instead of relying on the wait that sometimes hangs.
close https://github.com/karafka/karafka/issues/964
> increase timeout for admin operations

- CHANGELOG.md
- Fix hanging topic creation (#964)
- Fix conflict with other Rails loading libraries like `gruf` (#974)
> v2.0.4 release

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/base_consumer.rb
- lib/karafka/pro/base_consumer.rb
- lib/karafka/version.rb
- spec/integrations/pausing/with_pause_and_resume_after_reclaim.rb
- spec/integrations/pro/rebalancing/revoke_continuity.rb
- spec/integrations/pro/rebalancing/virtual_partitions/rebalance_continuity.rb
- spec/integrations/pro/rebalancing/with_static_membership_reconnect.rb
close https://github.com/karafka/karafka/issues/988
This spec also adds an integration case for this case.
We do not run this for LRJ as LRJ will automatically resume after finishing (via resume when success or short pause when failed)
> Fix a indefinite manual pause after rebalance

- CHANGELOG.md
- bin/integrations
- spec/integrations/pro/rebalancing/long_running_jobs/continuity_after_error_and_rebalance.rb
- spec/integrations_helper.rb
- spec/lib/karafka/time_trackers/pause_spec.rb
This PR extends sleep in one of the specs to compensate for its instability.
GH CI runners are shared and it seems their CPU is not stable when doing heavy parallel work, thus values are lowered.
> Extended sleep in one of the specs

- CHANGELOG.md
- lib/karafka/connection/client.rb
This PR moves check on client being closed to a mutex. This ensures we do not close twice on forceful shutdown.
> Improve potential double closing edge case

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/base_consumer.rb
- lib/karafka/connection/listener.rb
- lib/karafka/messages/builders/batch_metadata.rb
- lib/karafka/messages/builders/messages.rb
- lib/karafka/pro/base_consumer.rb
- lib/karafka/pro/processing/coordinator.rb
- lib/karafka/pro/processing/jobs/consume_non_blocking.rb
- lib/karafka/processing/executor.rb
- lib/karafka/processing/jobs/base.rb
- lib/karafka/processing/jobs/consume.rb
- lib/karafka/processing/worker.rb
- lib/karafka/version.rb
- spec/integrations/lags/processing_not_enough_threads.rb
- spec/integrations/pro/consumption/long_running_jobs/no_revocation_on_low_concurrency.rb
- spec/lib/karafka/messages/builders/batch_metadata_spec.rb
- spec/lib/karafka/pro/active_job/consumer_spec.rb
- spec/lib/karafka/pro/base_consumer_spec.rb
- spec/lib/karafka/pro/processing/coordinator_spec.rb
- spec/lib/karafka/pro/processing/jobs/consume_non_blocking_spec.rb
- spec/lib/karafka/processing/executor_spec.rb
- spec/lib/karafka/processing/jobs/consume_spec.rb
close https://github.com/karafka/karafka/issues/1002
This PR ensures that even when having multiple LRJ topics with multiple partitions in the same consumer group, they are not starved because of low concurrency. This could cause polling to be blocked.
No public API changes.
> Prevent multiple LRJ from blocking polling on pausing

- spec/integrations/consumption/many_topics_same_group.rb
- spec/lib/karafka/time_trackers/pause_spec.rb
This PR adds a scenario where we consume 100 topics and also refactors pause spec to make it CPU hangs insensitive.
> Multi-topic (100) consumption scenario with a single consumer group

- bin/integrations
Sending process kill after time exceeded means we do not have to deal with killing the thread. Without killing it, once the process is dead we will anyhow get the outcome value, and the exit code with details will be preserved.
It also prints better info upon failures.
> optimize specs supervision

- spec/integrations/pro/rails/active_job/virtual_partitions/from_earliest.rb
- spec/integrations/rebalancing/exceeding_max_poll_interval.rb
This PR improves one spec failing on a slow CI.
Karafka stop can be slow enough for one more poll to happen thus we need to compensate for it.
> Improve spec stability on a slow ci

- bin/integrations
- spec/integrations/pro/rebalancing/long_running_jobs/revoke_mark_as_consumed_sync_enough_threads.rb
This PR fixes an accidental bug where the spec executor would consider all specs as regular, running non-parallel in parallel.
this caused the:
https://github.com/karafka/karafka/actions/runs/3104736813/jobs/5029554905
> Fix integration spec type detection

- CHANGELOG.md
- lib/karafka/connection/client.rb
- spec/integrations/rebalancing/exceeding_max_poll_interval.rb
- spec/integrations_helper.rb
I gave it a second, though, and I think we need to make one change to the reporting of network / critical logic errors here:
while we can and should still retry them, on those errors, we should early notify them before retries. The reasoning is that network and other criticals indicate severe system problems, and max poll interval exceeding means severe business logic problems (slow processing).
This code does not change how the retry engine works but it provides early important errors notifications.
> Improve error notifications on key polling errors

- spec/integrations/rebalancing/multiple_consumer_groups_stability.rb
This specs ensures, that when there is a rebalance on one of the consumer groups, second is not affected by it.
> Multiple consumer group rebalance stability

- bin/integrations
- spec/integrations/rebalancing/exceeding_max_poll_with_late_commit_spec.rb
This PR improves the stability of one of the specs and increases CI concurrency (let's see if it will run faster).
This spec could fail (ref: https://github.com/karafka/karafka/actions/runs/3257845234/jobs/5349431095) in case we would fetch more than one message during initial poll, and this can happen.
> Compensate for first request unpredictability

- spec/integrations/pro/rails/active_job/virtual_partitions/with_partitioning_using_key_spec.rb
- spec/integrations/rebalancing/cooperative_sticky_full_spec.rb
- spec/integrations_helper.rb
This PR ensures that we always flush logs sync. This way when we extract details for error reporting, all the lines are always there.
> flush spec log sync and spec stability

- LICENSE
I'm not sure the mechanics of changing licenses. It may be that it would be preferable to rename the commercial license file instead.
Can you believe that people read the license? ;)
> Point to correct location of Commercial license

- lib/karafka/setup/attributes_map.rb
New `ssl.providers` attribute was introduced upstream in this change https://github.com/edenhill/librdkafka/commit/3709caa91391cb115848ef9946ad228aa56ea476
> add missing ssl.providers attribute

- CHANGELOG.md
- lib/karafka/pro/processing/strategies/dlq.rb
- spec/integrations/pro/consumption/strategies/aj_dlq_lrj_mom/with_non_recoverable_slow_jobs_error_spec.rb
- spec/integrations/pro/consumption/strategies/aj_dlq_mom/with_non_recoverable_job_error_spec.rb
- spec/integrations/pro/consumption/strategies/dlq/details_dispatch_transfer_spec.rb
- spec/integrations/pro/consumption/strategies/dlq/manual_dispatch_to_dlq_spec.rb
- spec/integrations/pro/consumption/strategies/dlq/multi_partition_source_target_flow_spec.rb
- spec/integrations/pro/consumption/strategies/dlq/original_offset_tracking_spec.rb
- spec/integrations/pro/consumption/strategies/dlq_lrj/fast_with_non_recoverable_errors_spec.rb
- spec/integrations/pro/consumption/strategies/dlq_lrj/with_non_recoverable_slow_error_spec.rb
- spec/integrations/pro/consumption/strategies/dlq_lrj_mom/with_non_recoverable_slow_no_marking_error_spec.rb
This PR replaces `-` with `_` in the headers details on the Pro DLQ dispatch.
> Fix unintentional headers naming

- .github/workflows/ci.yml
Caching the integrations spec bundler makes it impossible to install deps in integrations
> caching bundler breaks integrations

- CHANGELOG.md
- lib/karafka/app.rb
- lib/karafka/connection/consumer_group_status.rb
- lib/karafka/connection/listener.rb
- lib/karafka/connection/listeners_batch.rb
- lib/karafka/errors.rb
- spec/integrations/consumption/strategies/default/of_many_topics_with_different_settings_spec.rb
- spec/integrations/consumption/with_mixed_performance_in_subscription_group_spec.rb
- spec/integrations/routing/routing_with_anonymous_subscription_group_spec.rb
- spec/integrations/routing/routing_with_subscription_groups_arg_based_spec.rb
- spec/integrations/routing/routing_with_subscription_groups_block_based_spec.rb
- spec/lib/karafka/connection/consumer_group_status_spec.rb
- spec/lib/karafka/connection/listener_spec.rb
- spec/lib/karafka/connection/listeners_batch_spec.rb
- spec/lib/karafka/errors_spec.rb
- spec/lib/karafka/instrumentation/logger_listener_spec.rb
This PR optimizes shutdown of a single consumer group with subscription groups in which the processing performance varies.
close https://github.com/karafka/karafka/issues/1154
close https://github.com/karafka/karafka/issues/1148
> Optimize shutdown

- CHANGELOG.md
- lib/karafka/connection/listener.rb
- lib/karafka/pro/processing/coordinator.rb
- lib/karafka/processing/jobs_queue.rb
- spec/integrations/pro/consumption/strategies/lrj/starved_revocation_on_rebalance_spec.rb
This PR improves time needed for LRJ VP to switch to revoked and adds some extra concurrency security in the jobs queue.
> Optimized LRJ VP revoked awareness + small concurrency improvements

- CHANGELOG.md
- lib/karafka/connection/client.rb
- lib/karafka/pro/performance_tracker.rb
- lib/karafka/pro/processing/strategies/aj_dlq_mom.rb
- lib/karafka/pro/processing/strategies/dlq.rb
- lib/karafka/pro/processing/strategies/dlq_lrj.rb
- lib/karafka/pro/processing/strategies/dlq_lrj_mom.rb
- lib/karafka/pro/processing/strategies/dlq_mom.rb
- lib/karafka/processing/jobs_queue.rb
- lib/karafka/routing/features/dead_letter_queue/contract.rb
- lib/karafka/routing/features/dead_letter_queue/topic.rb
- spec/integrations/pro/consumption/strategies/aj_dlq_lrj_mom/without_dispatch_to_dlq_spec.rb
- spec/integrations/pro/consumption/strategies/dlq/without_dispatch_with_retries_spec.rb
- spec/integrations/pro/consumption/strategies/dlq/without_dispatch_without_retries_spec.rb
- spec/integrations/shutdown/on_hanging_listener_and_shutdown_spec.rb
- spec/integrations_helper.rb
- spec/lib/karafka/routing/features/dead_letter_queue/contract_spec.rb
- spec/support/data_collector.rb
This PR:
- adds the ability not to dispatch message to DLQ with DLQ enabled. This can be used to just silently ignore messages and continue.
- Fixes remaining concurrency issues.
close https://github.com/karafka/karafka/issues/1164
> 1164 skip messages on DLQ

- Gemfile.lock
- karafka.gemspec
This PR ensures that we use at least 2.0.4 karafka-core that has thread safety fixes.
> use 2.0.4 karafka-core

- lib/karafka/routing/builder.rb
- lib/karafka/routing/consumer_group.rb
- lib/karafka/routing/subscription_group.rb
- lib/karafka/routing/subscription_groups_builder.rb
- spec/integrations/routing/routing_with_subscription_groups_arg_based_spec.rb
- spec/integrations/routing/routing_with_subscription_groups_block_based_spec.rb
- spec/integrations/routing/routing_with_subscription_groups_chaotic_order_spec.rb
- spec/integrations/routing/stable_with_subscription_groups.rb
- spec/lib/karafka/routing/builder_spec.rb
- spec/lib/karafka/routing/subscription_group_spec.rb
- spec/lib/karafka/routing/subscription_groups_builder_spec.rb
- spec/support/factories/routing/subscription_group.rb
- spec/support/factories/routing/topic.rb
This PR makes the groups ids stable, that is consecutive usage of subscription groups should not increment the counter.
> Stabilize group ids

- spec/integrations/pro/consumption/strategies/lrj/saturated_before_revocation_spec.rb
This spec illustrates a case where full job queue can get extra work due to revocation and LRJ revocation jobs are blocking.
this may be changed with this: https://github.com/karafka/karafka/issues/1177 though for now its good to cover this case.
> illustrate lrj saturation

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/pro/processing/jobs/revoked_non_blocking.rb
- lib/karafka/pro/processing/jobs_builder.rb
- lib/karafka/version.rb
- spec/integrations/pro/consumption/strategies/lrj/saturated_before_revocation_spec.rb
- spec/lib/karafka/pro/processing/jobs/revoked_non_blocking_spec.rb
- spec/lib/karafka/pro/processing/jobs_builder_spec.rb
close https://github.com/karafka/karafka/issues/1177
blocked by https://github.com/karafka/karafka/pull/1178
will have to update the https://github.com/karafka/karafka/pull/1178 spec once merged and rebased.
> prevent lrj saturation on revocation

- lib/karafka/base_consumer.rb
- lib/karafka/pro/processing/strategies/default.rb
- lib/karafka/processing/strategies/base.rb
- lib/karafka/processing/strategies/default.rb
This PR moves the consume handler to strategies so we can customize this for LRJ and others when needed.
> Move consumption to strategies

- CHANGELOG.md
- lib/karafka/base_consumer.rb
- lib/karafka/instrumentation/logger_listener.rb
- spec/lib/karafka/instrumentation/logger_listener_spec.rb
This PR:
- connects previously added instrumentation into stdout listener
- adds the `#id` to consumers similar to other places
> add id to consumers and expand stdout listener

- CHANGELOG.md
- lib/karafka/instrumentation/notifications.rb
- lib/karafka/server.rb
- lib/karafka/status.rb
- spec/integrations/consumption/removing_a_topic_should_still_consume_rest_spec.rb
- spec/integrations/pro/rebalancing/with_static_membership_reconnect_spec.rb
- spec/integrations/rebalancing/with_static_membership_reconnect_spec.rb
- spec/integrations/rebalancing/without_using_revoked_partition_data_spec.rb
- spec/integrations_helper.rb
- spec/lib/karafka/server_spec.rb
- spec/lib/karafka/status_spec.rb
This PR introduces `terminated` state to differentiate between the stopped (no consumption, no connections via listeners, etc) and the last step, which is termination (exit).
The distinction is needed because we need to be able to instrument on stopped in the web UI and via listeners. `terminated` will run right after exit.
> Introduce terminated state

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/setup/config.rb
- spec/lib/karafka/setup/config_spec.rb
As discussed on Slack, that would be a more convenient default
> emit stats every 5 seconds by default

- CHANGELOG.md
- lib/karafka/railtie.rb
- lib/karafka/templates/karafka.rb.erb
This PR fixes a case where code reload would run with persisted consumers. Alongside of that it actually also fully disables the reload when persistence is on (no point)
close https://github.com/karafka/karafka/issues/1084
> Do not reload when consumer persistence on

- CHANGELOG.md
- bin/integrations
- lib/karafka/connection/consumer_group_coordinator.rb
- lib/karafka/connection/listener.rb
- lib/karafka/connection/listeners_batch.rb
- lib/karafka/instrumentation/logger_listener.rb
- lib/karafka/instrumentation/notifications.rb
- lib/karafka/server.rb
- lib/karafka/status.rb
- spec/integrations/shutdown/on_quiet_with_work_finalization_spec.rb
- spec/lib/karafka/connection/consumer_group_coordinator_spec.rb
- spec/lib/karafka/instrumentation/logger_listener_spec.rb
- spec/lib/karafka/server_spec.rb
- spec/lib/karafka/status_spec.rb
This PR introduces a new state of `quiet`. This state is the outcome of the quieting process and is reached when no more work is done in any consumer groups. This is the moment when we know we can safely shutdown.
> introduce quiet state

- CHANGELOG.md
- lib/karafka/admin.rb
- lib/karafka/routing/router.rb
- spec/lib/karafka/admin_spec.rb
- spec/lib/karafka/routing/router_spec.rb
This PR enhances the admin API by injecting the topic notion if possible to the `read_topic` admin API.
> include topic discovery in read_topic admin api

- CHANGELOG.md
- config/locales/errors.yml
- lib/karafka/app.rb
- lib/karafka/contracts/server_cli_options.rb
- lib/karafka/contracts/topic.rb
- lib/karafka/routing/topic.rb
- spec/integrations/routing/limited_scope/with_inactive_and_disabled_spec.rb
- spec/integrations/routing/limited_scope/with_mix_but_inactive_without_consumer_spec.rb
- spec/integrations/routing/limited_scope/with_only_inactive_topics_spec.rb
- spec/lib/karafka/contracts/topic_spec.rb
- spec/lib/karafka/routing/topic_spec.rb
This PR introduces ability to set `active false` for topics.
This will make them inactive (won't be consumed under `karafka s`) but will allow to define deserializer and use it with the admin API if needed because their resolutions via routing will be present.
> Inactive topics support

- CHANGELOG.md
- lib/karafka/connection/client.rb
- lib/karafka/instrumentation/logger_listener.rb
- lib/karafka/instrumentation/notifications.rb
- lib/karafka/routing/subscription_group.rb
- spec/integrations/instrumentation/pausing_and_retry_client_callbacks_spec.rb
- spec/integrations/routing/limited_scope/with_mix_but_inactive_without_consumer_spec.rb
- spec/integrations/setup/attributes_distribution_spec.rb
- spec/integrations_helper.rb
- spec/lib/karafka/instrumentation/logger_listener_spec.rb
- spec/lib/karafka/routing/subscription_group_spec.rb
This PR introduces `client.pause` and `client.resume` notification hooks. We cannot use a consumer instance action because pausing and resuming can be beyond a consumer instance lifecycle.
> better pause-resume instrumentation

- CHANGELOG.md
- lib/karafka.rb
- lib/karafka/routing/builder.rb
- lib/karafka/routing/consumer_group.rb
- lib/karafka/routing/subscription_group.rb
- spec/integrations/offset_management/rebalance_commit_spec.rb
This PR introduces a stable subscription groups instead of random. That way we can use them in the UI.
> Introduce stable subscription groups ids

- CHANGELOG.md
- lib/karafka/base_consumer.rb
- lib/karafka/instrumentation/notifications.rb
- lib/karafka/pro/processing/strategies/aj_lrj_mom_vp.rb
- lib/karafka/pro/processing/strategies/default.rb
- lib/karafka/pro/processing/strategies/lrj.rb
- lib/karafka/pro/processing/strategies/lrj_mom.rb
- lib/karafka/processing/strategies/base.rb
- lib/karafka/processing/strategies/default.rb
- lib/karafka/routing/consumer_mapper.rb
- spec/integrations/instrumentation/consumption_event_vs_processing_spec.rb
- spec/lib/karafka/base_consumer_spec.rb
- spec/lib/karafka/processing/strategies/base_spec.rb
This PR adds pre-execution instrumentation for consumer related actions and moves revocation and shutdown operations to strategies.
> Revoke and shutdown refactor

- CHANGELOG.md
- lib/karafka/process.rb
- spec/integrations/embedding/puma_poro/Gemfile
- spec/lib/karafka/process_spec.rb
This PR fixes a case where previous signal handlers would defined but would not be called because of Karafka intercept.
> Run previous signal handlers

- CHANGELOG.md
- Gemfile.lock
- karafka.gemspec
- lib/karafka/version.rb
Lets keep ruby version only in core as it's collective for the whole ecosystem (same will be applied to waterdrop)
> rely on shared core ruby version limitation

- CHANGELOG.md
- lib/karafka/pro/processing/strategies/dlq.rb
- spec/integrations/pro/consumption/strategies/dlq/multi_topic_one_target_multi_partitions_flow_spec.rb
This PR changes the DLQ dispatch key to make the distribution better in case of multi-partition single DLQ topic.
> better dlq keys strategy

- CHANGELOG.md
- lib/karafka/instrumentation/callbacks/error.rb
This PR adds a missing caller to make sure all error publishing locations have same api.
> ensure caller is published

- CHANGELOG.md
- bin/karafka
- lib/karafka/cli/base.rb
This PR moves the code loading from the karafka bin executable, so the same code can be used on the web to load code before install command execution.
> Extract cli loader command

- CHANGELOG.md
- config/locales/errors.yml
- lib/karafka/admin.rb
- lib/karafka/contracts.rb
- lib/karafka/contracts/consumer_group.rb
- lib/karafka/contracts/topic.rb
- spec/integrations/routing/with_namespace_collisions_spec.rb
- spec/lib/karafka/contracts/consumer_group_spec.rb
- spec/lib/karafka/contracts/topic_spec.rb
- spec/lib/karafka/routing/topic_spec.rb
- spec/spec_helper.rb
cd of https://github.com/karafka/karafka/issues/1300
this PR also increases wait timeout for admin operations as those would fail sometimes due to the cluster overload.
> Fix topic name validation (CandyFet)

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/connection/client.rb
- lib/karafka/time_trackers/poll.rb
- lib/karafka/version.rb
- spec/integrations/consumption/with_non_existing_topics_auto_create_spec.rb
- spec/integrations/consumption/with_non_existing_topics_no_auto_create_spec.rb
Improves how we handle non-critical errors.
- Do not include the sleep time in the internal poll time tracking (it would always run out after 1 or 2 attempts)
- Ignore `unknown_topic_or_part` when auto topic creation is on (as recommended by librdkafka authors)
Integration specs for this are included.
close https://github.com/karafka/karafka/issues/1310
> Improve non-critical error handling

- CHANGELOG.md
- config/locales/errors.yml
- lib/karafka/contracts/consumer_group.rb
- lib/karafka/contracts/topic.rb
- lib/karafka/setup/config.rb
- spec/integrations/routing/with_namespace_collisions_without_strict_spec.rb
- spec/lib/karafka/contracts/consumer_group_spec.rb
- spec/lib/karafka/contracts/topic_spec.rb
This PR introduces a config flag to disable strict topic naming validation.
@nijikon decided to introduce it at the root level not to introduce a new concept (setting namespaces) to the config. When we end up with more config settings we can decide to extract them to proper namespaces for routing, processing, etc similar to how it is done for internals.
close https://github.com/karafka/karafka/issues/1325
> Allow for disabling of strict_topics_namespacing validation

- CHANGELOG.md
- Gemfile.lock
- config/locales/errors.yml
- lib/active_job/queue_adapters/karafka_adapter.rb
- lib/karafka/active_job/dispatcher.rb
- lib/karafka/active_job/job_options_contract.rb
- lib/karafka/pro/active_job/dispatcher.rb
- lib/karafka/pro/active_job/job_options_contract.rb
- spec/lib/active_job/queue_adapters/karafka_adapter_spec.rb
- spec/lib/karafka/active_job/dispatcher_spec.rb
- spec/lib/karafka/active_job/job_options_contract_spec.rb
- spec/lib/karafka/pro/active_job/dispatcher_spec.rb
- spec/lib/karafka/pro/active_job/job_options_contract_spec.rb
We cannot add integration specs because Rails 7.1 is not yet released. Those will be added after Rails 7.1. Functionality is based on Sidekiq adapter code and tested with units.
close https://github.com/karafka/karafka/issues/1327
> Support Rails 7.1 batch AJ jobs

- spec/integrations/pro/consumption/strategies/vp/with_parallel_errors_spec.rb
This spec had a tendency to assign 9/10 partitions because of how uuids are generated. This normalizes that.
> improve spec stability

- CHANGELOG.md
- lib/karafka/pro/processing/strategies/aj_dlq_lrj_mom.rb
- spec/integrations/pro/consumption/strategies/aj_dlq_lrj_mom/regular_processing_one_by_one_without_errors_spec.rb
- spec/integrations/pro/consumption/strategies/aj_dlq_lrj_mom/with_recoverable_slow_jobs_error_spec.rb
- spec/integrations/pro/consumption/strategies/aj_dlq_lrj_mom_vp/regular_processing_one_by_one_without_errors_spec.rb
- spec/integrations/pro/consumption/strategies/aj_dlq_lrj_mom_vp/with_recoverable_slow_jobs_error_spec.rb
- spec/integrations/pro/consumption/strategies/aj_dlq_mom/regular_processing_one_by_one_without_errors_spec.rb
- spec/integrations/pro/consumption/strategies/aj_dlq_mom/with_recoverable_jobs_error_spec.rb
- spec/integrations/pro/consumption/strategies/aj_dlq_mom_vp/regular_processing_one_by_one_without_errors_spec.rb
- spec/integrations/pro/consumption/strategies/aj_dlq_mom_vp/with_recoverable_jobs_error_spec.rb
- spec/integrations/pro/consumption/strategies/dlq_lrj/regular_processing_one_by_one_without_errors_spec.rb
- spec/integrations/pro/consumption/strategies/dlq_lrj_mom/regular_processing_one_by_one_without_errors_spec.rb
- spec/integrations/pro/consumption/strategies/dlq_lrj_vp/regular_processing_one_by_one_without_errors_spec.rb
- spec/integrations/pro/consumption/strategies/dlq_mom/regular_processing_one_by_one_without_errors_spec.rb
- spec/integrations/pro/consumption/strategies/dlq_vp/regular_processing_one_by_one_without_errors_spec.rb
- spec/integrations/pro/consumption/strategies/lrj/regular_processing_one_by_one_without_errors_spec.rb
- spec/integrations/pro/consumption/strategies/lrj_vp/regular_processing_one_by_one_without_errors_spec.rb
- spec/integrations/pro/consumption/strategies/vp/regular_processing_one_by_one_without_errors_spec.rb
This PR:
- uses proper strategy for AJ + DLQ + MOM + LRJ combination that handles all the cases (same as for AJ + DLQ + MOM + LRJ + VP) - because from the outside, this is the same.
- adds regression integration spec to ALL potentially affected scenarios (other not affected but just to be sure in the future).
fix https://github.com/karafka/karafka/issues/1362
> Fix AJ + DLQ + MOM + LRJ is pausing indefinitely after the first job

- CHANGELOG.md
- lib/karafka/admin.rb
- spec/lib/karafka/admin_spec.rb
This PR aligns the name to match other admin actions to prefix operation with command (create / delete / update / read) etc. for consistency.
It's not a breaking change because was not released yet.
> Rename watermark_offsets method

- CHANGELOG.md
- lib/karafka/base_consumer.rb
- lib/karafka/processing/strategies/default.rb
- spec/integrations/pro/rails/active_job/virtual_partitions/with_revocation_spec.rb
- spec/lib/karafka/active_job/consumer_spec.rb
- spec/lib/karafka/base_consumer_spec.rb
Moving marking methods to strategies as their behaviour will differ in the future due to introduction of soft marking in virtual partitions.
> Move marking to strategies

- CHANGELOG.md
- lib/karafka/base_consumer.rb
- lib/karafka/pro/active_job/consumer.rb
- lib/karafka/pro/processing/strategies.rb
- lib/karafka/pro/processing/strategies/lrj/ftr_vp.rb
- lib/karafka/pro/processing/strategies/vp/default.rb
- lib/karafka/processing/coordinator.rb
- lib/karafka/processing/result.rb
- spec/integrations/consumption/with_branching_logic_on_retry.rb
- spec/integrations/pro/consumption/strategies/aj/dlq_lrj_mom_vp/with_non_recoverable_job_error_spec.rb
- spec/integrations/pro/consumption/strategies/aj/dlq_mom_vp/with_non_recoverable_job_error_spec.rb
- spec/integrations/pro/consumption/strategies/aj/mom_vp/no_execution_on_failing_saturated_spec.rb
- spec/integrations/pro/consumption/strategies/dlq/ftr/pipeline_with_delayed_dlq.rb
- spec/integrations/pro/consumption/strategies/lrj/ftr_mom/with_continuous_error_spec.rb
- spec/lib/karafka/pro/processing/strategies_spec.rb
This PR:
- adds few more examples inluding delayed DLQ example
- When using ActiveJob with Virtual Partitions, Karafka will stop if collectively VPs are failing. This minimizes number of jobs that will be collectively re-processed.
- `#retrying?` method has been added to consumers to provide ability to check, that we're reprocessing data after a failure. This is useful for branching out processing based on errors.
close https://github.com/karafka/karafka/issues/1402
> `#retrying?` and `#failing?` consumer API + specs

- CHANGELOG.md
- bin/integrations
This PR prints 10 slowests specs after suite is executed. Useful for future optimizations.
> Report ten slowest integration specs after execution

- CHANGELOG.md
- lib/karafka/instrumentation/callbacks/statistics.rb
- lib/karafka/instrumentation/logger_listener.rb
- spec/integrations/instrumentation/statistics_callback_with_crashing_subscription_spec.rb
- spec/integrations_helper.rb
- spec/lib/karafka/instrumentation/callbacks/statistics_spec.rb
- spec/lib/karafka/instrumentation/logger_listener_spec.rb
librdkafka crashes if upon statistics dispatch there is an error. This PR fixes that by handling this error via the standard errors bus.
close https://github.com/karafka/karafka/issues/1419
> Prevent deadlock on statistics crash

- CHANGELOG.md
- lib/karafka/pro/active_job/consumer.rb
- lib/karafka/pro/processing/coordinator.rb
- lib/karafka/pro/processing/filters/virtual_limiter.rb
- lib/karafka/pro/processing/filters_applier.rb
- lib/karafka/pro/processing/strategies/dlq/mom.rb
- lib/karafka/pro/processing/strategies/vp/default.rb
- lib/karafka/pro/processing/virtual_offset_manager.rb
- lib/karafka/processing/strategies/dlq_mom.rb
- spec/integrations/pro/consumption/strategies/aj/mom_vp/execution_on_failing_saturated_spec.rb
- spec/integrations/pro/consumption/strategies/dlq/mom/at_most_once_skipping_on_error_poll_one_spec.rb
- spec/integrations/pro/consumption/strategies/vp/collapse_with_intermediate_marking_filtering_spec.rb
- spec/integrations/pro/consumption/strategies/vp/continuous_retry_in_collabse_with_filtering_spec.rb
- spec/integrations/pro/consumption/strategies/vp/pre_work_marking_retry_continuity_spec.rb
- spec/integrations/pro/consumption/strategies/vp/with_soft_marking_partial_error_spec.rb
- spec/lib/karafka/pro/active_job/consumer_spec.rb
- spec/lib/karafka/pro/processing/filters/virtual_limiter_spec.rb
- spec/lib/karafka/pro/processing/strategies_spec.rb
- spec/lib/karafka/pro/processing/virtual_offset_manager_spec.rb
This PR adds virtual offset filtering and management.
It removes the last issue with VPs, where on retry and collapse, we would have to restart all the processing. After this PR, only failed messages will be retried.
close https://github.com/karafka/karafka/issues/1397
> Virtual Offset Filtering

- lib/karafka/base_consumer.rb
- spec/integrations/consumption/with_branching_logic_on_retry_spec.rb
Currently, `BaseConsumer#retrying?` never evaluates to false since `coordinator.pause_tracker.attempt` starts with 0 and gets incremented even during initial consumption [here](https://github.com/karafka/karafka/blob/625e33267cc21d675d30d5c219df128244233d33/lib/karafka/connection/listener.rb#L277), if I understand correctly.
The only spec that I could find that tests this helper is being silently ignored since its name does not end with `_spec`. If it were to run, it would result in a false positive since it does not assert that an error has happened.
Moreover, dangling descendant of `Exception` is never used in this test, and raising it would also not work, since as far I understand, Karafka recreates the listener when it encounters something that is not a descendant of `StandardError`. …
> Fix `#retrying?` helper, enable phantom test

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/messages/batch_metadata.rb
- lib/karafka/version.rb
- spec/integrations/pro/consumption/strategies/ftr/with_delayed_shutdown_metadata_lags_spec.rb
- spec/lib/karafka/messages/batch_metadata_spec.rb
Workless flows jobs tracking in Web-UI fails because of this. We use -1 similar to how we report "not available" offsets as those flows are mostly used for internal operations. While we may skip reporting them in web when no data, it is still worth fixing.
close https://github.com/karafka/karafka/issues/1475
> Fix consumption_lag and processing_lag references from workless flows

- CHANGELOG.md
- lib/karafka/base_consumer.rb
- lib/karafka/connection/client.rb
- lib/karafka/processing/strategies/default.rb
- spec/benchmarks/offset_management/async.rb
- spec/benchmarks/offset_management/revoked_checks.rb
- spec/benchmarks/offset_management/sync.rb
- spec/benchmarks_helper.rb
- spec/integrations/offset_management/commit_offset_after_exceeding_max_poll_spec.rb
A small change to optimize how the coordinator discovers the revocation state when using `#revoked?`
this PR also adds some new benchmarks
close https://github.com/karafka/karafka/issues/1492
> Optimize revocation switch change

- spec/integrations/consumption/standard_saturation_reliability_spec.rb
This spec illustrates that the OSS version runs post-revocation jobs when karafka is over-saturated.
Appropriate Pro spec is already there.
> OSS version saturation execution spec

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/admin.rb
- lib/karafka/pro/iterator/tpl_builder.rb
- lib/karafka/version.rb
- spec/integrations/pro/iterator/with_negative_bigger_than_available_data_spec.rb
This PR fixes an issue where upon negative offset selection (backwards lookup) we would compute an offset below the low watermark.
> Negative offset iterator lookup fix

- spec/integrations/pro/consumption/strategies/lrj/ftr/constant_reporting_lag_spec.rb
Simple spec to illustrate, that when processing the stored lag is impacted by the upcoming messages as well as current batch size and to ensure it does not go out of the expected range.
> Ensure stats stability for lrj

- spec/integrations/pro/consumption/strategies/vp/with_pause_on_collapsed_spec.rb
This PR tackles an edge case that rarely occurs where all messages were shipped in one go, so the karafka consumer stopped prior to pause restore causing the spec to fail.
ref https://github.com/karafka/karafka/actions/runs/5751096603/job/15589173788
> stabilize spec

- CHANGELOG.md
- lib/karafka/connection/client.rb
- lib/karafka/instrumentation/logger_listener.rb
- lib/karafka/instrumentation/notifications.rb
- spec/lib/karafka/instrumentation/logger_listener_spec.rb
Mitigates a case where a broker request for a subscription would start running the same moment we close the connection.
> Unsubscribe long-living consumer client on close

- spec/integrations/consumption/from_never_existing_topic_spec.rb
- spec/integrations/consumption/from_non_existing_topic_spec.rb
- spec/integrations/consumption/with_cluster_info_based_routes_spec.rb
- spec/integrations/routing/cluster_info_based_discovery_spec.rb
- spec/integrations/routing/runtime_routing_expansion_spec.rb
Some specs illustrating that while we do not support dynamic runtime subscriptions (yet), we do support subscriptions on process starts.
> cluster info based dynamic subscriptions

- CHANGELOG.md
- lib/karafka/admin.rb
From librdkafka:
> We do recommend that you set allow.auto.create.topics=false to avoid topic metadata lookups to unexpectedly have the broker create topics.
I never encountered that but better safe than sorry ;)
> Disable auto-topic-create for admin

- CHANGELOG.md
- config/locales/errors.yml
- lib/karafka/connection/proxy.rb
- lib/karafka/contracts/config.rb
- lib/karafka/setup/config.rb
- spec/lib/karafka/contracts/config_spec.rb
This PR extracts the constant timeouts and makes them customizable. It is part of mitigation of issues with certain kafka commands that tend to fail on a first try. There are few librdkafka issues where the solution (or a mitigation) is to retry. Alongside of that fixes in rdkafka-ruby are in place.
close https://github.com/karafka/karafka/issues/1552
> Customize retry and timeouts for proxy

- CHANGELOG.md
- Gemfile.lock
- spec/integrations/instrumentation/error_callback_multiple_subscription_groups_spec.rb
By default datadog will use the service name such as `myservice` which will be the same for web and karafka processes. 
However, it is beneficial to separate those and have  `myservice-karafka` as a separate service name. This allows setting different default operation in Datadog UI and makes analyzing traces much easier.
In https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/ruby/ you can find examples how every integration supports setting service name.
Tested manually in Datadog as well.
> Support changing service_name in datadog integration

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/instrumentation/vendors/datadog/logger_listener.rb
- lib/karafka/version.rb
- spec/integrations/instrumentation/vendors/datadog/logger_flow_spec.rb
- spec/support/vendors/datadog/logger_dummy_client.rb
* Support changing service_name in datadog integration
By default datadog will use the service name such as my-app which will be the same for web and karafka processes. 
However, it is beneficial to separate those and have  my-app-karafka as a separate service name. This allows setting different default operation in Datadog UI and makes analyzing traces much easier.
In https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/ruby/  you can find examples how every integration supports setting service name.
* delegate service_name to config
* Fix integration tests for datadog service name
---------
> Support changing service_name in datadog integration (#1576)

- CHANGELOG.md
- Gemfile.lock
- karafka.gemspec
- lib/karafka/pro/routing/features/patterns/pattern.rb
- lib/karafka/version.rb
- spec/integrations/pro/routing/patterns/anonymous_with_invalid_regexp_spec.rb
- spec/integrations/pro/routing/patterns/named_with_invalid_regexp_spec.rb
close https://github.com/karafka/karafka/issues/1596
also updates dep on karafka-core to 2.2.0
> 1596 - do not crash on non-regexp patterns prior to contracts validation

- spec/integrations/pausing/manual_pause_on_a_revoked_partition_spec.rb
A simple spec that checks that revoked pause does not affect reassigned consumption.
> spec for revoked paused usage

- docker-compose.yml
Since we've introduced locking on topics creation via flock it should not be a problem to get back to default time tick.
> use zookeeper timetick default

- CHANGELOG.md
- docker-compose.yml
- lib/karafka/admin.rb
- lib/karafka/errors.rb
This PR changes two things:
- KRaft for docker
- Ensure that the result of topic related admin operations is visible from the broker perspective before finishing
close https://github.com/karafka/karafka/issues/1633
> Change to kraft and validate cache state

- lib/karafka/instrumentation/vendors/datadog/logger_listener.rb
- spec/support/vendors/datadog/logger_dummy_client.rb
I have the following configuration that leverages a simple consumer from the example documents.
```
class KarafkaApp < Karafka::App
setup do |config|
config.kafka = { 'bootstrap.servers': '127.0.0.1:9092' }
config.client_id = 'example_app'
require 'karafka/instrumentation/vendors/datadog/logger_listener'
trace_listener = ::Karafka::Instrumentation::Vendors::Datadog::LoggerListener.new do |config|
config.client = Datadog::Tracing
end
config.monitor.subscribe(trace_listener)
end
```
This is the contents of my Gemfile
```
ruby '3.2.2'
gem 'ddtrace', '~> 1.0'
gem "karafka", ">= 2.2.0"
```
Running this consumer will yield the following FATAL error, causing the work process to fail.
>F, [2023-09-19T15:17:17.008201 #77740] FATAL -- : Worker processing failed due to an error: undefined method …
> use nil? instead of present? on DataDog::Tracing::SpanOperation

- .github/workflows/ci.yml
- bin/integrations
- spec/integrations/pro/consumption/strategies/ftr/static_throttler_spec.rb
- spec/integrations/pro/rails/rails6_pristine/Gemfile
- spec/integrations/pro/rails/rails6_pristine/railtie_setup_spec.rb
- spec/integrations/pro/rails/rails7_pristine/just_a_dependency/Gemfile
- spec/integrations/pro/rails/rails7_pristine/just_a_dependency/railtie_setup_spec.rb
- spec/integrations/pro/rails/rails7_pristine/with-active_job_and_current_attributes/Gemfile
- spec/integrations/rails/rails6_pristine/just-a-dependency/Gemfile
- spec/integrations/rails/rails6_pristine/with-active_job/Gemfile
- spec/integrations/rails/rails6_pristine/with-active_job/railtie_setup_spec.rb
- spec/integrations/rails/rails6_pristine/without-a-boot-file/Gemfile
- spec/integrations/rails/rails6_pristine/without-active_job/Gemfile
- spec/integrations/rails/rails6_pristine/without-active_job/railtie_setup_spec.rb
- spec/integrations/rails/rails6_pristine/without-active_job_rspec/Gemfile
- spec/integrations/rails/rails7_pristine/just-a-dependency/Gemfile
- spec/integrations/rails/rails7_pristine/with-active_job/Gemfile
- spec/integrations/rails/rails7_pristine/with-active_job/railtie_setup_spec.rb
- spec/integrations/rails/rails7_pristine/with-active_job_and_current_attributes/Gemfile
- spec/integrations/rails/rails7_pristine/without-active_job/Gemfile
- spec/integrations/rails/rails7_pristine/without-active_job/railtie_setup_spec.rb
- spec/integrations/rails/rails7_pristine/without-active_job_rspec/Gemfile
To make them run in parallel and not overload Kafka with crazy number of topics, etc on GH machines, this PR splits the work.
On top of that it retries (once) docker-compose in case it would fail. I've seen some docker API temporary errors that just go away with second run after backoff.
OSS integrations run now around 10 minutes
Pro around 25-30.
In total the parallel execution went down from 40-45 minutes in total to around 30m.
close https://github.com/karafka/karafka/issues/1573
superseeds: https://github.com/karafka/karafka/pull/1543
> Split integrations into OSS and Pro and retry Docker

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/admin.rb
- lib/karafka/version.rb
In this update, I've added a retry mechanism to the `Karafka::Admin#read_watermark_offsets` method. This enhancement addresses the `not_leader_for_partition` error that can often arise under two main scenarios:
- When topics are newly created in KRaft.
- Following unexpected crashes that happen during the leader selection phase.
The primary goal of this enhancement is to ensure that our system remains resilient and can recover gracefully in cases where the `not_leader_for_partition` error is encountered. By implementing this retry logic, I aim to provide a smoother and more reliable user experience, especially in the above mentioned scenarios.
ref https://github.com/appsignal/rdkafka-ruby/issues/289
> Retry watermark offsets reading for lack of leader of partition

- lib/karafka/connection/listener.rb
This PR renames the method to reflect better what it does. Lost partitions are partitions that will not be assigned back but this concept is not present on this layer. We always run revocation for revoked partitions even if they will be reassigned. We do it because we want to make sure, that new consumer instance will be initialized for this partition.
> Rename listener revoked method to better reflect what it does

- CHANGELOG.md
- config/locales/pro_errors.yml
- lib/karafka/base_consumer.rb
- lib/karafka/pro/processing/filters/inline_insights_delayer.rb
- lib/karafka/pro/routing/features/inline_insights.rb
- lib/karafka/pro/routing/features/inline_insights/config.rb
- lib/karafka/pro/routing/features/inline_insights/contracts/topic.rb
- lib/karafka/pro/routing/features/inline_insights/topic.rb
- spec/integrations/consumption/retrying_flow_spec.rb
- spec/integrations/pro/consumption/inline_insights/from_earliest_required_spec.rb
- spec/integrations/pro/consumption/inline_insights/from_earliest_spec.rb
- spec/integrations/pro/consumption/inline_insights/multi_topic_partition_spec.rb
- spec/integrations/pro/consumption/inline_insights/post_involuntary_revocation_spec.rb
- spec/integrations/pro/consumption/inline_insights/post_revocation_insights_lrj_spec.rb
- spec/integrations/pro/consumption/inline_insights/without_being_enabled_spec.rb
- spec/lib/karafka/base_consumer_spec.rb
- spec/lib/karafka/pro/processing/filters/inline_insights_delayer_spec.rb
- spec/lib/karafka/pro/routing/features/inline_insights/config_spec.rb
- spec/lib/karafka/pro/routing/features/inline_insights/contracts/topic_spec.rb
- spec/lib/karafka/pro/routing/features/inline_insights/topic_spec.rb
- spec/lib/karafka/pro/routing/features/inline_insights_spec.rb
this PR adds the auto-backoff filter in cases where insights would not be yet available to the consumer
> inline insights auto-delay

- CHANGELOG.md
- lib/karafka/pro/processing/coordinator.rb
- lib/karafka/pro/processing/strategies/vp/default.rb
- spec/integrations/pro/consumption/strategies/vp/pausing_concurrently_spec.rb
This PR introduces a cross-consumer synchronization API for VP consumers running on the same topic partition. It may ease some operations.
Additionally it adds spec to make sure that the last pause on multiple VPs is the one in use.
> Cross consumer synchronization API for VPs

- renovate.json
Renovate creates immortal PRs for updating from Rails 7 to Rails 7.1 etc where we want to test not the latest release but each that we support. Hence we need to exclude those from Renovate not to update them.
> Exclude specs from renovate

- .github/workflows/ci.yml
Automatically will cancel previous runs on pushes.
This saves a lot of minutes in CI especially in karafka.
> cancel previous runs

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/pro/processing/strategies/vp/default.rb
- lib/karafka/processing/coordinator.rb
- lib/karafka/version.rb
- spec/integrations/pro/consumption/strategies/vp/synchronized_with_marking_spec.rb
This PR moves the locking from the coordinator seek_offset to the VPs via the coordinator lock. This ensures that only one full marking (sync and async) can operate at the same time.
> Move the locking from coordinator to VPs

- CHANGELOG.md
- lib/karafka/cli/server.rb
- spec/lib/karafka/cli/help_spec.rb
- spec/lib/karafka/cli/server_spec.rb
close https://github.com/karafka/karafka/issues/1676
server is used everywhere so lets keep it but provide alias `karafka consumer` for ppl that want to be exact
> alias server as consumer in the CLI

- CHANGELOG.md
- Gemfile.lock
- config/locales/errors.yml
- karafka.gemspec
- lib/karafka/connection/client.rb
- lib/karafka/connection/listener.rb
- lib/karafka/contracts/config.rb
- lib/karafka/helpers/interval_runner.rb
- lib/karafka/processing/jobs_queue.rb
- lib/karafka/processing/timed_queue.rb
- lib/karafka/setup/config.rb
- lib/karafka/version.rb
- spec/integrations/instrumentation/statistics_publishing_on_long_poll_spec.rb
- spec/integrations/instrumentation/statistics_publishing_on_long_processing_spec.rb
- spec/integrations/pro/consumption/strategies/lrj/default/concurrent_operations_execution_spec.rb
- spec/lib/karafka/contracts/config_spec.rb
- spec/lib/karafka/helpers/interval_runner_spec.rb
- spec/lib/karafka/processing/timed_queue_spec.rb
This PR replaces a single queue based consumer client with one that handles consumer and other events independently + provides a tick engine for periodic checking also when locked during processing or long pollings.
It does NOT increase number of threads needed and performance impact should be neglectable.
This PR allows us to ensure we are publishing statistics more or less every 5 seconds and that they are updated despite processing state or any features usage.
> Provide time-reliable events polling

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/instrumentation/notifications.rb
- lib/karafka/pro/processing/strategies/default.rb
- lib/karafka/pro/processing/strategies/vp/default.rb
- lib/karafka/processing/strategies/default.rb
- lib/karafka/version.rb
- spec/integrations/instrumentation/before_enqueue_jobs_tracking_spec.rb
This PR adds instrumentation to the before enqueue event. Useful for monitoring work that will be saturated.
> Instrument before enqueue

- CHANGELOG.md
- lib/karafka.rb
- lib/karafka/routing/builder.rb
- lib/karafka/routing/subscription_group.rb
- spec/integrations/consumption/with_mixed_performance_in_subscription_group_spec.rb
- spec/integrations/pro/consumption/strategies/ftr/static_throttler_spec.rb
- spec/integrations/pro/consumption/strategies/vp/many_distributed_batches_end_order_spec.rb
- spec/integrations/rebalancing/on_partition_data_revoked_spec.rb
- spec/support/data_collector.rb
This PR removes part of the concurrent-ruby 
part of https://github.com/karafka/karafka/issues/1741
> Limit concurrent ruby usage

- CHANGELOG.md
- config/locales/errors.yml
- lib/karafka/connection/listener.rb
- lib/karafka/connection/listeners_batch.rb
- lib/karafka/contracts/config.rb
- lib/karafka/pro/loader.rb
- lib/karafka/pro/processing/jobs_queue.rb
- lib/karafka/pro/processing/scheduler.rb
- lib/karafka/processing/jobs_queue.rb
- lib/karafka/processing/scheduler.rb
- lib/karafka/runner.rb
- lib/karafka/setup/config.rb
- spec/integrations/pro/consumption/scheduling/with_single_thread_materialization_scheduler_spec.rb
- spec/integrations/pro/consumption/strategies/aj/dlq_ftr_lrj_mom_vp/with_non_recoverable_job_error_spec.rb
- spec/integrations/pro/licensing/configure_with_valid_token_spec.rb
- spec/lib/karafka/connection/listener_spec.rb
- spec/lib/karafka/connection/listeners_batch_spec.rb
- spec/lib/karafka/contracts/config_spec.rb
- spec/lib/karafka/pro/processing/jobs_queue_spec.rb
- spec/lib/karafka/pro/processing/scheduler_spec.rb
- spec/lib/karafka/processing/jobs_queue_spec.rb
- spec/lib/karafka/processing/scheduler_spec.rb
- spec/lib/karafka/server_spec.rb
This is a LOW LEVEL API for building state-aware schedulers.
This PR introduces a low-level API for building advanced multi-level schedulers.
Initially, we've wanted to introduce a separate workers' polls management for work distribution; however, due to the nature of work and the fact that it is often dynamically assigned, such an approach would drastically limit us. For example user would be forced to assign idle threads for LRJ (assuming wanted to have 2 workers) to all processes even if they would not have any LRJs assignments.
This API mitigates this by allowing to introduce a pre-buffer with active work distribution on ticks. With that we can make smart state based decisions on final work scheduling depending on the resources availability and assignmnets.
No performance regression. …
> Stateful state-aware scheduling API

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/base_consumer.rb
- lib/karafka/connection/listener.rb
- lib/karafka/instrumentation/logger_listener.rb
- lib/karafka/instrumentation/notifications.rb
- lib/karafka/instrumentation/vendors/datadog/logger_listener.rb
- lib/karafka/pro/processing/strategies/aj/lrj_mom_vp.rb
- lib/karafka/pro/processing/strategies/default.rb
- lib/karafka/pro/processing/strategies/lrj/default.rb
- lib/karafka/pro/processing/strategies/lrj/mom.rb
- lib/karafka/pro/processing/strategies/vp/default.rb
- lib/karafka/processing/executor.rb
- lib/karafka/processing/jobs/base.rb
- lib/karafka/processing/jobs/consume.rb
- lib/karafka/processing/strategies/base.rb
- lib/karafka/processing/strategies/default.rb
- lib/karafka/version.rb
- spec/integrations/instrumentation/before_enqueue_jobs_tracking_spec.rb
- spec/lib/karafka/instrumentation/logger_listener_spec.rb
- spec/lib/karafka/pro/active_job/consumer_spec.rb
- spec/lib/karafka/pro/base_consumer_spec.rb
- spec/lib/karafka/pro/processing/jobs/consume_non_blocking_spec.rb
- spec/lib/karafka/pro/processing/strategies/base_spec.rb
- spec/lib/karafka/pro/processing/strategies_spec.rb
- spec/lib/karafka/processing/executor_spec.rb
- spec/lib/karafka/processing/jobs/consume_spec.rb
- spec/lib/karafka/processing/strategies/base_spec.rb
This PR renames the `before_enqueue` to `before_schedule` as with the scheduler introduction we no longer run it before enqueuing but before scheduling that may not immediately enqueue job to the queue.
> rename before_enqueue to before_schedule

- CHANGELOG.md
- lib/karafka/connection/listener.rb
- lib/karafka/processing/jobs_queue.rb
- spec/lib/karafka/pro/processing/jobs_queue_spec.rb
- spec/lib/karafka/processing/jobs_queue_spec.rb
This PR removes concurreny ruby usage from the jobs queue. Part of retiring of https://github.com/karafka/karafka/issues/1741
> remove concurent ruby from the jobs queue

- CHANGELOG.md
- lib/karafka/pro/performance_tracker.rb
This PR removes the rest of concurrent-ruby from karafka
all is left is the karafka-core pieces
ref https://github.com/karafka/karafka/issues/1741
> Remove rest of concurrent ruby from Karafka

- CHANGELOG.md
- lib/karafka/instrumentation/vendors/kubernetes/liveness_listener.rb
- spec/integrations/instrumentation/vendors/kubernetes/consuming_liveness_parallel_regular_flow_spec.rb
- spec/integrations/instrumentation/vendors/kubernetes/consuming_liveness_parallel_timeout_flow_spec.rb
- spec/integrations/instrumentation/vendors/kubernetes/consuming_liveness_timeout_flow_spec.rb
- spec/integrations/instrumentation/vendors/kubernetes/liveness_all_good_spec.rb
- spec/integrations/instrumentation/vendors/kubernetes/non_existing_until_running_spec.rb
- spec/integrations/instrumentation/vendors/kubernetes/polling_liveness_timeout_flow_spec.rb
- spec/integrations/rails/rails71_pristine/with_kubernetes_listener_in_the_console/Gemfile
- spec/integrations/rails/rails71_pristine/with_kubernetes_listener_in_the_console/console_with_rails_spec.rb
This PR changes when we initialize the TCP listener for k8s liveness.
Instead of subscribing on initialization, we subscribe ONLY on running. This can now be done since while ago we reworked how embedded mode changes statuses.
This will also allow us to simplify the docs and remove the:
```ruby
if ENV['KARAFKA_LIVENESS'] == true
listener = ::Karafka::Instrumentation::Vendors::Kubernetes::LivenessListener.new(
)
Karafka.monitor.subscribe(listener)
end
```
recommendation.
> initialize k8s on running

- spec/integrations/consumption/strategies/dlq/with_rolling_error_spec.rb
This fix makes sure that we always operate with at least 3 messages. While this is not always the case with Kafka, this check in spec ensures it is predictable.
close https://github.com/karafka/karafka/issues/1804
> Stabilize unstable spec

- CHANGELOG.md
- lib/karafka/base_consumer.rb
- spec/integrations/consumption/producing_with_aliases_spec.rb
close https://github.com/karafka/karafka/issues/1810
> Alias `#produce_sync` and `#produce_async` in consumer

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/contracts/consumer_group.rb
- lib/karafka/pro/routing/features/multiplexing.rb
- lib/karafka/pro/routing/features/multiplexing/consumer_group.rb
- lib/karafka/pro/routing/features/multiplexing/patches/contracts/consumer_group.rb
- lib/karafka/pro/routing/features/patterns/detector.rb
- lib/karafka/routing/builder.rb
- spec/integrations/pro/consumption/multiplexing/with_same_topic_in_multiple_subscription_groups_spec.rb
- spec/integrations/pro/routing/with_multiplexed_subscription_group_spec.rb
- spec/integrations/pro/routing/with_same_topic_in_multiple_same_subscription_groups_spec.rb
- spec/integrations/pro/routing/with_same_topic_in_multiple_subscription_groups_spec.rb
- spec/integrations/routing/with_same_topic_in_multiple_subscription_groups_spec.rb
- spec/lib/karafka/pro/routing/features/multiplexing/consumer_group_spec.rb
- spec/lib/karafka/pro/routing/features/multiplexing/patches/contracts/consumer_group_spec.rb
- spec/lib/karafka/pro/routing/features/multiplexing_spec.rb
This feature allows for running multiple parallel connections for data of the same topic from a single process.
It should allow for much better parallelism when lagging on topics that do not have as many processes as partitions and cannot use VPs due to the nature of their data.
close https://github.com/karafka/karafka/issues/1604
> Multiplexing

- CHANGELOG.md
- lib/karafka/pro/routing/features/non_blocking_job.rb
- lib/karafka/pro/routing/features/non_blocking_job/topic.rb
- spec/integrations/pro/consumption/strategies/lrj/default/fast_non_blocking_spec.rb
- spec/integrations/pro/consumption/strategies/lrj/default/processing_via_non_blocking_spec.rb
- spec/lib/karafka/pro/routing/features/non_blocking_job/topic_spec.rb
- spec/lib/karafka/pro/routing/features/non_blocking_job_spec.rb
This PR aliases LRJ via `non_blocking` to allow for indication in routing that LRJ is set to avoid blocking and not to run LRJ.
While conceptually it uses the same code, the expression "non blocking" and "long-running" have different indication
> alias lrj as non blocking

- CHANGELOG.md
- lib/karafka/app.rb
- lib/karafka/process.rb
- lib/karafka/routing/topic.rb
- lib/karafka/status.rb
Since class eval methods do not have closures, it should be slightly better on the memory side and less risky on the scope. Plus it is a bit faster in general.
> replace define method with class eval

- spec/integrations/rebalancing/lost_partition_revoked_execution_time_spec.rb
Just a simple spec to make sure that OSS revocation does not run prior to revoked job finishing.
> Extra revoke time spec

- lib/karafka/errors.rb
- lib/karafka/pro/processing/strategies/default.rb
- lib/karafka/pro/processing/strategies/vp/default.rb
- spec/integrations/pro/consumption/transactions/lost_assignment_with_offset_storage_spec.rb
- spec/integrations/pro/consumption/transactions/lost_assignment_without_offset_storage_spec.rb
- spec/integrations/pro/consumption/transactions/vps/lost_assignment_with_offset_storage_spec.rb
- spec/integrations/pro/consumption/transactions/vps/lost_assignment_without_offset_storage_spec.rb
This PR makes sure we raise an exception if we want to store offset inside a transaction that will not finish successfully anyhow.
> prevent eos from kicking in when assignment is lost

- Gemfile
- Gemfile.lock
- lib/karafka.rb
- lib/karafka/constraints.rb
- lib/karafka/errors.rb
- spec/integrations/web/incompatible_version_pristine/Gemfile
- spec/integrations/web/incompatible_version_pristine/console_with_rails_spec.rb
- spec/lib/karafka/constraints_spec.rb
since bundler does not support optional dependencies, we need to check web UI (if used) to make sure older than 0.7 is not used as long as we do not do direct 1:1 locks like rails.
> verify constraints of web

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/helpers/async.rb
- lib/karafka/version.rb
this PR ensures, that in case we run `#async_call` few times in parallel, it is safe.
This is not a bug or anything ATM but we need to alter this behaviour for forks.
> ensure parallel executions of async are ok

- lib/karafka/instrumentation/vendors/datadog/metrics_listener.rb
- spec/integrations/instrumentation/vendors/datadog/metrics_flow_with_distributions_spec.rb
- spec/support/vendors/datadog/statsd_dummy_client.rb
Currently, histogram metrics are emitted as histograms in the Datadog listener.
This PR introduces an option to emit these metrics as distributions instead. This makes the calculated percentiles more accurate in case there are multiple consumers running on different hosts (or rather when multiple DD agents are being used).
More info can be found in the [DD documentation](https://docs.datadoghq.com/metrics/types/?tab=distribution#metric-types).
> Add `use_distributions` setting to Datadog::MetricsListener

- CHANGELOG.md
- config/locales/pro_errors.yml
- lib/karafka/connection/client.rb
- lib/karafka/pro/iterator/expander.rb
- lib/karafka/pro/iterator/tpl_builder.rb
- lib/karafka/pro/routing/features/direct_assignments.rb
- lib/karafka/pro/routing/features/direct_assignments/config.rb
- lib/karafka/pro/routing/features/direct_assignments/contracts/consumer_group.rb
- lib/karafka/pro/routing/features/direct_assignments/contracts/topic.rb
- lib/karafka/pro/routing/features/direct_assignments/subscription_group.rb
- lib/karafka/pro/routing/features/direct_assignments/topic.rb
- lib/karafka/pro/routing/features/swarm/topic.rb
- lib/karafka/routing/subscription_group.rb
- spec/integrations/pro/consumption/direct_assignments/all_partitions_spec.rb
- spec/integrations/pro/consumption/direct_assignments/beyond_poll_interval_spec.rb
- spec/integrations/pro/consumption/direct_assignments/from_earliest_spec.rb
- spec/integrations/pro/consumption/direct_assignments/marking_as_consumed_spec.rb
- spec/integrations/pro/consumption/direct_assignments/multi_topic_in_one_cg_spec.rb
- spec/integrations/pro/consumption/direct_assignments/transactions_support_spec.rb
- spec/integrations/pro/encryption/consumption/with_key_mismatch_spec.rb
- spec/integrations/pro/routing/direct_assignments/with_mixed_group_spec.rb
- spec/lib/karafka/pro/routing/features/direct_assignments/config_spec.rb
- spec/lib/karafka/pro/routing/features/direct_assignments/contracts/consumer_group_spec.rb
- spec/lib/karafka/pro/routing/features/direct_assignments/contracts/topic_spec.rb
- spec/lib/karafka/pro/routing/features/direct_assignments/subscription_group_spec.rb
- spec/lib/karafka/pro/routing/features/direct_assignments/topic_spec.rb
- spec/lib/karafka/pro/routing/features/direct_assignments_spec.rb
This PR provides ability do assign direct ownership over topics and partitions bypassing the automatic group management from kafka. This can be used for stream merging, window processing, and other advanced features.
> Direct assignments

- CHANGELOG.md
- lib/karafka/connection/client.rb
- lib/karafka/connection/proxy.rb
- lib/karafka/pro/iterator.rb
- lib/karafka/setup/config.rb
- spec/integrations/pro/iterator/stop_start_with_marking_spec.rb
- spec/lib/karafka/connection/proxy_spec.rb
close https://github.com/karafka/karafka/issues/1809
this PR also moves some of the generic abstraction to rdkafka proxy and caches the proxy wrapper not to create it when not needed.
> introduce marking as consumed in the iterator

- CHANGELOG.md
- lib/karafka/connection/client.rb
- lib/karafka/connection/listener.rb
- spec/integrations/instrumentation/statistics_publishing_on_long_poll_spec.rb
- spec/integrations/shutdown/fast_shutdown_on_long_polling_spec.rb
- spec/lib/karafka/connection/client_spec.rb
- spec/lib/karafka/connection/listener_spec.rb
close https://github.com/karafka/karafka-web/issues/285
close https://github.com/karafka/karafka/issues/1957
> Improve shutdown when using long polling setup (high `max_wait_time`)

- CHANGELOG.md
- lib/karafka/connection/client.rb
- lib/karafka/connection/listener.rb
- lib/karafka/pro/processing/jobs_queue.rb
- lib/karafka/processing/jobs_queue.rb
- spec/integrations/pro/consumption/fast_non_blocking_unlock_spec.rb
- spec/lib/karafka/pro/processing/jobs_queue_spec.rb
close https://github.com/karafka/karafka/issues/1965
This PR supports job queue auto-unlock on the async locked timeouts for millisecond precision unlocking in between subscription groups.
It also fixes a case where the periodic jobs scheduler would kick in too often because of jobs being finished and causing re-wait check
> support time sensitive auto-unlock

- CHANGELOG.md
- config/locales/errors.yml
- lib/karafka/admin.rb
- lib/karafka/connection/proxy.rb
- lib/karafka/contracts/config.rb
- lib/karafka/setup/config.rb
- spec/lib/karafka/admin_spec.rb
- spec/lib/karafka/contracts/config_spec.rb
This PR improves admin by using a limited queries for per-topic operations (much faster on large clusters) + exposes `#topic_info` similar to `#cluster_info` that will be used in web-ui.
It also wraps metadata request with the proxy for granular timeout control
> optimize admin and expose `topic_info` admin API

- lib/karafka/admin.rb
- spec/integrations/admin/read_lags/inactive_topics_lags_spec.rb
Simple alteration to allow reading inactive groups lags. Useful when we have a multi-app setup.
> Allow read lags on inactive cgs

- lib/active_job/queue_adapters/karafka_adapter.rb
- spec/lib/active_job/queue_adapters/karafka_adapter_spec.rb
For any ActiveJob adapter, `#enqueue_all` method should return the total number of jobs enqueued.
So that `enqueued_count` set by `instrument_enqueue_all` is as expected: 
https://github.com/rails/rails/blob/main/activejob/lib/active_job/enqueuing.rb#L17
https://github.com/rails/rails/blob/main/activejob/lib/active_job/instrumentation.rb#L10
Otherwise, it fails here: https://github.com/rails/rails/blob/main/activejob/lib/active_job/log_subscriber.rb#L68
> make #enqueue_all output compatible with ActiveJob.perform_all_later

- CHANGELOG.md
- config/locales/errors.yml
- lib/karafka/base_consumer.rb
- lib/karafka/pro/processing/strategies/aj/dlq_ftr_lrj_mom.rb
- lib/karafka/pro/processing/strategies/aj/dlq_ftr_lrj_mom_vp.rb
- lib/karafka/pro/processing/strategies/aj/dlq_ftr_mom.rb
- lib/karafka/pro/processing/strategies/aj/dlq_ftr_mom_vp.rb
- lib/karafka/pro/processing/strategies/aj/dlq_lrj_mom.rb
- lib/karafka/pro/processing/strategies/aj/dlq_lrj_mom_vp.rb
- lib/karafka/pro/processing/strategies/aj/dlq_mom.rb
- lib/karafka/pro/processing/strategies/aj/dlq_mom_vp.rb
- lib/karafka/pro/processing/strategies/dlq/default.rb
- lib/karafka/processing/strategies/aj_dlq_mom.rb
- lib/karafka/processing/strategies/dlq.rb
- lib/karafka/routing/features/dead_letter_queue/config.rb
- lib/karafka/routing/features/dead_letter_queue/contracts/topic.rb
- lib/karafka/routing/features/dead_letter_queue/topic.rb
- spec/integrations/consumption/strategies/dlq/with_sync_dispatch_spec.rb
- spec/integrations/consumption/strategies/dlq/with_sync_marking_spec.rb
- spec/integrations/pro/consumption/strategies/dlq/default/details_dispatch_transfer_spec.rb
- spec/integrations/pro/consumption/strategies/dlq/default/with_sync_dispatch_spec.rb
- spec/integrations/pro/consumption/strategies/dlq/default/with_sync_marking_spec.rb
- spec/lib/karafka/routing/features/dead_letter_queue/contracts/topic_spec.rb
this PR allows for selection whether we want to mark as consumed async or sync post dispatch on dlq and whether we want to dispatch sync or async (in transactions it is irrelevant)
close https://github.com/karafka/karafka/issues/1994
> improve dlq dispatch warranties

- lib/karafka/routing/router.rb
- spec/integrations/admin/read_topic/with_default_for_non_routed_topic_spec.rb
- spec/integrations/admin/read_topic/with_defaults_but_overwritten_in_routes_spec.rb
https://github.com/karafka/karafka/issues/2015
> Fix default deserializer inheritance on dynamically built admin topics fetches

- spec/integrations/pro/consumption/patterns/post_detected_with_default_deserializers_spec.rb
simple spec to ensure that late pattern matched topics use defaults if not overwritten.
> add extra pattern and defaults spec

- CHANGELOG.md
- lib/karafka/instrumentation/logger_listener.rb
- spec/lib/karafka/instrumentation/logger_listener_spec.rb
this PR changes how we report unrecognized errors. Thanks to this change we will no longer raise and we will report, so we can also ship errors from web-ui, etc.
> support custom errors

- .github/workflows/ci.yml
Similar to rdkafka, this should not be our policy when this can be upgraded easily.
> Give up on running .0

- CHANGELOG.md
- lib/karafka/admin.rb
- spec/integrations/admin/consumer_groups/seek_consumer_group/to_earliest_latest_par_partition_spec.rb
- spec/integrations/admin/consumer_groups/seek_consumer_group/to_earliest_on_topic_spec.rb
- spec/integrations/admin/consumer_groups/seek_consumer_group/to_earliest_on_topic_via_false_spec.rb
- spec/integrations/admin/consumer_groups/seek_consumer_group/to_latest_spec.rb
I decided not to provide negative lookups as this can be easily implemented already using `read_watermark_offsets`:
```ruby
highwatermark_offset = Karafka::Admin.read_watermark_offsets('topic', 2).last
Karafka::Admin.seek_consumer_group('group-id', { 'topic' => { 2 => highwatermark_offset - 100 } })
```
close https://github.com/karafka/karafka/issues/2063
> Supports moving offset to `:earliest` and `:latest`

- spec/integrations/consumption/pausing_not_unlocking_spec.rb
This spec ensures that post-pause locking still works.
> Extra spec illustrating that pausing won't bypass max.poll

- spec/integrations/testing/rspec_pristine/Gemfile
- spec/integrations/testing/rspec_pristine/assertions.rb
- spec/integrations/testing/rspec_pristine/test_flow_with_marking_spec.rb
Adds specs to ensure deserializers for minitest and rspec work as expected.
ref https://github.com/karafka/karafka-testing/pull/203
> add karafka-testing regression specs

- lib/karafka/templates/karafka.rb.erb
Hey! Thanks for your hard work on the gem! Just started using it, exciting stuff! This PR just fixes a small typo in `karafka.rb`  template
> Fix karafka.rb template typo

- lib/karafka/connection/client.rb
Recently, after upgrading to Karafka 2.4.0 by mistake, I encountered this issue https://github.com/karafka/karafka/issues/2085. There was no error reported on staging and production servers, the Karafka process appeared to be up and running but didn't consume any messages. We had to enable the debug mode in local host to understand what went wrong.
So for errors like `topic_authorization_failed`, `group_authorization_failed` and `cluster_authorization_failed`, `rdkafka` will raise the error only on the first poll, from the second poll tick, the message will be always null and make it look good, but in fact, cause the entire `poll` return null result without any error: https://github.com/karafka/rdkafka-ruby/blob/2900f6aa0d281ef8c12918c076b1cbab3f0d86fe/lib/rdkafka/consumer.rb#L530-L531 …
> Add some more error codes to early report

- CHANGELOG.md
- config/locales/pro_errors.yml
- lib/karafka/pro/processing/partitioner.rb
- lib/karafka/pro/routing/features/virtual_partitions/config.rb
- lib/karafka/pro/routing/features/virtual_partitions/contracts/topic.rb
- lib/karafka/pro/routing/features/virtual_partitions/topic.rb
- spec/integrations/pro/consumption/strategies/vp/round_robin_with_direct_reducer_spec.rb
- spec/lib/karafka/pro/routing/features/virtual_partitions/contracts/topic_spec.rb
- spec/lib/karafka/pro/routing/features/virtual_partitions/topic_spec.rb
This PR extracts the default reducer code to a customizable reducer, allowing for the usage of custom reducers for better (wider) mapping of the virtual partition keys.
As shown in the included specs, the default reducer is good but may not cover all people's cases due to the nature of their keys or concurrency settings. This is compensated by giving them the ability to write their own.
close https://github.com/karafka/karafka/issues/2127
> Provide ability to use custom VP reducers

- CHANGELOG.md
- Gemfile.lock
- karafka.gemspec
make sure waterdrop 2.7.3 is required to be able to detect `idemponent?` on producers for altering in web ui
> require waterdrop 2.7.3

- CHANGELOG.md
- lib/karafka/instrumentation/logger_listener.rb
- lib/karafka/server.rb
- spec/lib/karafka/instrumentation/logger_listener_spec.rb
similar to waterdrop we lower the noise of time reporting
additionally I've also improved the forceful shutdown to prevent a situation when we hang on listener shutdown despite forceful.
close https://github.com/karafka/karafka/issues/2158
> improve logger listener instrumentation and shutdown

- Gemfile.lock
superseeds: https://github.com/karafka/karafka/pull/2162 because renovate messes up the 3.4 tests.
> bump karafka-testing

- CHANGELOG.md
- lib/karafka/connection/client.rb
This PR breaks the unsubscribe loop and delegates the final shutdown to the close when there is no time. It prevents us from getting into a wait loop if librdkafka cannot  deal with the unsubscribe fast.
> Improve shutdown by breaking the unsubscribe loop

- lib/karafka/constraints.rb
- spec/integrations/web/incompatible_version_pristine_0.7/console_with_rails_spec.rb
web 0.9 will work with karafka 2.4.8 as long as `#eofed` is not used, so no point in locking users.
> relax web constraints

- CHANGELOG.md
- lib/karafka.rb
- spec/integrations/rails/rails71_pristine/just-a-dependency/rails_setup_spec.rb
- spec/integrations/rails/rails71_pristine/just-a-loaded-dependency/Gemfile
- spec/integrations/rails/rails71_pristine/just-a-loaded-dependency/rails_setup_spec.rb
- spec/integrations/rails/rails71_pristine/just-a-not-loaded-dependency/Gemfile
- spec/integrations/rails/rails71_pristine/just-a-not-loaded-dependency/rails_setup_spec.rb
This PR introduces an ENV variable to disable auto-rails require when user wants to run Rails-less Karafka despite having Rails in the Gemfile.
> skip require rails on env

- config/locales/errors.yml
- lib/karafka/connection/listener.rb
- lib/karafka/routing/features/eofed.rb
- lib/karafka/routing/features/eofed/config.rb
- lib/karafka/routing/features/eofed/contracts/topic.rb
- lib/karafka/routing/features/eofed/topic.rb
- spec/integrations/consumption/eofed/error_recovery_spec.rb
- spec/integrations/consumption/eofed/marking_as_consumed_spec.rb
- spec/integrations/consumption/eofed/post_consumption_spec.rb
- spec/integrations/consumption/eofed/post_eof_state_change_spec.rb
- spec/integrations/consumption/eofed/when_eof_reached_on_an_empty_topic_spec.rb
- spec/integrations/consumption/eofed/when_eof_reached_on_multiple_empty_topics_spec.rb
- spec/integrations/consumption/eofed/without_eofed_on_spec.rb
- spec/integrations/pro/consumption/eofed/vps_with_eof_spec.rb
- spec/integrations/pro/consumption/periodic_jobs/with_eof_status_spec.rb
- spec/lib/karafka/routing/features/eofed/config_spec.rb
- spec/lib/karafka/routing/features/eofed/contracts/topic_spec.rb
- spec/lib/karafka/routing/features/eofed/topic_spec.rb
- spec/lib/karafka/routing/features/eofed_spec.rb
- spec/lib/karafka/routing/topic_spec.rb
This PR adds an `#eofed` routing setting to control if eofed should trigger a consumer action.
Without this it would not be possible to use fast eof messages yielding without triggering `#eofed` actions even if they would be pointless.
> Add conditional eof handling

- CHANGELOG.md
- lib/karafka/routing/topic.rb
- spec/integrations/routing/with_topic_inherited_settings_spec.rb
This PR improves how we draw routes. It allows to pass `:inherit` set to `true` to the kafka routing setting (as in spec) to make it merge with existing root config. This helps avoid full reconfiguration duplication to just change one flag.
> support partial kafka routing reconfiguration

- lib/karafka/pro/recurring_tasks/listener.rb
- lib/karafka/pro/recurring_tasks/serializer.rb
- spec/integrations/pro/recurring_tasks/logging_data_published_on_errors_spec.rb
- spec/integrations/pro/recurring_tasks/logging_data_published_spec.rb
- spec/lib/karafka/pro/recurring_tasks/listener_spec.rb
- spec/lib/karafka/pro/recurring_tasks/serializer_spec.rb
This PR adds karafka (not karafka-web) logging of failed executions. We do not instrument details because this is not an error tracker but execution ntracker. We instrument for consistency and better visibility.
> log failed executions of recurring tasks

- lib/karafka/processing/worker.rb
- lib/karafka/railtie.rb
- lib/karafka/setup/config.rb
This is a stab at removing the manual code reloading and instead wrapping execution (if integrated with a rails app) with the rails executor or reloader (depending on whether consumer_persistence is enabled or not). I was having some wild reloading issues in development that I could not seem to fix... but this does it!
This is how sidekiq handles this as well: https://github.com/sidekiq/sidekiq/blob/ed8b217d32f026acc1fae7221dca18d1baa86d11/lib/sidekiq/processor.rb#L135-L147
There seems to be other important things handled by the executor we likely want! (Query cache enabling/disabling, connection management -- I didn't try it out, but possibly we won't need the other initializer that clears AR connections on worker completion?) https://guides.rubyonrails.org/threading_and_code_execution.ht …
> Draft/WIP/Idea: Wrap worker/job execution with rails reloader or executor

- CHANGELOG.md
- lib/karafka/base_consumer.rb
- lib/karafka/instrumentation/logger_listener.rb
- lib/karafka/instrumentation/notifications.rb
- lib/karafka/processing/executor.rb
- lib/karafka/processing/strategies/default.rb
- spec/integrations/consumption/when_initialization_happens_spec.rb
- spec/integrations/instrumentation/initialized_flow_spec.rb
- spec/integrations/pro/consumption/periodic_jobs/initialized_prior_to_ticking_spec.rb
- spec/lib/karafka/base_consumer_spec.rb
- spec/lib/karafka/instrumentation/logger_listener_spec.rb
This PR adds new consumer `#initialized` method that can be used to setup some sub-components when all things related to consumer and its assignment are ready.
I noticed users overwrite the `#initialize` but the issue is, some pieces of the puzzle like `#topic` will be missing at this stage.
> Add post-initialize consumer hook for custom component bootstrapping

- lib/karafka/railtie.rb
I found this deprecation warning when ready to Rails 7.2 in my application.
> ActiveSupport::DeprecationException: DEPRECATION WARNING: `clear_active_connections!` currently only applies to connection pools in the current role (`writing`). In Rails 7.2, this method will apply to all known pools, regardless of role. To affect only those connections belonging to a specific role, pass the role name as an argument. To switch to the new behavior, pass `:all` as the role name. (called from loop at <internal:kernel>:187) (ActiveSupport::DeprecationException)
We can suppress this warning by passing `:all` to argument.
> Fix deprecation warning in `lib/karafka/railtie.rb`

- CHANGELOG.md
- lib/karafka/railtie.rb
since now we use the executor/reloader wrapper for Rails, connection management and other resources management is fully on Rails. Based on the docs, we no longer have to release or manage this manually.
superseeds https://github.com/karafka/karafka/pull/2257
ref https://github.com/karafka/karafka/pull/2233
> remove no longer needed ar connection management

- lib/karafka/instrumentation/vendors/appsignal/client.rb
- lib/karafka/instrumentation/vendors/appsignal/errors_listener.rb
- spec/support/vendors/appsignal/dummy_client.rb
* Register AppSignal probe with new helper
In AppSignal for Ruby gem 3.7 the recommended method for registering minutely probes has changed. In version 4 the old methods were removed.
Add a check to see if it listens to the new registration helper and if not, call the old helper.
* Use the AppSignal report_error helper if available
The AppSignal for Ruby gem introduced the `Appsignal.report_error` helper in Ruby gem version 3.10.0. This helper does what the client already did, check if there's a current transaction or not and report the error with `set_error` or `send_error`.
In version 4 of the Ruby gem the `report_error` helper also supports reporting multiple errors per transaction, so it's recommended to use this new helper.
* Update AppSignal Transaction initialization
In AppSignal …
> Update AppSignal client to support newer versions (#2260)

- .github/workflows/ci.yml
Per our maintenance policy, I'm removing 3.0 from CI to fully retire it in few weeks.
> retire ruby 3.0 ci

- lib/karafka/cli/topics/plan.rb
- spec/integrations/cli/declaratives/plan/when_with_partitions_spec.rb
We've recently started using the declarative topic management in our deploy pipeline, and its super convenient.
One thing I noticed is that whilst `karafka topics migrate` is conservative, and will never reduce the number of partitions on an existing topic, `karafka topics plan`'s output suggests otherwise.
Example output:
```tf
Following topics will be repartitioned:
~ topic-a:
~ partitions: "3" => "1"
~ topic-b:
~ partitions: "3" => "1"
~ topic-c:
~ partitions: "3" => "1"
```
This PR just tweaks the `karafka topics plan` command to ignore topics that have fewer topics in the declarative topics definition than exist on the broker.
> Don't report declarative partitions with fewer topics than on cluster

- .github/workflows/ci.yml
This PR is suppose to resolve issues because of using newer ActiveSupport and friends in Gemfile.lock that are not compatible with Ruby 3.1
We do want to support Ruby 3.1 but we also want to make sure we can run specs on newer versions with newer defaults.
Ref https://github.com/karafka/karafka/pull/2328/files
> resolve ruby 3.1 deps fallback

- CHANGELOG.md
- Gemfile.lock
- lib/karafka/connection/client.rb
- lib/karafka/instrumentation/vendors/kubernetes/liveness_listener.rb
- lib/karafka/version.rb
- spec/integrations/instrumentation/vendors/kubernetes/fenced_out_criticality_spec.rb
this PR fast tracks reporting on critical errors that won't be recovered and adds their awareness into the k8s state listener.
close https://github.com/karafka/karafka/issues/2327
> Report fast in criticals and support k8s criticals

- spec/integrations/instrumentation/statistics_callback_with_crashing_subscription_spec.rb
- spec/integrations/instrumentation/with_replaced_monitor_spec.rb
This PR adds scenario where monitor is wrapped with a custom one that can run stuff prior and after consumer consume execution and can wrap it with a block.
It also removes useless print
> add custom monitor scenario

- lib/karafka/routing/builder.rb
- spec/lib/karafka/routing/builder_spec.rb
This allows testing code to define its own routes _without_ blowing away the defaults. I've found this helpful when I have overall defaults that I want to keep around, but I want to test my own routing plugin with various routes.
> Add redraw method

- CHANGELOG.md
- lib/karafka/connection/client.rb
- lib/karafka/connection/rebalance_manager.rb
- spec/integrations/pro/consumption/transactions/post_revocation_cooperative_reclaim_spec.rb
- spec/integrations/pro/consumption/transactions/post_revocation_non_cooperative_reclaim_spec.rb
- spec/integrations/rebalancing/consecutive_reclaim_flow_cooperative_spec.rb
- spec/integrations/rebalancing/consecutive_reclaim_flow_spec.rb
- spec/integrations/rebalancing/revoke_reclaim_continuity_spec.rb
- spec/integrations/rebalancing/stored_reclaimed_continuity_cooperative_spec.rb
- spec/integrations/rebalancing/stored_reclaimed_continuity_spec.rb
- spec/lib/karafka/connection/rebalance_manager_spec.rb
This PR moves the post-revoked data revocation closer to the revocation event and removes no longer needed (because of this change) diffing of post-revoked messages via `lost_partitions`. Because we do cleanup now right after the revocation, we don't have to compute lost partitions anymore. Aside from fixing the below bug in transactional flows it also improves the general flow.
close https://github.com/karafka/karafka/issues/2370
A lot of extra specs are added just to cover various cases.
> improve rebalance flow

- spec/integrations/pro/consumption/transactions/post_revocation_cooperative_reclaim_spec.rb
- spec/integrations/pro/consumption/transactions/post_revocation_non_cooperative_reclaim_spec.rb
- spec/integrations/pro/rebalancing/transactions/revoke_reclaim_continuity_cooperative_spec.rb
- spec/integrations/pro/rebalancing/transactions/revoke_reclaim_continuity_spec.rb
- spec/integrations/rebalancing/consecutive_reclaim_flow_cooperative_spec.rb
- spec/integrations/rebalancing/consecutive_reclaim_flow_spec.rb
- spec/integrations/rebalancing/revoke_reclaim_continuity_spec.rb
We should not close librdkafka that often so instead to trigger rebalancing we re-use the same instance.
> Stabilize more specs

- spec/integrations/pro/recurring_tasks/state_publishing_frequency_spec.rb
This spec sometimes fails on this assertion, but the assertion conditions are not printed. This PR does not fix the issue with this spec but adds better reporting.
> improve spec debuggability

- CHANGELOG.md
- lib/karafka/pro/cleaner/messages/message.rb
- spec/integrations/pro/consumption/cleaner/without_metadata_spec.rb
- spec/integrations/pro/iterator/with_granular_cleaning_spec.rb
- spec/lib/karafka/pro/cleaner/messages/message_spec.rb
This PR allows for control what should be cleaned. Useful when metadata may still be needed but not the payload.
> Granular cleaning

- CHANGELOG.md
- lib/karafka/pro/processing/coordinators/filters_applier.rb
- lib/karafka/pro/processing/filters/base.rb
- lib/karafka/pro/processing/strategies/default.rb
- lib/karafka/pro/processing/strategies/ftr/default.rb
- lib/karafka/processing/strategies/default.rb
- spec/integrations/pro/consumption/offset_metadata/basic_automatic_flow_overwritten_last_marking_spec.rb
- spec/integrations/seek/back_without_reset_and_mark_again_spec.rb
In order to be able to move offsets freely with marking (for rebalance persistence) without having to deal with forced seek, this PR aligns Karafka behaviour with librdkafka allowing for older offsets storage and persistence. No integration specs (aside one which was expected) were affected.
Aside from that a new `#marking_cursor` API for Filtering is introduced to further support Web UI development.
Without this change our ability to mark from filtering API would be tampered as the offset position after moving back could not be persisted.
> Allow marking older offsets

- lib/karafka/connection/listener.rb
- lib/karafka/processing/coordinators_buffer.rb
This PR exposes the coordinators for my low-level internal APIs needs.
> expose coordinators from listener

- CHANGELOG.md
- lib/karafka/base_consumer.rb
- lib/karafka/connection/client.rb
- spec/lib/karafka/base_consumer_spec.rb
- spec/lib/karafka/pro/base_consumer_spec.rb
Since we're going to introduce low-level consumer bypassing flow controls into web UI, this had to be aligned so the listeners can get cohesive pause/resume data.
> enhance low level client.pause event with a timeout

- CHANGELOG.md
- lib/karafka/admin.rb
100 years ago does not work with confluent kafka 7.9.0 so we use a shorter but still long enough value
> use sane value for long ago

- lib/karafka/base_consumer.rb
#1374 [removed](https://github.com/karafka/karafka/pull/1374/files#diff-f2298aa0c0eee8d69c0c9e9919ee5fd97e5bc5f343d13d41e51739a6141c60cdR16-R17) the wrong docs from the `messages` field.
> Update BaseConsumer documentation to point to the correct class

- CHANGELOG.md
- Gemfile.lock
- config/locales/pro_errors.yml
- karafka.gemspec
- lib/karafka/pro/recurring_tasks/contracts/config.rb
- lib/karafka/pro/recurring_tasks/dispatcher.rb
- lib/karafka/pro/recurring_tasks/setup/config.rb
- lib/karafka/pro/routing/features/recurring_tasks/builder.rb
- spec/integrations/pro/recurring_tasks/logging_data_published_on_errors_spec.rb
- spec/integrations/pro/recurring_tasks/logging_data_published_spec.rb
- spec/integrations/pro/recurring_tasks/routes_creation_spec.rb
- spec/integrations/pro/recurring_tasks/state_publishing_frequency_spec.rb
- spec/integrations/pro/recurring_tasks/state_structure_spec.rb
- spec/integrations_helper.rb
- spec/lib/karafka/pro/recurring_tasks/contracts/config_spec.rb
Because we're namespacing topics in web ui (topic.name) I wanted to align it first in karafka as well.
I guess this will force us to do 2.5 release but I don't see it as a problem because of the scope of stuff released (a lot)
> align config topics naming convention

- CHANGELOG.md
- lib/karafka/pro/processing/partitioner.rb
If the number of jobs is less than the number of available threads, the scheduling order doesn't matter much, because all jobs will start simultaneously - each job will get its dedicated thread.
However, the LJF (Longest Job First) algorithm starts to provide benefits precisely when you have more jobs than threads. In such cases:
- The longest jobs will start first
- Shorter jobs will run in parallel with longer ones or fill in "gaps" after completed jobs
- The total execution time (makespan) will be smaller than with random allocation
In a typical Karafka data processing scenario, you often have more message groups (jobs) than consumer threads, so LJF will be beneficial. This is especially noticeable in batch processing, where message groups arrive in large quantities.
Implementing LJF …
> Reorder VP jobs to use LJF

- CHANGELOG.md
- lib/karafka.rb
- spec/lib/karafka_spec.rb
We should not run `Bundler.with_unbundled_env` multiple times because it is not atomic.
> cache root not to run `Bundler.with_unbundled_env` multiple times

- spec/spec_helper.rb
This PR lowers a bit the required coverage because we mostly cover stuff with integrations.
> lower coverage requirement

- CHANGELOG.md
- bin/integrations
- lib/karafka/cli.rb
- lib/karafka/cli/topics.rb
- lib/karafka/cli/topics/align.rb
- lib/karafka/cli/topics/base.rb
- lib/karafka/cli/topics/create.rb
- lib/karafka/cli/topics/delete.rb
- lib/karafka/cli/topics/help.rb
- lib/karafka/cli/topics/repartition.rb
- lib/karafka/errors.rb
- spec/integrations/admin/acl_flow_spec.rb
- spec/integrations/cli/cli_unknown_spec.rb
- spec/integrations/cli/declaratives/align/incorrectly_spec.rb
- spec/integrations/pro/recurring_tasks/smarter_reconfiguration_spec.rb
- spec/lib/karafka/cli/topics/help_spec.rb
- spec/lib/karafka/cli_spec.rb
Declarative topics will now (after karafka-rdkafka release) print full messages including broker errors and in the correct order.
Also topic alignments are now independent for much better reporting.
This PR also adds the help command for declarative topics.
close https://github.com/karafka/karafka/issues/2612
close https://github.com/karafka/karafka/issues/2604
> improve declarative topics reporting + add declarative topics CLI help

- CHANGELOG.md
- lib/karafka/swarm/node.rb
- spec/lib/karafka/swarm/node_spec.rb
Replaces the Linux-specific pidfd approach with a ppid (parent process ID) check for detecting orphaned swarm nodes. This change improves cross-platform compatibility (works on macOS, BSD, etc.) and reduces complexity while maintaining the same functionality. The ppid check is cheaper and more portable than maintaining file descriptors with pidfd.
> Replace pidfd with ppid check for orphan detection in swarm
